import { useEffect, useRef, useState, type ChangeEvent, type MouseEvent as ReactMouseEvent, type PointerEvent as ReactPointerEvent } from "react";
import { createPortal } from "react-dom";
import type { PlayerDisplayFogPoint, PlayerDisplayFogRegion, PlayerDisplayGridSettings, PlayerDisplayToken, PlayerDisplayWall } from "@shadow-edge/shared-types";
import { api } from "./api";

type Props = { campaignId: string; open: boolean; onClose: () => void };
const youtubeId = (raw: string) => { try { const u=new URL(raw.trim()); const h=u.hostname.replace(/^www\./,"").toLowerCase(); if(h==="youtu.be") return u.pathname.split("/").filter(Boolean)[0]??""; if(["youtube.com","m.youtube.com","youtube-nocookie.com"].includes(h)) return u.searchParams.get("v")||u.pathname.match(/^\/(?:embed|shorts)\/([^/]+)/)?.[1]||""; } catch { return ""; } return ""; };
const eventPoint = (event: ReactPointerEvent<SVGSVGElement>): PlayerDisplayFogPoint => { const r=event.currentTarget.getBoundingClientRect(); return {x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))}; };
const svgPoints = (points: PlayerDisplayFogPoint[]) => points.map(p=>`${p.x*1000},${p.y*1000}`).join(" ");
const hexGridPath=(size:number)=>{const r=size*1000,w=r*1.732;const hex=(cx:number,cy:number)=>`M ${cx} ${cy-r} L ${cx+w/2} ${cy-r/2} L ${cx+w/2} ${cy+r/2} L ${cx} ${cy+r} L ${cx-w/2} ${cy+r/2} L ${cx-w/2} ${cy-r/2} Z `;return hex(w/2,r)+hex(w*1.5,r)+hex(0,r*2.5)+hex(w,r*2.5)+hex(w*2,r*2.5);};

export function SessionMapModal({campaignId,open,onClose}:Props){
  const [imageUrl,setImageUrl]=useState(""); const [mediaType,setMediaType]=useState<"image"|"youtube">("image");
  const [sourceUrl,setSourceUrl]=useState(""); const [title,setTitle]=useState("Карта приключения");
  const [regions,setRegions]=useState<PlayerDisplayFogRegion[]>([]); const [walls,setWalls]=useState<PlayerDisplayWall[]>([]);
  const [token,setToken]=useState<PlayerDisplayToken|null>(null); const [tool,setTool]=useState<"fog"|"wall"|"token"|null>(null);
  const [draft,setDraft]=useState<PlayerDisplayFogPoint[]>([]); const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState(""); const [displayUrl,setDisplayUrl]=useState("");
  const [grid,setGrid]=useState<PlayerDisplayGridSettings>({type:"none",size:.08,color:"#ffffff",opacity:.35});
  const [regionMenu,setRegionMenu]=useState<{kind:"region"|"wall";id:string;x:number;y:number}|null>(null);
  const drawing=useRef(false); const draftRef=useRef<PlayerDisplayFogPoint[]>([]);
  const previewPlayer=useRef<HTMLIFrameElement|null>(null); const [previewMuted,setPreviewMuted]=useState(true);
  const mapShell=useRef<HTMLDivElement|null>(null);

  useEffect(()=>{if(!open)return; const close=(e:KeyboardEvent)=>e.key==="Escape"&&onClose(); document.addEventListener("keydown",close); const old=document.body.style.overflow; document.body.style.overflow="hidden"; return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=old;};},[onClose,open]);
  if(!open||typeof document==="undefined")return null;

  const publish=async(nextRegions=regions,nextWalls=walls,nextToken=token,openDisplay=false,nextGrid=grid)=>{if(!imageUrl){setNotice("Сначала загрузите или подключите карту.");return;}const shell=mapShell.current;const mapAspectRatio=mediaType==="youtube"?16/9:(shell&&shell.clientHeight?shell.clientWidth/shell.clientHeight:1);setBusy(true);try{const share=await api.showPlayerDisplayImage(campaignId,{alt:title||"Карта игровой сессии",fogRegions:nextRegions,grid:nextGrid,walls:nextWalls,token:nextToken??undefined,mapAspectRatio,mediaType,sessionMap:true,title,url:imageUrl});setDisplayUrl(share.url);setNotice("Экран игроков обновлён.");if(openDisplay)window.open(share.url,"shadow-edge-session-display")?.focus();}catch(error){setNotice(error instanceof Error?error.message:"Не удалось обновить экран игроков.");}finally{setBusy(false);}};
  const updateRegions=(next:PlayerDisplayFogRegion[])=>{setRegions(next);if(displayUrl)void publish(next,walls,token);};
  const updateWalls=(next:PlayerDisplayWall[])=>{setWalls(next);if(displayUrl)void publish(regions,next,token);};
  const updateToken=(next:PlayerDisplayToken|null)=>{setToken(next);if(displayUrl)void publish(regions,walls,next);};
  const updateGrid=(next:PlayerDisplayGridSettings)=>{setGrid(next);if(displayUrl)void publish(regions,walls,token,false,next);};
  const resetFog=()=>{setRegions([]);setWalls([]);setToken(null);setDraft([]);draftRef.current=[];};
  const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setBusy(true);try{const result=await api.uploadImage(campaignId,file);setImageUrl(result.url);setMediaType("image");setTitle(file.name.replace(/\.[^.]+$/,"")||"Карта приключения");resetFog();setNotice("Карта загружена. Обведите скрываемые области.");}catch(error){setNotice(error instanceof Error?error.message:"Не удалось загрузить карту.");}finally{setBusy(false);event.target.value="";}};
  const useUrl=()=>{const value=sourceUrl.trim();if(!value)return;const id=youtubeId(value);if(id){setImageUrl(value);setMediaType("youtube");setTitle("Анимированная карта");resetFog();setNotice("YouTube-карта подключена. Обведите зоны тумана.");return;}try{const parsed=new URL(value);if(!/^https?:$/.test(parsed.protocol))throw new Error();setImageUrl(value);setMediaType("image");resetFog();setNotice("Карта по ссылке подключена.");}catch{setNotice("Укажите прямую ссылку на изображение или YouTube.");}};
  const begin=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!tool||event.button!==0)return;setRegionMenu(null);const p=eventPoint(event);if(tool==="token"){updateToken({...p,visionRadius:token?.visionRadius??.22});drawing.current=true;event.currentTarget.setPointerCapture(event.pointerId);return;}event.currentTarget.setPointerCapture(event.pointerId);drawing.current=true;draftRef.current=[p];setDraft([p]);};
  const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!tool||!drawing.current)return;const p=eventPoint(event);if(tool==="token"){setToken({...p,visionRadius:token?.visionRadius??.22});return;}const last=draftRef.current.at(-1);if(last&&Math.hypot(p.x-last.x,p.y-last.y)<.006)return;draftRef.current=[...draftRef.current,p];setDraft(draftRef.current);};
  const finish=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!drawing.current)return;drawing.current=false;event.currentTarget.releasePointerCapture(event.pointerId);if(tool==="token"){const next={...eventPoint(event),visionRadius:token?.visionRadius??.22};setToken(next);if(displayUrl)void publish(regions,walls,next);return;}const points=draftRef.current;draftRef.current=[];setDraft([]);if(tool==="wall"){if(points.length<2)return;const next=[...walls,{id:crypto.randomUUID?.()??`wall-${Date.now()}`,start:points[0],end:points.at(-1)!,points,disabled:false}];updateWalls(next);setNotice(`Добавлена стена ${next.length}.`);return;}if(points.length<3){setNotice("Нарисуйте область чуть длиннее.");return;}const next=[...regions,{id:crypto.randomUUID?.()??`region-${Date.now()}`,points,revealed:false}];updateRegions(next);setNotice(`Добавлена область ${next.length}. Она скрыта.`);};
  const togglePreviewSound=()=>{const next=!previewMuted;previewPlayer.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func:next?"mute":"unMute",args:[]}),"https://www.youtube-nocookie.com");setPreviewMuted(next);};
  const openRegionMenu=(event:ReactMouseEvent<SVGElement>,kind:"region"|"wall",id:string)=>{event.preventDefault();event.stopPropagation();setRegionMenu({kind,id,x:event.clientX,y:event.clientY});};
  const deleteRegionFromMenu=()=>{if(!regionMenu)return;if(regionMenu.kind==="wall")updateWalls(walls.filter(wall=>wall.id!==regionMenu.id));else updateRegions(regions.filter(region=>region.id!==regionMenu.id));setRegionMenu(null);};
  const toggleWallFromMenu=()=>{if(!regionMenu||regionMenu.kind!=="wall")return;updateWalls(walls.map(wall=>wall.id===regionMenu.id?{...wall,disabled:!wall.disabled}:wall));setRegionMenu(null);};

  return createPortal(<div className="session-map-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();else setRegionMenu(null);}}><section aria-modal="true" className="session-map-modal" role="dialog">
    <header className="session-map-head"><div><p className="eyebrow">Режим сессии</p><h2>Карта на телевизоре</h2><p>Обводите комнаты и открывайте их по мере исследования.</p></div><button aria-label="Закрыть" className="ghost" onClick={onClose} type="button">✕</button></header>
    <div className="session-map-layout"><div className="session-map-stage">{imageUrl?<div className={`session-map-image-shell ${mediaType==="youtube"?"video":""}`} ref={mapShell}>
      {mediaType==="youtube"?<iframe allow="autoplay; encrypted-media" ref={previewPlayer} src={`https://www.youtube-nocookie.com/embed/${youtubeId(imageUrl)}?autoplay=1&mute=1&loop=1&playlist=${youtubeId(imageUrl)}&controls=0&disablekb=1&enablejsapi=1&fs=0&playsinline=1&rel=0`} title={title}/>:<img alt={title} src={imageUrl}/>}
      {grid.type!=="none"?<svg className="session-map-grid-preview" preserveAspectRatio="none" viewBox="0 0 1000 1000"><defs><pattern height={grid.type==="hex"?grid.size*3000:grid.size*1000} id="master-grid" patternUnits="userSpaceOnUse" width={grid.type==="hex"?grid.size*3464:grid.size*1000}>{grid.type==="square"?<path d={`M ${grid.size*1000} 0 H 0 V ${grid.size*1000}`} fill="none" stroke={grid.color} strokeWidth="1.5"/>:<path d={hexGridPath(grid.size)} fill="none" stroke={grid.color} strokeWidth="1.5"/>}</pattern></defs><rect fill="url(#master-grid)" height="1000" opacity={grid.opacity} width="1000"/></svg>:null}
      <svg className={`session-map-region-editor ${tool?"drawing":""}`} onContextMenu={event=>event.preventDefault()} onPointerDown={begin} onPointerMove={move} onPointerUp={finish} preserveAspectRatio="none" viewBox="0 0 1000 1000">{regions.map((r,i)=><polygon className={r.revealed?"revealed":"hidden"} key={r.id} onContextMenu={event=>openRegionMenu(event,"region",r.id)} points={svgPoints(r.points)}><title>{`Область ${i+1}`}</title></polygon>)}{walls.map(w=>{const points=w.points?.length?w.points:[w.start,w.end];return <g key={w.id}><polyline className="map-wall-hit" onContextMenu={event=>openRegionMenu(event,"wall",w.id)} points={svgPoints(points)}/><polyline className={`map-wall ${w.disabled?"disabled":""}`} points={svgPoints(points)}/></g>;})}{token?<><ellipse className="vision-preview" cx={token.x*1000} cy={token.y*1000} rx={token.visionRadius*1000} ry={token.visionRadius*1000*(mediaType==="youtube"?16/9:(mapShell.current&&mapShell.current.clientHeight?mapShell.current.clientWidth/mapShell.current.clientHeight:1))}/><circle className="map-token" cx={token.x*1000} cy={token.y*1000} r="15"/></>:null}{draft.length>1?<polyline className={tool==="wall"?"draft wall-draft":"draft"} points={svgPoints(draft)}/>:null}</svg>
    </div>:<label className="session-map-dropzone"><strong>Загрузить карту</strong><span>PNG, JPG, WEBP или GIF до 10 МБ</span><input accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={upload} type="file"/></label>}</div>
    <aside className="session-map-controls"><label>Ссылка на карту или YouTube<div className="session-map-url-row"><input onChange={e=>setSourceUrl(e.target.value)} placeholder="https://…" value={sourceUrl}/><button className="ghost" onClick={useUrl} type="button">Подключить</button></div></label>
      {imageUrl?<label className="session-map-upload-small">Заменить карту<input accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={upload} type="file"/></label>:null}
      <label>Название сцены<input onChange={e=>setTitle(e.target.value)} value={title}/></label>
      {mediaType==="youtube"?<button className="ghost" onClick={togglePreviewSound} type="button">{previewMuted?"Включить музыку у мастера":"Выключить музыку у мастера"}</button>:null}
      <div className="session-map-tool-grid"><button className={tool==="fog"?"primary":"ghost"} disabled={!imageUrl} onClick={()=>setTool(tool==="fog"?null:"fog")} type="button">Туман</button><button className={tool==="wall"?"primary":"ghost"} disabled={!imageUrl} onClick={()=>setTool(tool==="wall"?null:"wall")} type="button">Стена</button><button className={tool==="token"?"primary":"ghost"} disabled={!imageUrl} onClick={()=>setTool(tool==="token"?null:"token")} type="button">Фишка</button></div>
      <details className="session-map-settings"><summary>Сетка карты <span>{grid.type==="none"?"выключена":grid.type==="square"?"квадраты":"гексы"}</span></summary><div className="session-map-settings-body"><div className="session-map-grid-types"><button className={grid.type==="none"?"primary":"ghost"} onClick={()=>updateGrid({...grid,type:"none"})} type="button">Нет</button><button className={grid.type==="square"?"primary":"ghost"} onClick={()=>updateGrid({...grid,type:"square"})} type="button">Квадраты</button><button className={grid.type==="hex"?"primary":"ghost"} onClick={()=>updateGrid({...grid,type:"hex"})} type="button">Гексы</button></div>{grid.type!=="none"?<><label>Размер клетки: {Math.round(grid.size*1000)}<input max="200" min="20" onChange={e=>updateGrid({...grid,size:Number(e.target.value)/1000})} type="range" value={Math.round(grid.size*1000)}/><small>Положите фигурку 25 мм на телевизор и совместите основание с клеткой.</small></label><div className="session-map-grid-style"><label>Цвет<input onChange={e=>updateGrid({...grid,color:e.target.value})} type="color" value={grid.color}/></label><label>Прозрачность: {Math.round(grid.opacity*100)}%<input max="100" min="5" onChange={e=>updateGrid({...grid,opacity:Number(e.target.value)/100})} type="range" value={Math.round(grid.opacity*100)}/></label></div></>:null}</div></details>
      {token?<label>Радиус зрения: {Math.round(token.visionRadius*100)}%<input max="80" min="5" onChange={event=>updateToken({...token,visionRadius:Number(event.target.value)/100})} type="range" value={Math.round(token.visionRadius*100)}/></label>:null}
      <p className="session-map-source-hint">Зажмите мышь и обведите комнату или зону. Контур замкнётся автоматически.</p>
      <div className="session-map-region-list">{regions.map((r,i)=><div className="session-map-region-row" key={r.id}><span>Область {i+1}</span><button className="ghost" onClick={()=>updateRegions(regions.map(item=>item.id===r.id?{...item,revealed:!item.revealed}:item))} type="button">{r.revealed?"Скрыть":"Показать"}</button><button aria-label="Удалить" className="ghost danger" onClick={()=>updateRegions(regions.filter(item=>item.id!==r.id))} type="button">✕</button></div>)}{!regions.length?<p className="session-map-tip">Нарисованных областей пока нет.</p>:null}</div>
      {walls.length?<div className="session-map-region-list">{walls.map((wall,index)=><div className="session-map-region-row" key={wall.id}><span>Стена {index+1}</span><button className="ghost" onClick={()=>updateWalls(walls.map(item=>item.id===wall.id?{...item,disabled:!item.disabled}:item))} type="button">{wall.disabled?"Включить":"Пропускать"}</button><button className="ghost danger" onClick={()=>updateWalls(walls.filter(item=>item.id!==wall.id))} type="button">Удалить</button></div>)}</div>:null}
      {token?<button className="ghost danger" onClick={()=>updateToken(null)} type="button">Убрать фишку</button>:null}
      <div className="session-map-actions-grid"><button className="ghost" onClick={()=>updateRegions(regions.map(r=>({...r,revealed:false})))} type="button">Скрыть всё</button><button className="ghost" onClick={()=>updateRegions(regions.map(r=>({...r,revealed:true})))} type="button">Показать всё</button></div>
      <button className="primary session-map-launch" disabled={busy||!imageUrl} onClick={()=>void publish(regions,walls,token,true)} type="button">{busy?"Обновляю…":displayUrl?"Открыть экран телевизора":"Запустить сцену"}</button>{displayUrl?<p className="session-map-tip">Туман, стены и положение фишки автоматически появляются на телевизоре.</p>:null}{notice?<p className="session-map-notice">{notice}</p>:null}
    </aside></div>
    {regionMenu?<div className="session-map-region-menu" onMouseDown={event=>event.stopPropagation()} style={{left:regionMenu.x,top:regionMenu.y}}>{regionMenu.kind==="wall"?<button onClick={toggleWallFromMenu} type="button">{walls.find(wall=>wall.id===regionMenu.id)?.disabled?"Блокировать зрение":"Пропускать зрение"}</button>:null}<button onClick={deleteRegionFromMenu} type="button">{regionMenu.kind==="wall"?"Удалить стену":"Удалить область"}</button></div>:null}
  </section></div>,document.body);
}
