import test from 'node:test';
import assert from 'node:assert/strict';
import {withAIProfile,aiActorSystem,aiExtraItems} from '../scripts/actor-ai-profile.mjs';
import {aiItemTemplate,aiRestorableFields,aiReceiptAfter} from '../scripts/actor-ai-ui.mjs';
import {actorPlan,basicAbility,safeHTML} from '../scripts/adapter.mjs';
const profile=()=>({id:'profile',mode:'enrich',edition:'2024',abilities:[],spells:[],skills:[],loot:[],casterLevel:5,castingAbility:'int'});
const record=()=>({key:'monster:test',kind:'monster',data:{title:'Test',statBlock:{actions:[{name:'Bow',toHit:'+5',damage:'1d8+3 piercing'}]},foundryAI:profile()}});
test('AI profiles clone source abilities and ignore stale or player profiles',()=>{const r=record();r.data.foundryAI.abilities=[{section:'actions',index:0,name:'Bow',damage:'1d8+3 piercing',animation:'bow',mechanics:{kind:'attack',attackMode:'ranged'}}];const before=structuredClone(r),result=withAIProfile(r);assert.deepEqual(r,before);assert.equal(result.data.statBlock.actions[0].animation,'bow');r.data.foundryAI.stale=true;assert.equal(withAIProfile(r),r);r.data.foundryAI.stale=false;r.kind='player';assert.deepEqual(aiActorSystem(r),{})});
test('enrichment uses deterministic full caster slots; source slots win without restoring current resources',()=>{const r=record(),system=aiActorSystem(r);assert.deepEqual(system.spells,{spell1:{override:4},spell2:{override:3},spell3:{override:2}});assert.equal(system.attributes.spellcasting,'int');assert.equal(system.details.spellLevel,5);r.data.statBlock.spellcasting={slots:[{level:'1',slots:'2'}]};assert.deepEqual(aiActorSystem(r).spells,{spell1:{override:2}});r.data.statBlock.spellcasting=null;r.data.foundryAI.mode='configure';assert.equal(aiActorSystem(r).spells,undefined)});
test('AI additions have stable keys and supplied loot is never duplicated',()=>{const r=record();r.data.rewardProfile={loot:[{name:'Coin'}]};r.data.foundryAI.abilities=[{section:'actions',index:-1,name:'Ray',toHit:'+5',damage:'1d8 fire',mechanics:{kind:'attack',attackMode:'ranged'},animation:'fire-bolt'}];r.data.foundryAI.loot=[{name:'Coin',quantity:1,description:''},{name:'Letter',quantity:1,description:'A letter'}];const a=aiExtraItems(r,basicAbility,()=> 'icons/svg/item-bag.svg',safeHTML,2),b=aiExtraItems(r,basicAbility,()=>'',safeHTML,20);assert.equal(a.length,2);assert.equal(a[0].flags['shadow-edge-gm'].inventoryKey,b[0].flags['shadow-edge-gm'].inventoryKey);assert.equal(a[1].system.quantity,1);assert.equal(a[0].flags['shadow-edge-gm'].aiAnimation,'fire-bolt')});
test('AI rollback ignores spent uses but respects manual fields',()=>{const raw={_id:'id',name:'Spell',system:{uses:{max:'3',spent:2},activities:{a:{uses:{spent:1,max:'1'}}}},effects:[]};const template=aiItemTemplate(raw);assert.equal(template._id,undefined);assert.equal(template.system.uses.spent,undefined);assert.equal(raw.system.uses.spent,2);assert.deepEqual(aiRestorableFields({slot:2,skill:0},{slot:4,skill:1},{slot:4,skill:2}),{slot:2})});
test('AI import keeps spell editions separate and native limited innate consumption',async()=>{const old=globalThis.game;try{globalThis.game={system:{version:'6.0.6'},packs:new Map()};const r=record();r.data.statBlock.spellcasting={spells:['Shield']};r.data.foundryAI.spells=[{id:'shield-2024',method:'innate',dailyUses:2}];const plan=await actorPlan(r,[{id:'shield-2014',name:'Shield',level:1},{id:'shield-2024',name:'Shield',level:1}]);const spells=plan.items.filter(i=>i.type==='spell');assert.equal(spells.length,1);assert.equal(spells[0].flags['shadow-edge-gm'].spellId,'shield-2024');assert.equal(spells[0].system.method,'innate');assert.equal(spells[0].system.uses.max,'2');const a=Object.values(spells[0].system.activities)[0];assert.equal(a.type,'utility');assert.equal(a.consumption.spellSlot,false);assert.equal(a.consumption.targets[0].type,'itemUses')}finally{globalThis.game=old}});


test('existing magical feature becomes a colored innate spell with two damage types',async()=>{const old=globalThis.game;try{globalThis.game={system:{version:'6.0.6'},packs:new Map()};const r=record();r.data.statBlock.actions=[{name:'Адский огонь',description:'Зелёный огонь',foundry:{kind:'manual'}}];r.data.foundryAI.abilities=[{section:'actions',index:0,name:'Адский огонь',itemType:'spell',spellLevel:0,damage:'3d10 fire plus 2d10 necrotic',animation:'fireball',animationColor:'#55ff44',radius:10,mechanics:{kind:'save',saveAbility:'dex',saveDc:15,saveDamage:'half',range:120,damageType:'fire'}}];const plan=await actorPlan(r,[]),item=plan.items[0],a=Object.values(item.system.activities)[0];assert.equal(item.type,'spell');assert.equal(item.system.method,'innate');assert.equal(a.save.dc.formula,'15');assert.equal(a.target.template.size,10);assert.deepEqual(a.damage.parts.map(p=>p.types[0]),['fire','necrotic']);assert.equal(item.flags['shadow-edge-gm'].aiAnimationColor,'#55ff44');assert.equal(r.data.statBlock.actions[0].foundry.kind,'manual')}finally{globalThis.game=old}});

test('reapplying a profile does not claim later manual fields for undo',()=>{assert.deepEqual(aiReceiptAfter({skill:1,slot:4},{skill:2,slot:4},{skill:2,slot:5}),{skill:1,slot:5})});
