import test from 'node:test';import assert from 'node:assert/strict';import {MODULE} from '../scripts/core.mjs';import {animationProfile,weaponProfile,receiveAnimation} from '../scripts/animations.mjs';import {validEffect,profiles} from '../scripts/native-effects.mjs';
test('weapon names and structured base items select bundled profiles',()=>{for(const [name,key]of [['Длинный лук','bow'],['Light Crossbow','crossbow'],['Боевой топор','axe'],['Longsword','sword'],['Когти','claw'],['Копьё','spear'],['Кинжал','dagger'],['Боевой молот','hammer']])assert.equal(weaponProfile({name}).key,key);assert.equal(weaponProfile({name:'Custom',system:{type:{baseItem:'longbow'}}}).key,'bow');assert.equal(animationProfile({name:'Меч'}, {type:'attack'}),null);assert.equal(animationProfile({flags:{[MODULE]:{spellId:'shield-2024'}}}).mode,'self');assert.equal(Object.keys(profiles).length,85)});
const payload=()=>({id:'one',key:'bow',sceneId:'scene',userId:'player',actorUuid:'Actor.one',source:{x:10,y:10},targets:[{x:20,y:20}],size:100});
test('foundation includes exactly forty spells through sixth level and distinguishes natural attacks from magical projectiles',async()=>{
 const {animationCatalog}=await import('../scripts/animation-catalog.mjs'),foundation=animationCatalog.filter(p=>p.foundation);
 assert.equal(foundation.length,40);assert.equal(new Set(foundation.map(p=>p.key)).size,40);assert(foundation.every(p=>p.spellLevel>=0&&p.spellLevel<=6&&p.aliases.length));
 for(const [name,key]of [['Укус','bite'],['Удар хвостом','tail'],['Щупальце','tentacle'],['Удар рогами','horn'],['Жало','sting'],['Булава','mace'],['Посох','staff'],['Скимитар','sword']])assert.equal(weaponProfile({name}).key,key);
 assert.equal(animationProfile({name:'Custom fire',type:'spell',flags:{[MODULE]:{}}},{type:'attack',attack:{type:{value:'ranged',classification:'spell'}},damage:{parts:[{types:['fire']}]}}).key,'fire-bolt');
 assert.equal(animationProfile({name:'Удержание личности',flags:{[MODULE]:{}}}).key,'hold-person');
});
test('socket input is bounded and checks actor permission',async()=>{assert(validEffect(payload()));for(const bad of [{key:'constructor'},{key:'__proto__'},{key:'https://example.com/script'},{size:Infinity},{targets:Array(21).fill({x:1,y:2})},{template:{x:0,y:0,length:100000,direction:0}},{source:{x:NaN,y:0}}])assert.equal(validEffect({...payload(),...bad}),false);globalThis.canvas={scene:{id:'scene'}};globalThis.game={users:new Map([['player',{isGM:false}]])};globalThis.fromUuid=async()=>({testUserPermission:()=>false});assert.equal(await receiveAnimation(payload()),false)});


test('AI and renderer share a complete catalog with packaged transparent art',async()=>{const {readFile}=await import('node:fs/promises'),{animationCatalog}=await import('../scripts/animation-catalog.mjs');const server=JSON.parse(await readFile(new URL('../../../apps/server/internal/httpapi/foundry_animation_catalog.json',import.meta.url),'utf8'));assert.deepEqual(animationCatalog,server);assert.deepEqual(animationCatalog.map(p=>p.key).sort(),Object.keys(profiles).sort());for(const name of ['weapons','vines','blood-slash','magic']){const data=await readFile(new URL('../assets/'+name+'.png',import.meta.url));assert.equal(data.toString('hex',0,8),'89504e470d0a1a0a');assert.equal(data[25],6)}assert.equal(validEffect({...payload(),targets:[{x:20,y:20,hit:'yes'}]}),false)});
