import test from 'node:test';import assert from 'node:assert/strict';
import {attackHits,areaTargets,activityHasDamage} from '../scripts/combat.mjs';
test('save-only controls do not expose a damage operation, weapon base damage still does',()=>{assert.equal(activityHasDamage({damage:{parts:[]}}),false);assert.equal(activityHasDamage({damage:{parts:[{}]}}),true);assert.equal(activityHasDamage({damage:{parts:[],includeBase:true},item:{system:{damage:{base:{number:1}}}}}),true)});
import {effectDuration} from '../scripts/native-effects.mjs';
import {shieldEffectActive} from '../scripts/sustained-effects.mjs';
test('shield visuals require an active actual shield effect, not equipped armor',()=>{const effect={name:'Barrier',flags:{'shadow-edge-gm':{visual:'shield'}},duration:{expired:false}};assert(shieldEffectActive(effect));for(const update of [{disabled:true},{isSuppressed:true},{duration:{expired:true}},{active:false}])assert.equal(shieldEffectActive({...effect,...update}),false);assert.equal(shieldEffectActive({name:'Shield',system:{changes:[{key:'system.attributes.ac.bonus',value:2}]}}),false)});
test('all effects last 2-3 seconds and areas finish before combat resumes',()=>{assert.equal(effectDuration({key:'fireball'}),2800);assert.equal(effectDuration({key:'lightning-bolt',template:{}}),2800);assert.equal(effectDuration({key:'sword'}),2600)});
test('natural one misses, natural twenty hits, and other attacks compare with AC',()=>{const r=(n,total)=>({total,dice:[{faces:20,results:[{result:n,active:true}]}]});assert.equal(attackHits(r(1,100),10),false);assert.equal(attackHits(r(20,20),100),true);assert.equal(attackHits(r(11,16),16),true);assert.equal(attackHits(r(10,15),16),false)});
test('Fireball selects intersecting token footprints, excludes outside and actorless tokens',()=>{const token=(id,x,y,w=1,actor={})=>({uuid:id,x,y,width:w,height:1,actor});const scene={grid:{size:100,distance:5},tokens:[token('center',0,0),token('edge',200,0),token('outside',400,400),token('large',-250,0,2),token('no-actor',0,0,1,null)]};assert.deepEqual(areaTargets(scene,{t:'circle',x:50,y:50,distance:10}),['center','edge','large'])});

import {npcSaveBonuses,plainDamageTraits} from '../scripts/adapter.mjs';
test('NPC printed save totals preserve extra bonuses without adding ability modifier twice',()=>{assert.deepEqual(npcSaveBonuses('DEX +5, МДР +2',{dex:16,wis:10}),{dex:{save:{roll:{bonus:'2'}}},wis:{save:{roll:{bonus:'2'}}}});assert.deepEqual(plainDamageTraits('fire, холод; bludgeoning from nonmagical attacks; cold from spells'),['fire','cold'])});

test('native dnd5e 6 Region circles use pixel radius for area selection',()=>{const scene={grid:{size:100,distance:5},tokens:[{uuid:'inside',actor:{},x:100,y:100,width:1,height:1},{uuid:'outside',actor:{},x:600,y:600,width:1,height:1}]};assert.deepEqual(areaTargets(scene,{shapes:[{type:'circle',x:200,y:200,radius:150}]}),['inside'])});
