import test from 'node:test';import assert from 'node:assert/strict';
import {attackHits,areaTargets} from '../scripts/combat.mjs';import {dieGeometry,rollDice} from '../scripts/dice3d.mjs';
test('3D meshes have real D&D polyhedron faces and only display evaluated dice',()=>{for(const n of [4,6,8,10,12,20])assert.equal(dieGeometry(n).faces.length,n);assert.equal(dieGeometry(7),null);assert.deepEqual(rollDice([{dice:[{faces:20,results:[{result:17,active:true},{result:3,discarded:true}]},{faces:6,results:[{result:4}]}]}]),[{sides:20,result:17,discarded:false},{sides:20,result:3,discarded:true},{sides:6,result:4,discarded:false}])});
test('natural one misses, natural twenty hits, and other attacks compare with AC',()=>{const r=(n,total)=>({total,dice:[{faces:20,results:[{result:n,active:true}]}]});assert.equal(attackHits(r(1,100),10),false);assert.equal(attackHits(r(20,20),100),true);assert.equal(attackHits(r(11,16),16),true);assert.equal(attackHits(r(10,15),16),false)});
test('Fireball selects intersecting token footprints, excludes outside and actorless tokens',()=>{const token=(id,x,y,w=1,actor={})=>({uuid:id,x,y,width:w,height:1,actor});const scene={grid:{size:100,distance:5},tokens:[token('center',0,0),token('edge',200,0),token('outside',400,400),token('large',-250,0,2),token('no-actor',0,0,1,null)]};assert.deepEqual(areaTargets(scene,{t:'circle',x:50,y:50,distance:10}),['center','edge','large'])});

import {npcSaveBonuses,plainDamageTraits} from '../scripts/adapter.mjs';
test('NPC printed save totals preserve extra bonuses without adding ability modifier twice',()=>{assert.deepEqual(npcSaveBonuses('DEX +5, МДР +2',{dex:16,wis:10}),{dex:{save:{roll:{bonus:'2'}}},wis:{save:{roll:{bonus:'2'}}}});assert.deepEqual(plainDamageTraits('fire, холод; bludgeoning from nonmagical attacks; cold from spells'),['fire','cold'])});

test('native dnd5e 6 Region circles use pixel radius for area selection',()=>{const scene={grid:{size:100,distance:5},tokens:[{uuid:'inside',actor:{},x:100,y:100,width:1,height:1},{uuid:'outside',actor:{},x:600,y:600,width:1,height:1}]};assert.deepEqual(areaTargets(scene,{shapes:[{type:'circle',x:200,y:200,radius:150}]}),['inside'])});
