import {MODULE} from "./core.mjs";
import {actorPlan,basicAbility,safeHTML,compendiumItem} from "./adapter.mjs";
import {areaProfiles} from './area-profiles.mjs';
async function demoAreas(caster){
 const ru={grease:'Жир','wall-of-fire':'Стена огня','spike-growth':'Терновая поросль',entangle:'Опутывание',darkness:'Тьма','fog-cloud':'Туманное облако',web:'Паутина',moonbeam:'Лунный луч',thunderwave:'Волна грома',shatter:'Дребезги','ice-storm':'Град'};
 for(const [key,p]of Object.entries(areaProfiles)){
  if(caster.items.some(i=>i.flags?.[MODULE]?.spellId===key+'-2024'||i.flags?.[MODULE]?.areaProfile===key))continue;
  const consumable=['oil','acid','alchemists-fire'].includes(key),item=await compendiumItem(key==='oil'?'Oil':p.name,'2024',consumable?'consumable':'spell');if(!item)continue;
  item.name=consumable?(key==='oil'?'Скользкое масло':key==='acid'?'Кислота · Acid':'Алхимический огонь'):ru[key]+' · '+p.name;
  item.flags??={};item.flags[MODULE]={coverage:'partial',...(consumable?{areaProfile:key}:{spellId:key+'-2024'}),demoArea:true};item.flags.autoanimations={isEnabled:false};
  if(!consumable){item.system.method='innate';item.system.prepared=1}
  for(const a of Object.values(item.system.activities??{})){a.consumption={spellSlot:false,targets:[]}}
  if(key==='oil'){
   const a=Object.values(item.system.activities)[0];a.type='utility';delete a.save;delete a.damage;a.duration={override:true,units:'minute',value:'5',concentration:false};a.target={override:true,prompt:true,template:{type:'square',size:'10',units:'ft'},affects:{type:'space'}};a.range={override:true,value:'20',units:'ft'};item.system.activities={[a._id]:a};item.system.description.value=safeHTML('Скользкое масло — правило стола для проверки эффектов: квадрат 10 футов становится труднопроходимым на 5 минут. Падение и поджигание решает мастер. В демонстрации бутылка не расходуется.');
  }
  await caster.createEmbeddedDocuments('Item',[item]);
 }
}
async function demoWeapons(caster){
  const names=['Длинный лук','Арбалет','Длинный меч','Боевой топор','Боевой молот','Кинжал','Копьё','Когти'];
  const missing=names.filter(name=>!caster.items.some(i=>i.flags?.[MODULE]?.demoWeapon===name));
  await caster.createEmbeddedDocuments('Item',missing.map(name=>{const ranged=/лук|Арбалет/.test(name),i=basicAbility({name,toHit:'+7',damage:'1d8+4 '+(/лук|Арбалет|Кинжал|Копь/.test(name)?'piercing':/молот/.test(name)?'bludgeoning':'slashing'),description:'Проверка встроенной анимации оружия.',foundry:{kind:'attack',attackMode:ranged?'ranged':'melee'}});i.flags[MODULE].demoWeapon=name;return i}));
  if(!caster.items.some(i=>i.flags?.[MODULE]?.demoMechanics==='weapon-stats')){const weapon=await compendiumItem('Longsword','2024','weapon');if(weapon){weapon.name='Меч · характеристики';weapon.system.proficient=1;weapon.flags??={};weapon.flags[MODULE]={demoMechanics:'weapon-stats',coverage:'partial'};weapon.flags.autoanimations={isEnabled:false};await caster.createEmbeddedDocuments('Item',[weapon])}}
}
async function updateAreaGuide(scene,caster){
  if(caster?.img==='icons/svg/mage.svg')await caster.update({img:'icons/svg/cowled.svg','prototypeToken.texture.src':'icons/svg/cowled.svg'});
  const tokens=scene.tokens.filter(t=>t.texture.src==='icons/svg/mage.svg').map(t=>({_id:t.id,'texture.src':'icons/svg/cowled.svg'}));if(tokens.length)await scene.updateEmbeddedDocuments('Token',tokens);
  for(const journal of game.journal.filter(j=>j.flags?.[MODULE]?.demo==='animations'))for(const page of journal.pages){const content=page.text?.content;if(content&&!content.includes('Длительные области:'))await page.update({'text.content':content+safeHTML('Длительные области: Grease, скользкое масло, Wall of Fire, Spike Growth, Entangle, Darkness, Fog Cloud, Web, Moonbeam. Используйте способность и разместите область кликом. Анимация остаётся до игрового срока или окончания концентрации; кнопка «Убрать область» есть в карточке чата. Область можно перемещать инструментом регионов. Тьма, туман и огненная стена ограничивают обычную видимость. Thunderwave, Shatter, Ice Storm, кислота и алхимический огонь показывают короткие эффекты. Начальные спасброски, состояния и повторяющийся урон длительных областей выполняются средствами dnd5e под контролем мастера. Скользкое масло — правило стола; падение и поджигание не автоматизированы. Все демонстрационные предметы и заклинания бесплатны.')})}
}
export async function createDemoScene(){
  if(!game.user.isGM)throw Error("Тестовую сцену создаёт мастер.");
  if(Number.parseInt(game.system.version,10)<6)throw Error("Эта тестовая сцена рассчитана на dnd5e 6. Обмен кампанией доступен и в системе 5.");
  const prior=game.scenes.find(s=>s.flags?.[MODULE]?.demo==="animations");if(prior){const caster=game.actors.get(prior.tokens.find(t=>t.name.startsWith('Тестовый маг'))?.actorId);if(caster){await demoWeapons(caster);await demoAreas(caster)}for(const journal of game.journal.filter(j=>j.flags?.[MODULE]?.demo==='animations'))for(const page of journal.pages){const old=page.text?.content;if(old){const content=old.replace('Броски, урон и лечение выполняются обычными средствами dnd5e; авторасчёт Midi-QOL отдельно.','Атаки и Fireball используют карточку боя: спасброски владельцев целей, кнопка урона после попадания, автоматическое применение HP. Меч · характеристики берёт бонусы из листа; остальные тестовые атаки содержат фиксированные значения статблока. Лечение показывает поток до завершения кубов; HP применяются обычными средствами dnd5e. Shield автоматически создаёт эффект +5 КД и постоянный пузырь до его истечения. Сложные эффекты требуют проверки мастером.').replace('Лечение и сложные эффекты остаются средствами dnd5e.','Лечение показывает поток до завершения кубов; HP применяются обычными средствами dnd5e. Shield автоматически создаёт эффект +5 КД и постоянный пузырь до его истечения. Сложные эффекты требуют проверки мастером.').replace('Включите Shadow Edge GM, Sequencer и JB2A Free.','Включите Shadow Edge GM — все эффекты уже встроены.').replace('Простая тестовая атака даёт эффект попадания.','Для оружия используйте Длинный лук, Арбалет, Длинный меч, Боевой топор, Боевой молот, Кинжал, Копьё или Когти.');if(content!==old)await page.update({'text.content':content})}}await updateAreaGuide(prior,caster);await prior.view();return prior}
  const demo={demo:"animations"},actors=[];let scene,journal;
  try{
    const names=[['fire-bolt','Fire Bolt'],['ray-of-frost','Ray of Frost'],['magic-missile','Magic Missile'],['cure-wounds','Cure Wounds'],['healing-word','Healing Word'],['fireball','Fireball'],['burning-hands','Burning Hands'],['lightning-bolt','Lightning Bolt'],['bless','Bless'],['shield','Shield']];
    const catalog=names.map(([id,name])=>({id:id+'-2024',name,description:'',level:0}));
    const plan=await actorPlan({key:'demo:caster',kind:'character',data:{draft:{name:'Тестовый маг · Shadow Edge',edition:'2024',classId:'wizard',targetLevel:5,levels:[{spellIds:catalog.map(s=>s.id)}]},stats:{abilities:{str:10,dex:14,con:14,int:18,wis:12,cha:10},maxHp:40,armorClass:15,speed:30,spellSlots:[4,3,2]}}},catalog);
    plan.projection.flags[MODULE]=demo;plan.projection.img='icons/svg/cowled.svg';plan.projection.prototypeToken.texture={src:plan.projection.img};
    const caster=await Actor.create(plan.projection);actors.push(caster);await caster.createEmbeddedDocuments('Item',plan.items.map(i=>{if(i.type==='spell'){i.system.prepared=1;i.system.method='innate';i.system.uses={max:''};for(const a of Object.values(i.system.activities??{})){a.consumption??={};a.consumption.spellSlot=false;a.consumption.targets=[]}}return i}));
    const melee=basicAbility({name:'Тестовая атака',toHit:'+7',damage:'1d8+4 slashing',description:'Простой удар с анимацией попадания.',foundry:{kind:'attack',attackMode:'melee'}});await caster.createEmbeddedDocuments('Item',[melee]);
    await demoWeapons(caster);await demoAreas(caster);
    await caster.update({'system.attributes.hp.value':caster.system.attributes.hp.max});
    const target=await Actor.create({name:'Манекен · Shadow Edge',type:'npc',img:'icons/svg/target.svg',system:{attributes:{hp:{max:200,value:200},ac:{calcs:['flat'],flat:12}}},flags:{[MODULE]:demo}});actors.push(target);
    const ally=await Actor.create({name:'Союзник · Shadow Edge',type:'npc',img:'icons/svg/angel.svg',system:{attributes:{hp:{max:50,value:15},ac:{calcs:['flat'],flat:12}}},flags:{[MODULE]:demo}});actors.push(ally);
    scene=await Scene.create({name:'Shadow Edge · Проверка анимаций',width:1800,height:1200,padding:0.1,backgroundColor:'#1e2430',grid:{type:1,size:100,distance:5,units:'ft',color:'#697385',alpha:0.35},active:false,flags:{[MODULE]:demo},tokens:[{name:caster.name,actorId:caster.id,actorLink:true,x:400,y:500,texture:{src:caster.img}},{name:target.name,actorId:target.id,actorLink:true,x:1100,y:500,texture:{src:target.img},disposition:-1},{name:ally.name,actorId:ally.id,actorLink:true,x:700,y:800,texture:{src:ally.img},disposition:1}],drawings:[{x:200,y:200,shape:{type:'r',width:1400,height:700},fillType:1,fillColor:'#343d50',fillAlpha:0.3,strokeColor:'#7788aa',strokeAlpha:1},{x:220,y:160,shape:{type:'r',width:1350,height:100},text:'АРЕНА ПРОВЕРКИ АНИМАЦИЙ',fontSize:36,textColor:'#e5eaf5',fillType:0,strokeAlpha:0},{x:260,y:1000,shape:{type:'r',width:1280,height:100},text:'Выдели мага → отметь цель двойным правым кликом → открой лист мага и используй способность.',fontSize:20,textColor:'#ccd5e5',fillType:0,strokeAlpha:0}]});
    journal=await JournalEntry.create({name:'Shadow Edge · Как проверить анимации',ownership:{default:0},flags:{[MODULE]:demo},pages:[{name:'Проверка',type:'text',text:{format:1,content:safeHTML('1. Включите Shadow Edge GM — все эффекты уже встроены.\n2. На сцене выделите токен мага. Двойной правый клик по манекену отмечает его целью (или инструмент выбора цели).\n3. Двойным левым кликом откройте лист мага. Используйте Fire Bolt, Ray of Frost или Magic Missile.\n4. Для Cure Wounds и Healing Word отметьте союзника. Shield отображается на самом маге.\n5. Fireball, Burning Hands и Lightning Bolt создают шаблон области: разместите его на сцене.\n6. Bless отображается на выбранных целях. Для оружия используйте Длинный лук, Арбалет, Длинный меч, Боевой топор, Боевой молот, Кинжал, Копьё или Когти.\nЗаклинания здесь специально не расходуют ячейки: это демонстрация анимаций, а не готовый игровой персонаж. Атаки и Fireball используют карточку боя: спасброски владельцев целей, кнопка урона после попадания, автоматическое применение HP. Меч · характеристики берёт бонусы из листа; остальные тестовые атаки содержат фиксированные значения статблока. Лечение показывает поток до завершения кубов; HP применяются обычными средствами dnd5e. Shield автоматически создаёт эффект +5 КД и постоянный пузырь до его истечения. Сложные эффекты требуют проверки мастером. Тестовые документы исключены из экспорта на сайт.')}}]});
    await updateAreaGuide(scene,caster);await scene.activate();for(let i=0;i<100&&(!canvas.ready||canvas.scene?.id!==scene.id);i++)await new Promise(r=>setTimeout(r,100));ui.notifications.info('Тестовая сцена анимаций создана. Инструкция находится в журнале.');return scene;
  }catch(e){if(journal)await journal.delete();if(scene)await scene.delete();for(const a of actors)await a.delete();throw e}
}
