import {MODULE} from "./core.mjs";
import {actorPlan,basicAbility,safeHTML} from "./adapter.mjs";
export async function createDemoScene(){
  if(!game.user.isGM)throw Error("Тестовую сцену создаёт мастер.");
  if(Number.parseInt(game.system.version,10)<6)throw Error("Эта тестовая сцена рассчитана на dnd5e 6. Обмен кампанией доступен и в системе 5.");
  const prior=game.scenes.find(s=>s.flags?.[MODULE]?.demo==="animations");if(prior){await prior.view();return prior}
  const demo={demo:"animations"},actors=[];let scene,journal;
  try{
    const names=[['fire-bolt','Fire Bolt'],['ray-of-frost','Ray of Frost'],['magic-missile','Magic Missile'],['cure-wounds','Cure Wounds'],['healing-word','Healing Word'],['fireball','Fireball'],['burning-hands','Burning Hands'],['lightning-bolt','Lightning Bolt'],['bless','Bless'],['shield','Shield']];
    const catalog=names.map(([id,name])=>({id:id+'-2024',name,description:'',level:0}));
    const plan=await actorPlan({key:'demo:caster',kind:'character',data:{draft:{name:'Тестовый маг · Shadow Edge',edition:'2024',classId:'wizard',targetLevel:5,levels:[{spellIds:catalog.map(s=>s.id)}]},stats:{abilities:{str:10,dex:14,con:14,int:18,wis:12,cha:10},maxHp:40,armorClass:15,speed:30,spellSlots:[4,3,2]}}},catalog);
    plan.projection.flags[MODULE]=demo;plan.projection.img='icons/svg/mage.svg';plan.projection.prototypeToken.texture={src:plan.projection.img};
    const caster=await Actor.create(plan.projection);actors.push(caster);await caster.createEmbeddedDocuments('Item',plan.items.map(i=>{if(i.type==='spell'){i.system.prepared=1;i.system.method='innate';i.system.uses={max:''};for(const a of Object.values(i.system.activities??{})){a.consumption??={};a.consumption.spellSlot=false;a.consumption.targets=[]}}return i}));
    const melee=basicAbility({name:'Тестовая атака',toHit:'+7',damage:'1d8+4 slashing',description:'Простой удар с анимацией попадания.',foundry:{kind:'attack',attackMode:'melee'}});await caster.createEmbeddedDocuments('Item',[melee]);
    await caster.update({'system.attributes.hp.value':caster.system.attributes.hp.max});
    const target=await Actor.create({name:'Манекен · Shadow Edge',type:'npc',img:'icons/svg/target.svg',system:{attributes:{hp:{max:200,value:200},ac:{calcs:['flat'],flat:12}}},flags:{[MODULE]:demo}});actors.push(target);
    const ally=await Actor.create({name:'Союзник · Shadow Edge',type:'npc',img:'icons/svg/angel.svg',system:{attributes:{hp:{max:50,value:15},ac:{calcs:['flat'],flat:12}}},flags:{[MODULE]:demo}});actors.push(ally);
    scene=await Scene.create({name:'Shadow Edge · Проверка анимаций',width:1800,height:1200,padding:0.1,backgroundColor:'#1e2430',grid:{type:1,size:100,distance:5,units:'ft',color:'#697385',alpha:0.35},active:false,flags:{[MODULE]:demo},tokens:[{name:caster.name,actorId:caster.id,actorLink:true,x:400,y:500,texture:{src:caster.img}},{name:target.name,actorId:target.id,actorLink:true,x:1100,y:500,texture:{src:target.img},disposition:-1},{name:ally.name,actorId:ally.id,actorLink:true,x:700,y:800,texture:{src:ally.img},disposition:1}],drawings:[{x:200,y:200,shape:{type:'r',width:1400,height:700},fillType:1,fillColor:'#343d50',fillAlpha:0.3,strokeColor:'#7788aa',strokeAlpha:1},{x:220,y:160,shape:{type:'r',width:1350,height:100},text:'АРЕНА ПРОВЕРКИ АНИМАЦИЙ',fontSize:36,textColor:'#e5eaf5',fillType:0,strokeAlpha:0},{x:260,y:1000,shape:{type:'r',width:1280,height:100},text:'Выдели мага → отметь цель двойным правым кликом → открой лист мага и используй способность.',fontSize:20,textColor:'#ccd5e5',fillType:0,strokeAlpha:0}]});
    journal=await JournalEntry.create({name:'Shadow Edge · Как проверить анимации',ownership:{default:0},flags:{[MODULE]:demo},pages:[{name:'Проверка',type:'text',text:{format:1,content:safeHTML('1. Включите Shadow Edge GM, Sequencer и JB2A Free.\n2. На сцене выделите токен мага. Двойной правый клик по манекену отмечает его целью (или инструмент выбора цели).\n3. Двойным левым кликом откройте лист мага. Используйте Fire Bolt, Ray of Frost или Magic Missile.\n4. Для Cure Wounds и Healing Word отметьте союзника. Shield отображается на самом маге.\n5. Fireball, Burning Hands и Lightning Bolt создают шаблон области: разместите его на сцене.\n6. Bless отображается на выбранных целях. Простая тестовая атака даёт эффект попадания.\nЗаклинания здесь специально не расходуют ячейки: это демонстрация анимаций, а не готовый игровой персонаж. Броски, урон и лечение выполняются обычными средствами dnd5e; авторасчёт Midi-QOL отдельно. Тестовые документы исключены из экспорта на сайт.')}}]});
    await scene.activate();for(let i=0;i<100&&(!canvas.ready||canvas.scene?.id!==scene.id);i++)await new Promise(r=>setTimeout(r,100));ui.notifications.info('Тестовая сцена анимаций создана. Инструкция находится в журнале.');return scene;
  }catch(e){if(journal)await journal.delete();if(scene)await scene.delete();for(const a of actors)await a.delete();throw e}
}
