package httpapi

import "strings"

type AIOptions struct {
	Provider string
	Model    string
	BaseURL  string
	APIToken string
}

type entityGenerator interface {
	Generate(campaign campaignData, input generateEntityDraftInput) (generateEntityDraftResult, error)
	GenerateWorldEvent(campaign campaignData, input generateWorldEventInput) (generateWorldEventResult, error)
}

type encounterGenerator interface {
	GenerateEncounter(campaign campaignData, input generateCombatInput) (generateEncounterDraftResult, error)
}

type generateEncounterDraftResult struct {
	Provider string
	Notes    []string
	Items    []encounterDraftItem
}

type encounterDraftItem struct {
	Quantity int
	Entity   createEntityInput
}

type generatorConfig struct {
	requestedProvider string
	activeProvider    string
	model             string
	baseURL           string
	apiToken          string
	apiKeyConfigured  bool
}

type scaffoldGenerator struct {
	config generatorConfig
}

func newEntityGenerator(options AIOptions) entityGenerator {
	requestedProvider := normalizeProvider(options.Provider)
	baseURL := strings.TrimSpace(options.BaseURL)
	apiToken := strings.TrimSpace(options.APIToken)
	if requestedProvider == "" {
		if apiToken != "" || baseURL != "" {
			requestedProvider = "openai"
		} else {
			requestedProvider = "scaffold"
		}
	}

	config := generatorConfig{
		requestedProvider: requestedProvider,
		model:             strings.TrimSpace(options.Model),
		baseURL:           baseURL,
		apiToken:          apiToken,
		apiKeyConfigured:  apiToken != "",
	}

	switch requestedProvider {
	case "openai", "chatgpt":
		config.activeProvider = "openai"
		if config.model == "" {
			config.model = "gpt-5.4-mini"
		}
		return newOpenAIGenerator(config)
	default:
		config.activeProvider = "local-scaffold"
		if config.model == "" {
			config.model = "shadow-edge-synthetic-v1"
		}
		return scaffoldGenerator{config: config}
	}
}

func normalizeProvider(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func (generator scaffoldGenerator) Generate(_ campaignData, input generateEntityDraftInput) (generateEntityDraftResult, error) {
	kind := strings.TrimSpace(strings.ToLower(input.Kind))
	prompt := strings.TrimSpace(input.Prompt)

	result := generateEntityDraftResult{
		Provider: generator.config.activeProvider,
		Notes:    generator.buildNotes(),
	}

	switch kind {
	case "location":
		result.Entity = buildLocationDraft(prompt)
	case "npc":
		result.Entity = buildNpcDraft(prompt)
	case "monster":
		result.Entity = buildMonsterDraft(prompt)
	case "quest":
		result.Entity = buildQuestDraft(prompt)
	case "lore":
		result.Entity = buildLoreDraft(prompt)
	default:
		result.Entity = createEntityInput{
			Kind:    kind,
			Title:   draftTitle(prompt, "New Entity"),
			Summary: "Scaffold generation does not yet know how to structure this entity kind.",
			Content: prompt,
			Tags:    []string{"ai-draft"},
		}
	}

	if shouldGenerateQuestIssuerDraft(input, result.Entity) {
		result.LinkedDrafts = []linkedEntityDraft{
			{
				Role:   "issuer",
				Note:   "Новый квестодатель будет создан вместе с квестом, если ты не выберешь существующего НПС.",
				Entity: buildQuestIssuerDraft(prompt, result.Entity),
			},
		}
		result.Notes = append(result.Notes, "Так как квестодатель не выбран, AI подготовил отдельный draft НПС для этого квеста.")
	}

	return result, nil
}

func (generator scaffoldGenerator) GenerateWorldEvent(campaign campaignData, input generateWorldEventInput) (generateWorldEventResult, error) {
	return generateWorldEventResult{
		Provider: generator.config.activeProvider,
		Notes:    append(generator.buildNotes(), "Короткое событие собрано локальным scaffold-провайдером."),
		Event:    normalizeWorldEventDraftInput(campaign, input, buildWorldEventDraft(campaign, input)),
	}, nil
}

func (generator scaffoldGenerator) GenerateEncounter(_ campaignData, input generateCombatInput) (generateEncounterDraftResult, error) {
	notes := append([]string{}, generator.buildNotes()...)
	notes = append(notes, "Encounter roster generated by the local scaffold provider.")

	totalCount := normalizeEncounterMonsterCount(input.MonsterCount)
	prompt := strings.TrimSpace(input.Prompt)
	banditPrompt := containsAny(prompt, "bandit", "разбой", "brigand", "raider")
	leaderPrompt := containsAny(prompt, "leader", "глав", "captain", "chief", "boss")

	if banditPrompt {
		items := make([]encounterDraftItem, 0, 2)
		if leaderPrompt {
			items = append(items, encounterDraftItem{
				Quantity: 1,
				Entity:   buildOfficialBanditCaptainDraft(),
			})
		}

		minionCount := totalCount
		if leaderPrompt && minionCount > 1 {
			minionCount--
		}
		if minionCount > 0 {
			items = append(items, encounterDraftItem{
				Quantity: minionCount,
				Entity:   buildOfficialBanditDraft(),
			})
		}

		return generateEncounterDraftResult{
			Provider: generator.config.activeProvider,
			Notes:    notes,
			Items:    items,
		}, nil
	}

	if leaderPrompt && totalCount > 1 {
		leader := buildMonsterDraft(prompt)
		leader.Title = draftTitle(prompt, "Главарь отряда")
		leader.Importance = "Boss"
		minion := buildMonsterDraft(prompt)
		minion.Title = fallbackEncounterFollowerTitle(minion.Title)
		minion.Importance = "Standard"

		return generateEncounterDraftResult{
			Provider: generator.config.activeProvider,
			Notes:    notes,
			Items: []encounterDraftItem{
				{Quantity: 1, Entity: leader},
				{Quantity: totalCount - 1, Entity: minion},
			},
		}, nil
	}

	switch {
	case containsAny(prompt, "bandit", "разбой", "brigand", "raider"):
		leaderRequested := containsAny(prompt, "leader", "глав", "captain", "chief", "boss")
		items := make([]encounterDraftItem, 0, 2)
		if leaderRequested {
			items = append(items, encounterDraftItem{
				Quantity: 1,
				Entity:   buildOfficialBanditCaptainDraft(),
			})
		}

		minionCount := totalCount
		if leaderRequested && minionCount > 1 {
			minionCount--
		}
		if minionCount > 0 {
			items = append(items, encounterDraftItem{
				Quantity: minionCount,
				Entity:   buildOfficialBanditDraft(),
			})
		}

		return generateEncounterDraftResult{
			Provider: generator.config.activeProvider,
			Notes:    notes,
			Items:    items,
		}, nil
	case containsAny(prompt, "leader", "глав", "captain", "chief", "boss") && totalCount > 1:
		leader := buildMonsterDraft(prompt)
		leader.Title = draftTitle(prompt, "Главарь отряда")
		leader.Importance = "Boss"
		minion := buildMonsterDraft(prompt)
		minion.Title = fallbackEncounterFollowerTitle(minion.Title)
		minion.Importance = "Standard"

		return generateEncounterDraftResult{
			Provider: generator.config.activeProvider,
			Notes:    notes,
			Items: []encounterDraftItem{
				{Quantity: 1, Entity: leader},
				{Quantity: totalCount - 1, Entity: minion},
			},
		}, nil
	default:
		return generateEncounterDraftResult{
			Provider: generator.config.activeProvider,
			Notes:    notes,
			Items: []encounterDraftItem{
				{
					Quantity: totalCount,
					Entity:   buildMonsterDraft(prompt),
				},
			},
		}, nil
	}
}

func (generator scaffoldGenerator) buildNotes() []string {
	notes := []string{
		"Draft generated by the local scaffold provider.",
		"Review links, numbers and world tone before using it in play.",
	}

	if generator.config.requestedProvider != "" && generator.config.requestedProvider != "scaffold" {
		notes = append(notes, "Requested provider "+generator.config.requestedProvider+" is not available, so the server fell back to local-scaffold.")
	}

	if generator.config.model != "" {
		notes = append(notes, "Configured model: "+generator.config.model+".")
	}

	if generator.config.baseURL != "" {
		notes = append(notes, "A provider base URL is already configured on the server.")
	}

	if generator.config.apiKeyConfigured {
		notes = append(notes, "An API key is already available on the server.")
	}

	return notes
}

func buildLocationDraft(prompt string) createEntityInput {
	category := "City"
	danger := "Tense"
	title := draftTitle(prompt, "New City")

	switch {
	case containsAny(prompt, "ruin", "ancient", "vault", "catacomb"):
		category = "Dungeon"
		danger = "Deadly"
	case containsAny(prompt, "region", "valley", "forest", "coast", "frontier"):
		category = "Region"
		danger = "Dangerous"
	case containsAny(prompt, "bridge", "temple", "tower", "gate", "shrine"):
		category = "POI"
	}

	return createEntityInput{
		Kind:     "location",
		Title:    title,
		Subtitle: category + " - AI draft",
		Summary:  "Location generated from a text prompt and ready for GM polish.",
		Content:  title + " is sketched as a usable scene hub with hooks, rumors and pressure points for the table.",
		Tags:     []string{"ai-draft", strings.ToLower(category)},
		Category: category,
		Region:   "New Region",
		Danger:   danger,
		QuickFacts: []quickFact{
			{Label: "Danger", Value: danger, Tone: "warning"},
			{Label: "Category", Value: category},
			{Label: "Source", Value: "AI draft"},
		},
	}
}

func buildNpcDraft(prompt string) createEntityInput {
	title := draftTitle(prompt, "New NPC")
	role := "AI generated role"
	status := "Unknown"
	importance := "Major"
	statBlock := defaultHumanoidStatBlock(title)
	tags := []string{"ai-draft", "npc"}

	if containsAny(prompt, "wolf", "волк") {
		title = draftTitle(prompt, "Northern Wolf")
		role = "Predator scout"
		status = "Threat"
		statBlock = defaultWolfStatBlock()
		tags = []string{"ai-draft", "wolf", "beast"}
	}

	return createEntityInput{
		Kind:          "npc",
		Title:         title,
		Subtitle:      "AI draft - ready to refine",
		Summary:       "NPC or creature drafted from the GM prompt.",
		Content:       title + " comes with a baseline role, stat block and scene usage so you can refine it quickly.",
		PlayerContent: title + " can explain the visible problem, make a believable request and share only the information a player-facing scene should reveal.",
		Tags:          tags,
		Role:          role,
		Status:        status,
		Importance:    importance,
		StatBlock:     statBlock,
		RewardProfile: fallbackRewardProfile(prompt, title, "npc"),
		QuickFacts: []quickFact{
			{Label: "Status", Value: status, Tone: "accent"},
			{Label: "Role", Value: role},
			{Label: "AC / HP", Value: statBlock.ArmorClass + " / " + statBlock.HitPoints},
		},
	}
}

func buildMonsterDraft(prompt string) createEntityInput {
	if official, ok := officialMonsterDraft(prompt, ""); ok {
		return official
	}

	title := draftTitle(prompt, "New Monster")
	role := "Encounter threat"
	status := "Hostile"
	importance := "Standard"
	statBlock := defaultMonsterStatBlock(title)
	tags := []string{"ai-draft", "monster"}

	switch {
	case containsAny(prompt, "wolf", "волк"):
		title = draftTitle(prompt, "Dire Wolf")
		role = "Pack hunter"
		statBlock = defaultWolfStatBlock()
		tags = []string{"ai-draft", "monster", "wolf", "beast"}
	case containsAny(prompt, "spider", "паук"):
		title = draftTitle(prompt, "Giant Spider")
		role = "Ambush predator"
		statBlock = defaultSpiderStatBlock()
		tags = []string{"ai-draft", "monster", "spider", "beast"}
	case containsAny(prompt, "boss", "элит", "deadly", "смерто"):
		importance = "Boss"
	}

	return createEntityInput{
		Kind:          "monster",
		Title:         title,
		Subtitle:      "AI draft - encounter ready",
		Summary:       "Monster drafted for combat encounters and quick GM prep.",
		Content:       title + " comes with an encounter-ready stat block, tactics and scene usage.",
		Tags:          tags,
		Role:          role,
		Status:        status,
		Importance:    importance,
		StatBlock:     statBlock,
		RewardProfile: defaultMonsterRewardProfile(prompt, title),
		QuickFacts: []quickFact{
			{Label: "Threat", Value: status, Tone: "danger"},
			{Label: "Role", Value: role},
			{Label: "CR / XP", Value: firstNonEmpty(statBlock.Challenge, "—")},
		},
	}
}

func buildBanditMonsterDraft(isLeader bool) createEntityInput {
	if isLeader {
		statBlock := &npcStatBlock{
			Size:             "Medium",
			CreatureType:     "humanoid",
			Alignment:        "any non-good alignment",
			ArmorClass:       "15 (studded leather, shield)",
			HitPoints:        "27 (5d8 + 5)",
			Speed:            "30 ft.",
			ProficiencyBonus: "+2",
			Challenge:        "1/4 (50 XP)",
			Senses:           "passive Perception 10",
			Languages:        "Common plus one other",
			AbilityScores:    abilityScores{STR: 11, DEX: 14, CON: 12, INT: 10, WIS: 10, CHA: 12},
			Traits: []statBlockEntry{
				{Name: "Tactical Orders", Description: "Allied bandits within 30 feet that can hear the leader add +1 to damage rolls with weapon attacks while the leader is not incapacitated."},
			},
			Actions: []statBlockEntry{
				{Name: "Scimitar", ToHit: "+4 to hit", Damage: "1d6 + 2 slashing damage", Description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target."},
				{Name: "Light Crossbow", ToHit: "+4 to hit", Damage: "1d8 + 2 piercing damage", Description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target."},
			},
		}

		return createEntityInput{
			Kind:          "monster",
			Title:         "Главарь разбойников",
			Subtitle:      "Лидер шайки и координатор засады",
			Summary:       "Командир небольшой банды, который держит подчинённых в строю и выбирает цель для фокуса.",
			Content:       "Главарь разбойников действует из укрытия, направляет обычных разбойников и вступает в бой только когда видит преимущество.",
			Tags:          []string{"ai-draft", "monster", "bandit", "leader"},
			Role:          "Encounter leader",
			Status:        "Hostile",
			Importance:    "Boss",
			StatBlock:     statBlock,
			RewardProfile: defaultBanditRewardProfile(true),
		}
	}

	statBlock := &npcStatBlock{
		Size:             "Medium",
		CreatureType:     "humanoid",
		Alignment:        "any non-good alignment",
		ArmorClass:       "12 (leather armor)",
		HitPoints:        "11 (2d8 + 2)",
		Speed:            "30 ft.",
		ProficiencyBonus: "+2",
		Challenge:        "1/8 (25 XP)",
		Senses:           "passive Perception 10",
		Languages:        "Common",
		AbilityScores:    abilityScores{STR: 11, DEX: 12, CON: 12, INT: 10, WIS: 10, CHA: 10},
		Actions: []statBlockEntry{
			{Name: "Scimitar", ToHit: "+3 to hit", Damage: "1d6 + 1 slashing damage", Description: "Melee Weapon Attack: +3 to hit, reach 5 ft., one target."},
			{Name: "Light Crossbow", ToHit: "+3 to hit", Damage: "1d8 + 1 piercing damage", Description: "Ranged Weapon Attack: +3 to hit, range 80/320 ft., one target."},
		},
	}

	return createEntityInput{
		Kind:          "monster",
		Title:         "Разбойник",
		Subtitle:      "Рядовой налётчик и боец ближней дистанции",
		Summary:       "Обычный бандит, который давит числом и старается добивать ослабленных целей.",
		Content:       "Разбойник держится рядом с товарищами, пользуется флангом и атакует того, кого уже связал главарь.",
		Tags:          []string{"ai-draft", "monster", "bandit", "minion"},
		Role:          "Encounter minion",
		Status:        "Hostile",
		Importance:    "Minion",
		StatBlock:     statBlock,
		RewardProfile: defaultBanditRewardProfile(false),
	}
}

func buildQuestDraft(prompt string) createEntityInput {
	title := draftTitle(prompt, "New Quest")
	return createEntityInput{
		Kind:          "quest",
		Title:         title,
		Subtitle:      "AI draft - active",
		Summary:       "Quest skeleton generated from the prompt and ready for prep.",
		Content:       title + " includes a goal, pressure and likely consequences for the world.",
		PlayerContent: title + " is presented to players as a concrete lead, rumor, job offer or plea for help without exposing the hidden agenda.",
		Tags:          []string{"ai-draft", "quest"},
		Status:        "active",
		Urgency:       "High",
		RewardProfile: fallbackRewardProfile(prompt, title, "quest"),
		QuickFacts: []quickFact{
			{Label: "Status", Value: "active", Tone: "accent"},
			{Label: "Urgency", Value: "High", Tone: "warning"},
			{Label: "Source", Value: "AI draft"},
		},
	}
}

func buildLoreDraft(prompt string) createEntityInput {
	title := draftTitle(prompt, "New Lore Fragment")
	return createEntityInput{
		Kind:       "lore",
		Title:      title,
		Subtitle:   "AI draft - GM view",
		Summary:    "Lore fragment generated as a worldbuilding draft.",
		Content:    title + " is framed as lore you can turn into a rumor, a truth or a hidden threat.",
		Tags:       []string{"ai-draft", "lore"},
		Category:   "History",
		Visibility: "gm_only",
		QuickFacts: []quickFact{
			{Label: "Category", Value: "History"},
			{Label: "Visibility", Value: "gm_only", Tone: "danger"},
			{Label: "Source", Value: "AI draft"},
		},
	}
}

func shouldGenerateQuestIssuerDraft(input generateEntityDraftInput, entity createEntityInput) bool {
	if normalizeEntityKind(input.Kind) != "quest" {
		return false
	}
	if strings.TrimSpace(entity.IssuerID) != "" {
		return false
	}
	if input.Current != nil && strings.TrimSpace(input.Current.IssuerID) != "" {
		return false
	}
	return true
}

func buildQuestIssuerDraft(prompt string, quest createEntityInput) createEntityInput {
	issuerPrompt := buildQuestIssuerPrompt(prompt, quest)
	draft := buildNpcDraft(issuerPrompt)
	draft.LocationID = quest.LocationID
	draft.Role = firstNonEmpty(strings.TrimSpace(draft.Role), "Quest giver")
	draft.Summary = firstNonEmpty(strings.TrimSpace(draft.Summary), draft.Title+" is the NPC who sets the party on this quest.")
	draft.Content = firstNonEmpty(strings.TrimSpace(draft.Content), draft.Title+" knows the hidden stakes, real danger and what happens if the quest fails.")
	draft.PlayerContent = firstNonEmpty(strings.TrimSpace(draft.PlayerContent), draft.Title+" can explain the job, visible stakes, promised reward and only the information safe to reveal to the party.")
	return draft
}

func buildQuestIssuerPrompt(prompt string, quest createEntityInput) string {
	return strings.TrimSpace(firstNonEmpty(prompt, "Новый квест") + "\n\nCreate the quest giver NPC for this quest.\nQuest title: " + firstNonEmpty(quest.Title, "Новый квест") + "\nQuest summary: " + firstNonEmpty(quest.Summary, quest.Content) + "\nThe NPC must fit the same campaign tone, have clear motives, know more than the players, and have a separate player-facing version of the information.")
}

func draftTitle(prompt string, fallback string) string {
	trimmed := strings.TrimSpace(prompt)
	if trimmed == "" {
		return fallback
	}

	words := strings.Fields(trimmed)
	if len(words) > 5 {
		words = words[:5]
	}

	return strings.TrimSpace(strings.Join(words, " "))
}

func containsAny(value string, options ...string) bool {
	lower := strings.ToLower(value)
	for _, option := range options {
		if strings.Contains(lower, strings.ToLower(option)) {
			return true
		}
	}
	return false
}

func fallbackEncounterFollowerTitle(title string) string {
	trimmed := strings.TrimSpace(title)
	if trimmed == "" {
		return "Приспешник"
	}
	return trimmed + " отряд"
}

func defaultMonsterRewardProfile(prompt string, title string) *monsterRewardProfile {
	switch {
	case containsAny(prompt, "wolf", "волк"):
		return &monsterRewardProfile{
			Summary: "С волка можно аккуратно снять шкуру и собрать рабочие трофеи, если разделать тушу до того, как она испортится.",
			Loot: []monsterLootEntry{
				{Name: "Волчья шкура", Category: "Трофей", Quantity: "1 шкура", Check: "Выживание", DC: "СЛ 12", Details: "Если проверка провалена на 5 и больше, шкура рвётся и годится только как дешёвый мех."},
				{Name: "Клыки и когти", Category: "Алхимия", Quantity: "4 клыка и 4 когтя", Check: "Выживание", DC: "СЛ 10", Details: "Их можно продать охотнику, пустить на тотемы или использовать как сырьё для мелких реагентов."},
			},
		}
	case containsAny(prompt, "spider", "паук"):
		return &monsterRewardProfile{
			Summary: "Паука ценят за яд, паутину и хитиновую броню, но добыча легко портится при грубой разделке.",
			Loot: []monsterLootEntry{
				{Name: "Ядовитые железы", Category: "Яд", Quantity: "2 железы", Check: "Медицина или Набор отравителя", DC: "СЛ 13", Details: "При провале яд проливается или обжигает сборщика; пригодные железы можно продать алхимику."},
				{Name: "Паутина", Category: "Ремесло", Quantity: "40 футов прочной паутины", Check: "Ловкость рук", DC: "СЛ 12", Details: "Подходит для ловушек, импровизированных сетей и редких алхимических смесей."},
			},
		}
	default:
		return &monsterRewardProfile{
			Summary: firstNonEmpty(title, "Монстр") + " оставляет после себя один пригодный трофейный комплект и явную зацепку, что с него можно снять.",
			Loot: []monsterLootEntry{
				{Name: "Трофейный материал", Category: "Трофей", Quantity: "1 комплект", Check: "Выживание", DC: "СЛ 12", Details: "Это могут быть рога, кость, чешуя, клык, жало или иной характерный материал, годный для продажи или крафта."},
			},
		}
	}
}

func defaultBanditRewardProfile(isLeader bool) *monsterRewardProfile {
	if isLeader {
		return &monsterRewardProfile{
			Summary: "У главаря обычно есть точная доля с последнего налёта, лучшее оружие и улики, ведущие к тайнику или заказчику.",
			Loot: []monsterLootEntry{
				{Name: "Кошель главаря", Category: "Деньги", Quantity: "18 см и 6 зм", Check: "Без проверки", Details: "Личные сбережения и точная доля главаря с последнего грабежа."},
				{Name: "План засады", Category: "Улика", Quantity: "1 лист", Check: "Расследование", DC: "СЛ 12", Details: "На схеме отмечен маршрут, условные сигналы и место встречи с посредником или тайником."},
				{Name: "Хорошее оружие", Category: "Оружие", Quantity: "1 оружие", Check: "Без проверки", Details: "Скимитар, тяжёлый арбалет или иное оружие в лучшем состоянии, чем у рядовых налётчиков."},
			},
		}
	}

	return &monsterRewardProfile{
		Summary: "Рядовые разбойники носят мелкую, но вполне конкретную добычу: деньги, оружие и заметки о передвижении шайки.",
		Loot: []monsterLootEntry{
			{Name: "Потрёпанный кошель", Category: "Деньги", Quantity: "7 см", Check: "Без проверки", Details: "Точная мелочь с дороги, пара жетонов и карманная добыча последней стоянки."},
			{Name: "Оружие налётчика", Category: "Оружие", Quantity: "1 оружие", Check: "Без проверки", Details: "Скимитар, дубинка или лёгкий арбалет, пригодный после быстрой чистки и замены ремня."},
		},
	}
}

func defaultHumanoidStatBlock(name string) *npcStatBlock {
	return &npcStatBlock{
		Size:             "Medium",
		CreatureType:     "humanoid",
		Alignment:        "neutral",
		ArmorClass:       "13",
		HitPoints:        "27 (5d8 + 5)",
		Speed:            "30 ft.",
		ProficiencyBonus: "+2",
		Challenge:        "1 (200 XP)",
		Senses:           "passive Perception 12",
		Languages:        "Common",
		AbilityScores:    abilityScores{STR: 11, DEX: 14, CON: 12, INT: 11, WIS: 12, CHA: 13},
		Traits:           []statBlockEntry{{Name: "Scaffold Profile", Description: name + " is a scaffold stat block meant for fast GM refinement."}},
		Actions:          []statBlockEntry{{Name: "Blade or Staff", ToHit: "+4 to hit", Damage: "1d8 + 2 damage", Description: "Baseline melee attack placeholder for quick prep."}},
	}
}

func defaultWolfStatBlock() *npcStatBlock {
	return &npcStatBlock{
		Size:             "Medium",
		CreatureType:     "beast",
		Alignment:        "unaligned",
		ArmorClass:       "13 (natural armor)",
		HitPoints:        "11 (2d8 + 2)",
		Speed:            "40 ft.",
		ProficiencyBonus: "+2",
		Challenge:        "1/4 (50 XP)",
		Senses:           "passive Perception 13",
		Skills:           "Perception +3, Stealth +4",
		Languages:        "--",
		AbilityScores:    abilityScores{STR: 12, DEX: 15, CON: 12, INT: 3, WIS: 12, CHA: 6},
		Traits: []statBlockEntry{
			{Name: "Keen Hearing and Smell", Description: "The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."},
			{Name: "Pack Tactics", Description: "The wolf has advantage on an attack roll against a creature if at least one ally is within 5 feet of the target."},
		},
		Actions: []statBlockEntry{{Name: "Bite", ToHit: "+4 to hit", Damage: "2d4 + 2 piercing damage", Description: "If the target is a creature, it must succeed on a DC 11 Strength save or be knocked prone."}},
	}
}

func defaultMonsterStatBlock(name string) *npcStatBlock {
	return &npcStatBlock{
		Size:             "Large",
		CreatureType:     "monstrosity",
		Alignment:        "unaligned",
		ArmorClass:       "13",
		HitPoints:        "45 (6d10 + 12)",
		Speed:            "30 ft.",
		ProficiencyBonus: "+2",
		Challenge:        "2 (450 XP)",
		Senses:           "darkvision 60 ft., passive Perception 11",
		AbilityScores:    abilityScores{STR: 15, DEX: 14, CON: 14, INT: 4, WIS: 12, CHA: 6},
		Traits:           []statBlockEntry{{Name: "Scaffold Predator", Description: name + " is a scaffold monster draft meant for encounter generation and quick refinement."}},
		Actions:          []statBlockEntry{{Name: "Claw or Bite", ToHit: "+4 to hit", Damage: "2d6 + 2 damage", Description: "Baseline monster attack placeholder for fast prep."}},
	}
}

func defaultSpiderStatBlock() *npcStatBlock {
	return &npcStatBlock{
		Size:             "Large",
		CreatureType:     "beast",
		Alignment:        "unaligned",
		ArmorClass:       "14 (natural armor)",
		HitPoints:        "26 (4d10 + 4)",
		Speed:            "30 ft., climb 30 ft.",
		ProficiencyBonus: "+2",
		Challenge:        "1 (200 XP)",
		Senses:           "darkvision 60 ft., passive Perception 10",
		Skills:           "Stealth +7",
		AbilityScores:    abilityScores{STR: 14, DEX: 16, CON: 12, INT: 2, WIS: 11, CHA: 4},
		Traits: []statBlockEntry{
			{Name: "Spider Climb", Description: "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."},
			{Name: "Web Sense", Description: "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web."},
		},
		Actions: []statBlockEntry{
			{Name: "Bite", ToHit: "+5 to hit", Damage: "1d8 + 3 piercing damage plus 2d8 poison damage", SaveDC: "DC 11 Constitution", Description: "If the target fails the save, it takes the poison damage; on a success, it takes half as much poison damage."},
			{Name: "Web (Recharge 5-6)", ToHit: "+5 to hit", SaveDC: "DC 12 Strength", Description: "Ranged weapon attack. The target is restrained by webbing. The restrained target can use its action to make a Strength check, freeing itself on a success."},
		},
	}
}
