import type { Bilingual, RuleCreature } from "./rule-creatures";

// Independently worded mechanics, SRD 5.2.1 Animals. Page references use the PDF page number.
const p = (ru: string, en: string): Bilingual => ({ ru, en });
const animal = (id: string, ru: string, en: string, page: number, armorClass: number, hp: number, hitDice: string, abilities: RuleCreature["abilities"], challenge: string, profile: Bilingual, rules: Bilingual[], initiative = Math.floor((abilities[1] - 10) / 2)): RuleCreature => ({
  id: `${id}-2024`, edition: "2024", name: p(ru, en),
  sourceUrl: `https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf#page=${page}`,
  armorClass, hp, hitDice, abilities, challenge, proficiency: Number(challenge) >= 5 ? 3 : 2, initiative, profile, rules,
});
const pack = p("Тактика стаи: Преимущество на атаки по существу, если в пределах 5 фт. от него есть союзник, который не Недееспособен.", "Pack Tactics: Advantage on attacks against a creature with an ally within 5 feet of it, provided that ally is not Incapacitated.");
const amphibious = p("Амфибия: дышит воздухом и водой.", "Amphibious: breathes air and water.");
const water = p("Дышит только под водой.", "Breathes only underwater.");
const flyby = p("Облёт: вылет из досягаемости врага не провоцирует атаку.", "Flyby: flying out of an enemy's reach does not provoke an Opportunity Attack.");
const climb = p("Паучье лазание: преодолевает сложные поверхности, включая потолки, без проверки характеристики.", "Spider Climb: climbs difficult surfaces, including ceilings, without an ability check.");
const leap = p("Прыжок с места: прыжок в длину до 20 фт., в высоту до 10 фт., с разбегом или без него.", "Standing Leap: Long Jump up to 20 ft. and High Jump up to 10 ft., with or without a running start.");
const swarmDefense = p("Сопротивление дробящему, колющему и рубящему урону. Иммунитет к Очарованию, Испугу, Захвату, Параличу, Окаменению, Сбиванию с ног, Опутыванию и Ошеломлению.", "Resistant to Bludgeoning, Piercing and Slashing damage. Immune to Charmed, Frightened, Grappled, Paralyzed, Petrified, Prone, Restrained and Stunned.");
const swarm = (ru: string, en: string) => p(`Рой: может находиться в пространстве другого существа и наоборот; проходит через отверстие, достаточно большое для Крошечного ${ru}. Не может восстанавливать хиты или получать временные хиты.`, `Swarm: can share another creature's space and vice versa; can pass through an opening large enough for a Tiny ${en}. Cannot regain Hit Points or gain Temporary Hit Points.`);
export const ANIMALS_2024: RuleCreature[] = [
  animal("allosaurus", "Аллозавр", "Allosaurus", 344, 13, 51, "6d10 + 18", [19,13,17,2,12,5], "2",
    p("Большой Зверь (динозавр), без мировоззрения. Скорость 60 фт. Внимательность +5; пассивная Внимательность 15; языков нет.", "Large unaligned Beast (Dinosaur). Speed 60 ft. Perception +5; passive Perception 15; no languages."), [
      p("Укус: рукопашная атака +6, досягаемость 5 фт.; 15 (2d10 + 4) колющего урона.", "Bite: melee attack +6, reach 5 ft.; 15 (2d10 + 4) Piercing damage."),
      p("Когти: рукопашная атака +6, досягаемость 5 фт.; 8 (1d8 + 4) рубящего урона. Если непосредственно перед попаданием аллозавр прошёл к цели не менее 30 фт. по прямой и цель — существо Большого или меньшего размера, она Сбита с ног, а аллозавр может совершить по ней одну атаку Укусом.", "Claws: melee attack +6, reach 5 ft.; 8 (1d8 + 4) Slashing damage. If the allosaurus moved at least 30 ft. straight toward the target immediately before the hit and the target is a Large or smaller creature, it is Prone and the allosaurus can make one Bite attack against it."),
    ]),
  animal("ankylosaurus", "Анкилозавр", "Ankylosaurus", 344, 15, 68, "8d12 + 16", [19,11,15,2,12,5], "3",
    p("Огромный Зверь (динозавр), без мировоззрения. Скорость 30 фт. Спасбросок Силы +6; пассивная Внимательность 11; языков нет.", "Huge unaligned Beast (Dinosaur). Speed 30 ft. Strength save +6; passive Perception 11; no languages."), [
      p("Мультиатака: две атаки Хвостом.", "Multiattack: two Tail attacks."),
      p("Хвост: рукопашная атака +6, досягаемость 10 фт.; 9 (1d10 + 4) дробящего урона. Существо Огромного или меньшего размера Сбито с ног.", "Tail: melee attack +6, reach 10 ft.; 9 (1d10 + 4) Bludgeoning damage. A Huge or smaller creature is Prone."),
    ]),
  animal("archelon", "Архелон", "Archelon", 344, 17, 90, "12d12 + 12", [18,16,13,4,14,6], "4",
    p("Огромный Зверь (динозавр), без мировоззрения. Скорость 20 фт., Плавание 80 фт. Скрытность +5; пассивная Внимательность 12; языков нет.", "Huge unaligned Beast (Dinosaur). Speed 20 ft., Swim 80 ft. Stealth +5; passive Perception 12; no languages."), [amphibious,
      p("Мультиатака: два Укуса.", "Multiattack: two Bite attacks."),
      p("Укус: рукопашная атака +6, досягаемость 5 фт.; 14 (3d6 + 4) колющего урона.", "Bite: melee attack +6, reach 5 ft.; 14 (3d6 + 4) Piercing damage."),
    ]),
  animal("rhinoceros", "Носорог", "Rhinoceros", 360, 13, 45, "6d10 + 12", [21,8,15,2,12,6], "2",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Speed 40 ft.; passive Perception 11; no languages."), [
      p("Рог: рукопашная атака +7, досягаемость 5 фт.; 14 (2d8 + 5) колющего урона. Если непосредственно перед попаданием носорог прошёл к цели не менее 20 фт. по прямой и цель — существо Большого или меньшего размера, она получает ещё 9 (2d8) колющего урона и Сбита с ног.", "Gore: melee attack +7, reach 5 ft.; 14 (2d8 + 5) Piercing damage. If the rhinoceros moved at least 20 ft. straight toward the target immediately before the hit and the target is a Large or smaller creature, it takes another 9 (2d8) Piercing damage and is Prone."),
    ]),
  animal("saber-toothed-tiger", "Саблезубый тигр", "Saber-Toothed Tiger", 360, 13, 52, "7d10 + 14", [18,17,15,3,12,8], "2",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт. Спасброски Силы +6, Ловкости +5; Внимательность +5, Скрытность +7; Тёмное зрение 60 фт.; пассивная Внимательность 15; языков нет.", "Large unaligned Beast. Speed 40 ft. Strength save +6, Dexterity save +5; Perception +5, Stealth +7; Darkvision 60 ft.; passive Perception 15; no languages."), [
      p("Прыжок с разбега: после разбега 10 фт. прыжок в длину до 25 фт.", "Running Leap: after a 10-foot running start, Long Jump up to 25 ft."),
      p("Мультиатака: две атаки Разрыванием.", "Multiattack: two Rend attacks."),
      p("Разрывание: рукопашная атака +6, досягаемость 5 фт.; 11 (2d6 + 4) рубящего урона.", "Rend: melee attack +6, reach 5 ft.; 11 (2d6 + 4) Slashing damage."),
      p("Ловкое отступление (бонусное действие): Отход или Засада.", "Nimble Escape (Bonus Action): Disengage or Hide."),
    ]),
  animal("swarm-of-bats", "Рой летучих мышей", "Swarm of Bats", 361, 12, 11, "2d10", [5,15,10,2,12,4], "1/4",
    p("Большой рой Крошечных Зверей, без мировоззрения. Скорость 5 фт., Полёт 30 фт.; Слепое зрение 60 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Swarm of Tiny Beasts. Speed 5 ft., Fly 30 ft.; Blindsight 60 ft.; passive Perception 11; no languages."), [swarmDefense, swarm("зверя — летучей мыши", "bat"),
      p("Укусы: рукопашная атака +4, досягаемость 5 фт.; 5 (2d4) колющего урона, либо 2 (1d4), если у роя осталось не больше половины максимума хитов.", "Bites: melee attack +4, reach 5 ft.; 5 (2d4) Piercing damage, or 2 (1d4) if the swarm is Bloodied (at half its Hit Point maximum or lower)."),
    ]),
  animal("swarm-of-insects", "Рой насекомых", "Swarm of Insects", 361, 11, 19, "3d8 + 6", [3,13,14,1,7,1], "1/2",
    p("Средний рой Крошечных Зверей, без мировоззрения. Скорость 20 фт.; Лазание или Полёт 20 фт. на выбор мастера. Слепое зрение 30 фт.; пассивная Внимательность 8; языков нет.", "Medium unaligned Swarm of Tiny Beasts. Speed 20 ft.; Climb or Fly 20 ft., GM's choice. Blindsight 30 ft.; passive Perception 8; no languages."), [swarmDefense, swarm("насекомого", "insect"),
      p("Паучье лазание: если у роя есть скорость Лазания, сложные поверхности, включая потолки, преодолеваются без проверки характеристики.", "Spider Climb: if the swarm has a Climb Speed, it climbs difficult surfaces, including ceilings, without an ability check."),
      p("Укусы: рукопашная атака +3, досягаемость 5 фт.; 6 (2d4 + 1) урона ядом, либо 3 (1d4 + 1), если у роя осталось не больше половины максимума хитов.", "Bites: melee attack +3, reach 5 ft.; 6 (2d4 + 1) Poison damage, or 3 (1d4 + 1) if the swarm is Bloodied (at half its Hit Point maximum or lower)."),
    ]),
  animal("swarm-of-piranhas", "Рой пираний", "Swarm of Piranhas", 362, 13, 28, "8d8 - 8", [13,16,9,1,7,2], "1",
    p("Средний рой Крошечных Зверей, без мировоззрения. Скорость 5 фт., Плавание 40 фт.; Тёмное зрение 60 фт.; пассивная Внимательность 8; языков нет.", "Medium unaligned Swarm of Tiny Beasts. Speed 5 ft., Swim 40 ft.; Darkvision 60 ft.; passive Perception 8; no languages."), [swarmDefense, swarm("зверя — пираньи", "piranha"), water,
      p("Укусы: рукопашная атака +5, с Преимуществом против цели с неполными хитами, досягаемость 5 фт.; 8 (2d4 + 3) колющего урона, либо 5 (1d4 + 3), если у роя осталось не больше половины максимума хитов.", "Bites: melee attack +5, with Advantage against a target missing any Hit Points, reach 5 ft.; 8 (2d4 + 3) Piercing damage, or 5 (1d4 + 3) if the swarm is Bloodied (at half its Hit Point maximum or lower)."),
    ]),
  animal("swarm-of-ravens", "Рой воронов", "Swarm of Ravens", 362, 12, 11, "2d8 + 2", [6,14,12,5,12,6], "1/4",
    p("Средний рой Крошечных Зверей, без мировоззрения. Скорость 10 фт., Полёт 50 фт. Внимательность +5; пассивная Внимательность 15; языков нет.", "Medium unaligned Swarm of Tiny Beasts. Speed 10 ft., Fly 50 ft. Perception +5; passive Perception 15; no languages."), [swarmDefense, swarm("ворона", "raven"),
      p("Клювы: рукопашная атака +4, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона, либо 2 (1d4), если у роя осталось не больше половины максимума хитов.", "Beaks: melee attack +4, reach 5 ft.; 5 (1d6 + 2) Piercing damage, or 2 (1d4) if the swarm is Bloodied (at half its Hit Point maximum or lower)."),
      p("Какофония (перезарядка 6): одно существо в пространстве роя делает спасбросок Мудрости Сл 10. Провал: Оглохло до начала следующего хода роя; пока оглохло таким образом, имеет Помеху на проверки характеристик и броски атаки.", "Cacophony (Recharge 6): one creature in the swarm's space makes a DC 10 Wisdom save. Failure: Deafened until the start of the swarm's next turn; while Deafened this way, it also has Disadvantage on ability checks and attack rolls."),
    ]),
  animal("swarm-of-venomous-snakes", "Рой ядовитых змей", "Swarm of Venomous Snakes", 362, 14, 36, "8d8", [8,18,11,1,10,3], "2",
    p("Средний рой Крошечных Зверей, без мировоззрения. Скорость 30 фт., Плавание 30 фт.; Слепое зрение 10 фт.; пассивная Внимательность 10; языков нет.", "Medium unaligned Swarm of Tiny Beasts. Speed 30 ft., Swim 30 ft.; Blindsight 10 ft.; passive Perception 10; no languages."), [swarmDefense, swarm("зверя — змеи", "snake"),
      p("Укусы: рукопашная атака +6, досягаемость 5 фт.; 8 (1d8 + 4) колющего урона, либо 6 (1d4 + 4), если у роя осталось не больше половины максимума хитов; в обоих случаях ещё 10 (3d6) урона ядом.", "Bites: melee attack +6, reach 5 ft.; 8 (1d8 + 4) Piercing damage, or 6 (1d4 + 4) if the swarm is Bloodied (at half its Hit Point maximum or lower); plus 10 (3d6) Poison damage in either case."),
    ]),
  animal("triceratops", "Трицератопс", "Triceratops", 363, 14, 114, "12d12 + 36", [22,9,17,2,11,5], "5",
    p("Огромный Зверь (динозавр), без мировоззрения. Скорость 50 фт.; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast (Dinosaur). Speed 50 ft.; passive Perception 10; no languages."), [
      p("Мультиатака: две атаки Рогами.", "Multiattack: two Gore attacks."),
      p("Рога: рукопашная атака +9, досягаемость 5 фт.; 19 (2d12 + 6) колющего урона. Если цель Огромного или меньшего размера и непосредственно перед попаданием трицератопс прошёл к ней не менее 20 фт. по прямой, она получает ещё 9 (2d8) колющего урона и Сбита с ног.", "Gore: melee attack +9, reach 5 ft.; 19 (2d12 + 6) Piercing damage. If the target is Huge or smaller and the triceratops moved at least 20 ft. straight toward it immediately before the hit, it takes another 9 (2d8) Piercing damage and is Prone."),
    ]),
  animal("tyrannosaurus-rex", "Тираннозавр", "Tyrannosaurus Rex", 363, 13, 136, "13d12 + 52", [25,10,19,2,12,9], "8",
    p("Огромный Зверь (динозавр), без мировоззрения. Скорость 50 фт. Спасброски Силы +10, Мудрости +4; Внимательность +4; пассивная Внимательность 14; языков нет.", "Huge unaligned Beast (Dinosaur). Speed 50 ft. Strength save +10, Wisdom save +4; Perception +4; passive Perception 14; no languages."), [
      p("Мультиатака: один Укус и одна атака Хвостом.", "Multiattack: one Bite and one Tail attack."),
      p("Укус: рукопашная атака +10, досягаемость 10 фт.; 33 (4d12 + 7) колющего урона. Существо Большого или меньшего размера Схвачено (Сл высвобождения 17). Пока захват сохраняется, оно Опутано и не может быть целью Хвоста тираннозавра.", "Bite: melee attack +10, reach 10 ft.; 33 (4d12 + 7) Piercing damage. A Large or smaller creature is Grappled (escape DC 17). While Grappled, it is Restrained and cannot be targeted by the tyrannosaurus's Tail."),
      p("Хвост: рукопашная атака +10, досягаемость 15 фт.; 25 (4d8 + 7) дробящего урона. Существо Огромного или меньшего размера Сбито с ног.", "Tail: melee attack +10, reach 15 ft.; 25 (4d8 + 7) Bludgeoning damage. A Huge or smaller creature is Prone."),
    ], 3),
  animal("venomous-snake", "Ядовитая змея", "Venomous Snake", 363, 12, 5, "2d4", [2,15,11,1,10,3], "1/8",
    p("Крошечный Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт.; Слепое зрение 10 фт.; пассивная Внимательность 10; языков нет.", "Tiny unaligned Beast. Speed 30 ft., Swim 30 ft.; Blindsight 10 ft.; passive Perception 10; no languages."), [
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) колющего урона и 3 (1d6) урона ядом.", "Bite: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Piercing plus 3 (1d6) Poison damage."),
    ]),
  animal("warhorse", "Боевой конь", "Warhorse", 364, 11, 19, "3d10 + 3", [18,12,13,2,12,7], "1/2",
    p("Большой Зверь, без мировоззрения. Скорость 60 фт. Спасбросок Мудрости +3; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Speed 60 ft. Wisdom save +3; passive Perception 11; no languages."), [
      p("Копыта: рукопашная атака +6, досягаемость 5 фт.; 9 (2d4 + 4) дробящего урона. Если непосредственно перед попаданием конь прошёл к цели не менее 20 фт. по прямой и цель — существо Большого или меньшего размера, она получает ещё 5 (2d4) дробящего урона и Сбита с ног.", "Hooves: melee attack +6, reach 5 ft.; 9 (2d4 + 4) Bludgeoning damage. If the horse moved at least 20 ft. straight toward the target immediately before the hit and the target is a Large or smaller creature, it takes another 5 (2d4) Bludgeoning damage and is Prone."),
    ]),
  animal("wolf", "Волк", "Wolf", 364, 12, 11, "2d8 + 2", [14,15,12,3,12,6], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт. Внимательность +5, Скрытность +4; Тёмное зрение 60 фт.; пассивная Внимательность 15; языков нет.", "Medium unaligned Beast. Speed 40 ft. Perception +5, Stealth +4; Darkvision 60 ft.; passive Perception 15; no languages."), [pack,
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона. Существо Среднего или меньшего размера Сбито с ног.", "Bite: melee attack +4, reach 5 ft.; 5 (1d6 + 2) Piercing damage. A Medium or smaller creature is Prone."),
    ]),
  animal("giant-wasp", "Гигантская оса", "Giant Wasp", 354, 13, 22, "5d8", [10,14,10,1,10,3], "1/2",
    p("Средний Зверь, без мировоззрения. Скорость 10 фт., Полёт 50 фт.; пассивная Внимательность 10; языков нет.", "Medium unaligned Beast. Speed 10 ft., Fly 50 ft.; passive Perception 10; no languages."), [flyby,
      p("Жало: рукопашная атака +4, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона и 5 (2d4) урона ядом.", "Sting: melee attack +4, reach 5 ft.; 5 (1d6 + 2) Piercing plus 5 (2d4) Poison damage."),
    ]),
  animal("giant-wolf-spider", "Гигантский паук-волк", "Giant Wolf Spider", 355, 13, 11, "2d8 + 2", [12,16,13,3,12,4], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт., Лазание 40 фт. Внимательность +3, Скрытность +7; Слепое зрение 10 фт., Тёмное зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 40 ft., Climb 40 ft. Perception +3, Stealth +7; Blindsight 10 ft., Darkvision 60 ft.; passive Perception 13; no languages."), [climb,
      p("Укус: рукопашная атака +5, досягаемость 5 фт.; 5 (1d4 + 3) колющего урона и 5 (2d4) урона ядом.", "Bite: melee attack +5, reach 5 ft.; 5 (1d4 + 3) Piercing plus 5 (2d4) Poison damage."),
    ]),
  animal("hippopotamus", "Бегемот", "Hippopotamus", 355, 14, 82, "11d10 + 22", [21,7,15,2,12,4], "4",
    p("Большой Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Спасбросок Силы +7; Внимательность +3; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Speed 30 ft., Swim 30 ft. Strength save +7; Perception +3; passive Perception 13; no languages."), [
      p("Задержка дыхания: 10 минут.", "Hold Breath: 10 minutes."),
      p("Мультиатака: два Укуса.", "Multiattack: two Bite attacks."),
      p("Укус: рукопашная атака +7, досягаемость 5 фт.; 16 (2d10 + 5) колющего урона.", "Bite: melee attack +7, reach 5 ft.; 16 (2d10 + 5) Piercing damage."),
    ]),
  animal("hunter-shark", "Акула-охотник", "Hunter Shark", 356, 12, 45, "6d10 + 12", [18,14,15,1,10,4], "2",
    p("Большой Зверь, без мировоззрения. Скорость 5 фт., Плавание 40 фт. Внимательность +2; Слепое зрение 60 фт.; пассивная Внимательность 12; языков нет.", "Large unaligned Beast. Speed 5 ft., Swim 40 ft. Perception +2; Blindsight 60 ft.; passive Perception 12; no languages."), [water,
      p("Укус: рукопашная атака +6, с Преимуществом против цели с неполными хитами, досягаемость 5 фт.; 14 (3d6 + 4) колющего урона.", "Bite: melee attack +6, with Advantage against a target missing any Hit Points, reach 5 ft.; 14 (3d6 + 4) Piercing damage."),
    ]),
  animal("killer-whale", "Косатка", "Killer Whale", 356, 12, 90, "12d12 + 12", [19,14,13,3,12,7], "3",
    p("Огромный Зверь, без мировоззрения. Скорость 5 фт., Плавание 60 фт. Внимательность +3, Скрытность +4; Слепое зрение 120 фт.; пассивная Внимательность 13; языков нет.", "Huge unaligned Beast. Speed 5 ft., Swim 60 ft. Perception +3, Stealth +4; Blindsight 120 ft.; passive Perception 13; no languages."), [
      p("Задержка дыхания: 30 минут.", "Hold Breath: 30 minutes."),
      p("Укус: рукопашная атака +6, досягаемость 5 фт.; 21 (5d6 + 4) колющего урона.", "Bite: melee attack +6, reach 5 ft.; 21 (5d6 + 4) Piercing damage."),
    ]),
  animal("mammoth", "Мамонт", "Mammoth", 357, 13, 126, "11d12 + 55", [24,9,21,3,11,6], "6",
    p("Огромный Зверь, без мировоззрения. Скорость 50 фт. Спасброски Силы +10, Телосложения +8; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Speed 50 ft. Strength save +10, Constitution save +8; passive Perception 10; no languages."), [
      p("Мультиатака: две атаки Бивнями.", "Multiattack: two Gore attacks."),
      p("Бивни: рукопашная атака +10, досягаемость 10 фт.; 18 (2d10 + 7) колющего урона. Если непосредственно перед попаданием мамонт прошёл к цели не менее 20 фт. по прямой и цель — существо Огромного или меньшего размера, она Сбита с ног.", "Gore: melee attack +10, reach 10 ft.; 18 (2d10 + 7) Piercing damage. If the mammoth moved at least 20 ft. straight toward the target immediately before the hit and the target is a Huge or smaller creature, it is Prone."),
      p("Растаптывание (бонусное действие): одно Сбитое с ног существо в 5 фт. делает спасбросок Ловкости Сл 18. Провал: 29 (4d10 + 7) дробящего урона; успех: половина.", "Trample (Bonus Action): one Prone creature within 5 ft. makes a DC 18 Dexterity save. Failure: 29 (4d10 + 7) Bludgeoning damage; success: half."),
    ], 2),
  animal("mule", "Мул", "Mule", 357, 10, 11, "2d8 + 2", [14,10,13,2,10,5], "1/8",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт. Спасбросок Силы +4; пассивная Внимательность 10; языков нет.", "Medium unaligned Beast. Speed 40 ft. Strength save +4; passive Perception 10; no languages."), [
      p("Вьючное животное: при определении грузоподъёмности считается на одну категорию крупнее.", "Beast of Burden: counts as one size larger when determining carrying capacity."),
      p("Копыта: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) дробящего урона.", "Hooves: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Bludgeoning damage."),
    ]),
  animal("plesiosaurus", "Плезиозавр", "Plesiosaurus", 358, 13, 68, "8d10 + 24", [18,15,16,2,12,5], "2",
    p("Большой Зверь (динозавр), без мировоззрения. Скорость 20 фт., Плавание 40 фт. Внимательность +3, Скрытность +4; пассивная Внимательность 13; языков нет.", "Large unaligned Beast (Dinosaur). Speed 20 ft., Swim 40 ft. Perception +3, Stealth +4; passive Perception 13; no languages."), [
      p("Задержка дыхания: 1 час.", "Hold Breath: 1 hour."),
      p("Укус: рукопашная атака +6, досягаемость 10 фт.; 11 (2d6 + 4) колющего урона.", "Bite: melee attack +6, reach 10 ft.; 11 (2d6 + 4) Piercing damage."),
    ]),
  animal("polar-bear", "Белый медведь", "Polar Bear", 359, 12, 42, "5d10 + 15", [20,14,16,2,13,7], "2",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт., Плавание 40 фт. Внимательность +5, Скрытность +4; сопротивление холоду; Тёмное зрение 60 фт.; пассивная Внимательность 15; языков нет.", "Large unaligned Beast. Speed 40 ft., Swim 40 ft. Perception +5, Stealth +4; Cold Resistance; Darkvision 60 ft.; passive Perception 15; no languages."), [
      p("Мультиатака: две атаки Разрыванием.", "Multiattack: two Rend attacks."),
      p("Разрывание: рукопашная атака +7, досягаемость 5 фт.; 9 (1d8 + 5) рубящего урона.", "Rend: melee attack +7, reach 5 ft.; 9 (1d8 + 5) Slashing damage."),
    ]),
  animal("pony", "Пони", "Pony", 359, 10, 11, "2d8 + 2", [15,10,13,2,11,7], "1/8",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт. Спасбросок Силы +4; пассивная Внимательность 10; языков нет.", "Medium unaligned Beast. Speed 40 ft. Strength save +4; passive Perception 10; no languages."), [
      p("Копыта: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) дробящего урона.", "Hooves: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Bludgeoning damage."),
    ]),
  animal("pteranodon", "Птеранодон", "Pteranodon", 359, 13, 13, "3d8", [12,15,10,2,9,5], "1/4",
    p("Средний Зверь (динозавр), без мировоззрения. Скорость 10 фт., Полёт 60 фт. Внимательность +1; пассивная Внимательность 11; языков нет.", "Medium unaligned Beast (Dinosaur). Speed 10 ft., Fly 60 ft. Perception +1; passive Perception 11; no languages."), [flyby,
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 6 (1d8 + 2) колющего урона.", "Bite: melee attack +4, reach 5 ft.; 6 (1d8 + 2) Piercing damage."),
    ]),
  animal("reef-shark", "Рифовая акула", "Reef Shark", 360, 12, 22, "4d8 + 4", [14,15,13,1,10,4], "1/2",
    p("Средний Зверь, без мировоззрения. Скорость 5 фт., Плавание 30 фт. Внимательность +2; Слепое зрение 30 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 5 ft., Swim 30 ft. Perception +2; Blindsight 30 ft.; passive Perception 12; no languages."), [pack, water,
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 7 (2d4 + 2) колющего урона.", "Bite: melee attack +4, reach 5 ft.; 7 (2d4 + 2) Piercing damage."),
    ]),
  animal("giant-crocodile", "Гигантский крокодил", "Giant Crocodile", 350, 14, 85, "9d12 + 27", [21,9,17,2,10,7], "5",
    p("Огромный Зверь, без мировоззрения. Скорость 30 фт., Плавание 50 фт. Скрытность +5; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Speed 30 ft., Swim 50 ft. Stealth +5; passive Perception 10; no languages."), [
      p("Задержка дыхания: 1 час.", "Hold Breath: 1 hour."),
      p("Мультиатака: один Укус и одна атака Хвостом.", "Multiattack: one Bite and one Tail attack."),
      p("Укус: рукопашная атака +8, досягаемость 5 фт.; 21 (3d10 + 5) колющего урона. Существо Большого или меньшего размера Схвачено (Сл высвобождения 15). Пока захват сохраняется, оно Опутано и не может быть целью Хвоста крокодила.", "Bite: melee attack +8, reach 5 ft.; 21 (3d10 + 5) Piercing damage. A Large or smaller creature is Grappled (escape DC 15). While Grappled, it is Restrained and cannot be targeted by the crocodile's Tail."),
      p("Хвост: рукопашная атака +8, досягаемость 10 фт.; 18 (3d8 + 5) дробящего урона. Существо Большого или меньшего размера Сбито с ног.", "Tail: melee attack +8, reach 10 ft.; 18 (3d8 + 5) Bludgeoning damage. A Large or smaller creature is Prone."),
    ]),
  animal("giant-eagle", "Гигантский орёл", "Giant Eagle", 350, 13, 26, "4d10 + 4", [16,17,13,8,14,10], "1",
    p("Большой Небожитель, нейтрально-добрый. Скорость 10 фт., Полёт 80 фт. Внимательность +6; сопротивление некротическому урону и излучению; пассивная Внимательность 16. Небесный язык; понимает Общий и Первичный (Воздушный), но не говорит на них.", "Large Neutral Good Celestial. Speed 10 ft., Fly 80 ft. Perception +6; Necrotic and Radiant Resistance; passive Perception 16. Celestial; understands Common and Primordial (Auran) but cannot speak them."), [
      p("Мультиатака: две атаки Разрыванием.", "Multiattack: two Rend attacks."),
      p("Разрывание: рукопашная атака +5, досягаемость 5 фт.; 5 (1d4 + 3) рубящего урона и 3 (1d6) урона излучением.", "Rend: melee attack +5, reach 5 ft.; 5 (1d4 + 3) Slashing plus 3 (1d6) Radiant damage."),
    ]),
  animal("giant-frog", "Гигантская лягушка", "Giant Frog", 351, 11, 18, "4d8", [12,13,11,2,10,3], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2, Скрытность +4; Тёмное зрение 30 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2, Stealth +4; Darkvision 30 ft.; passive Perception 12; no languages."), [amphibious, leap,
      p("Укус: рукопашная атака +3, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона. Существо Среднего или меньшего размера Схвачено, Сл высвобождения 11.", "Bite: melee attack +3, reach 5 ft.; 5 (1d6 + 2) Piercing damage. A Medium or smaller creature is Grappled, escape DC 11."),
      p("Проглатывание: проглотите схваченную цель Маленького или меньшего размера. Она больше не Схвачена, но Ослеплена и Опутана, имеет полное укрытие от атак и эффектов снаружи. Пока цель внутри, Укус недоступен. В конце следующего хода лягушки цель получает 5 (2d4) урона кислотой; если она выжила, лягушка выплёвывает её Сбитой с ног. Если лягушка умирает, цель больше не Опутана и может выйти из трупа, потратив 5 фт. перемещения, Сбитой с ног.", "Swallow: swallow a Small or smaller grappled target. It is no longer Grappled, but is Blinded and Restrained with Total Cover against attacks and effects outside. Bite is unavailable while a target is inside. At the end of the frog's next turn the target takes 5 (2d4) Acid damage; if it survives, the frog disgorges it Prone. If the frog dies, the target is no longer Restrained and can leave the corpse by spending 5 ft. of movement, exiting Prone."),
    ]),
  animal("giant-lizard", "Гигантская ящерица", "Giant Lizard", 352, 12, 19, "3d10 + 3", [15,12,13,2,10,5], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт., Лазание 40 фт. Спасбросок Ловкости +3; Тёмное зрение 60 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 40 ft., Climb 40 ft. Dexterity save +3; Darkvision 60 ft.; passive Perception 10; no languages."), [climb,
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 6 (1d8 + 2) колющего урона.", "Bite: melee attack +4, reach 5 ft.; 6 (1d8 + 2) Piercing damage."),
    ]),
  animal("giant-octopus", "Гигантский осьминог", "Giant Octopus", 352, 11, 45, "7d10 + 7", [17,13,13,5,10,4], "1",
    p("Большой Зверь, без мировоззрения. Скорость 10 фт., Плавание 60 фт. Внимательность +4, Скрытность +5; Тёмное зрение 60 фт.; пассивная Внимательность 14; языков нет.", "Large unaligned Beast. Speed 10 ft., Swim 60 ft. Perception +4, Stealth +5; Darkvision 60 ft.; passive Perception 14; no languages."), [water,
      p("На воздухе задерживает дыхание на 1 час.", "Can hold its breath for 1 hour outside water."),
      p("Щупальца: рукопашная атака +5, досягаемость 10 фт.; 10 (2d6 + 3) дробящего урона. Существо Среднего или меньшего размера Схвачено всеми восемью щупальцами (Сл высвобождения 13) и Опутано, пока захват сохраняется.", "Tentacles: melee attack +5, reach 10 ft.; 10 (2d6 + 3) Bludgeoning damage. A Medium or smaller creature is Grappled by all eight tentacles (escape DC 13) and Restrained while the grapple lasts."),
      p("Чернильное облако (реакция, 1/день): получив урон под водой, выпустите чернила в куб со стороной 10 фт. с центром на себе и переместитесь на расстояние до скорости Плавания. Куб сильно заслонён на 1 минуту либо до рассеивания чернил сильным течением или подобным эффектом.", "Ink Cloud (Reaction, 1/Day): when damaged underwater, release ink in a 10-foot Cube centered on yourself and move up to your Swim Speed. The Cube is Heavily Obscured for 1 minute or until a strong current or similar effect disperses the ink."),
    ]),
  animal("giant-scorpion", "Гигантский скорпион", "Giant Scorpion", 353, 15, 52, "7d10 + 14", [16,13,15,1,9,3], "3",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт.; Слепое зрение 60 фт.; пассивная Внимательность 9; языков нет.", "Large unaligned Beast. Speed 40 ft.; Blindsight 60 ft.; passive Perception 9; no languages."), [
      p("Мультиатака: две атаки Клешнёй и одна Жалом.", "Multiattack: two Claw attacks and one Sting."),
      p("Клешня: рукопашная атака +5, досягаемость 5 фт.; 6 (1d6 + 3) дробящего урона. Существо Большого или меньшего размера Схвачено одной из двух клешней, Сл высвобождения 13.", "Claw: melee attack +5, reach 5 ft.; 6 (1d6 + 3) Bludgeoning damage. A Large or smaller creature is Grappled by one of two claws, escape DC 13."),
      p("Жало: рукопашная атака +5, досягаемость 5 фт.; 7 (1d8 + 3) колющего урона и 11 (2d10) урона ядом.", "Sting: melee attack +5, reach 5 ft.; 7 (1d8 + 3) Piercing plus 11 (2d10) Poison damage."),
    ]),
  animal("giant-seahorse", "Гигантский морской конёк", "Giant Seahorse", 353, 14, 16, "3d10", [15,12,11,2,12,5], "1/2",
    p("Большой Зверь, без мировоззрения. Скорость 5 фт., Плавание 40 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Speed 5 ft., Swim 40 ft.; passive Perception 11; no languages."), [water,
      p("Таран: рукопашная атака +4, досягаемость 5 фт.; 9 (2d6 + 2) дробящего урона, либо 11 (2d8 + 2), если непосредственно перед попаданием конёк прошёл к цели не менее 20 фт. по прямой.", "Ram: melee attack +4, reach 5 ft.; 9 (2d6 + 2) Bludgeoning damage, or 11 (2d8 + 2) if the seahorse moved at least 20 ft. straight toward the target immediately before the hit."),
      p("Пузырьковый рывок (бонусное действие): под водой переместитесь на расстояние до половины скорости Плавания без провоцированных атак.", "Bubble Dash (Bonus Action): underwater, move up to half your Swim Speed without provoking Opportunity Attacks."),
    ]),
  animal("giant-shark", "Гигантская акула", "Giant Shark", 353, 13, 92, "8d12 + 40", [23,11,21,1,10,5], "5",
    p("Огромный Зверь, без мировоззрения. Скорость 5 фт., Плавание 60 фт. Внимательность +3; Слепое зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Huge unaligned Beast. Speed 5 ft., Swim 60 ft. Perception +3; Blindsight 60 ft.; passive Perception 13; no languages."), [water,
      p("Мультиатака: два Укуса.", "Multiattack: two Bite attacks."),
      p("Укус: рукопашная атака +9, с Преимуществом против цели с неполными хитами, досягаемость 5 фт.; 22 (3d10 + 6) колющего урона.", "Bite: melee attack +9, with Advantage against a target missing any Hit Points, reach 5 ft.; 22 (3d10 + 6) Piercing damage."),
    ], 3),
  animal("giant-spider", "Гигантский паук", "Giant Spider", 353, 14, 26, "4d10 + 4", [14,16,12,2,11,4], "1",
    p("Большой Зверь, без мировоззрения. Скорость 30 фт., Лазание 30 фт. Внимательность +4, Скрытность +7; Тёмное зрение 60 фт.; пассивная Внимательность 14; языков нет.", "Large unaligned Beast. Speed 30 ft., Climb 30 ft. Perception +4, Stealth +7; Darkvision 60 ft.; passive Perception 14; no languages."), [climb,
      p("Хождение по паутине: игнорирует ограничения перемещения от паутины и знает местоположение других существ, касающихся той же паутины.", "Web Walker: ignores movement restrictions from webs and knows the location of other creatures touching the same web."),
      p("Укус: рукопашная атака +5, досягаемость 5 фт.; 7 (1d8 + 3) колющего урона и 7 (2d6) урона ядом.", "Bite: melee attack +5, reach 5 ft.; 7 (1d8 + 3) Piercing plus 7 (2d6) Poison damage."),
      p("Паутина (перезарядка 5–6): одно видимое существо в пределах 60 фт. делает спасбросок Ловкости Сл 13. Провал: Опутано до уничтожения паутины. Паутина: КД 10, 5 хитов, уязвимость к огню, иммунитет к яду и психическому урону.", "Web (Recharge 5–6): one visible creature within 60 ft. makes a DC 13 Dexterity save. Failure: Restrained until the web is destroyed. Web: AC 10, 5 HP, Fire Vulnerability, Poison and Psychic Immunity."),
    ]),
  animal("giant-toad", "Гигантская жаба", "Giant Toad", 354, 11, 39, "6d10 + 6", [15,13,13,2,10,3], "1",
    p("Большой Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт.; Тёмное зрение 60 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 30 ft., Swim 30 ft.; Darkvision 60 ft.; passive Perception 10; no languages."), [amphibious, leap,
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона и 5 (2d4) урона ядом. Существо Среднего или меньшего размера Схвачено, Сл высвобождения 12.", "Bite: melee attack +4, reach 5 ft.; 5 (1d6 + 2) Piercing plus 5 (2d4) Poison damage. A Medium or smaller creature is Grappled, escape DC 12."),
      p("Проглатывание: проглотите схваченную цель Среднего или меньшего размера. Она больше не Схвачена, но Ослеплена и Опутана, имеет полное укрытие от атак и эффектов снаружи. В конце каждого хода жабы цель получает 10 (3d6) урона кислотой. Внутри может находиться только одна цель; пока она там, Укус недоступен. Если жаба умирает, цель больше не Опутана и может выйти из трупа, потратив 5 фт. перемещения, Сбитой с ног.", "Swallow: swallow a Medium or smaller grappled target. It is no longer Grappled but is Blinded and Restrained with Total Cover against attacks and effects outside. It takes 10 (3d6) Acid damage at the end of each of the toad's turns. Only one target can be swallowed at a time; Bite is unavailable while it is inside. If the toad dies, the target is no longer Restrained and can leave the corpse by spending 5 ft. of movement, exiting Prone."),
    ]),
  animal("giant-venomous-snake", "Гигантская ядовитая змея", "Giant Venomous Snake", 354, 14, 11, "2d8 + 2", [10,18,13,2,10,3], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт., Плавание 40 фт. Внимательность +2; Слепое зрение 10 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 40 ft., Swim 40 ft. Perception +2; Blindsight 10 ft.; passive Perception 12; no languages."), [
      p("Укус: рукопашная атака +6, досягаемость 10 фт.; 6 (1d4 + 4) колющего урона и 4 (1d8) урона ядом.", "Bite: melee attack +6, reach 10 ft.; 6 (1d4 + 4) Piercing plus 4 (1d8) Poison damage."),
    ]),
  animal("giant-vulture", "Гигантский стервятник", "Giant Vulture", 354, 10, 25, "3d10 + 9", [15,10,16,6,12,7], "1",
    p("Большая Монструозность, нейтрально-злая. Скорость 10 фт., Полёт 60 фт. Внимательность +3; сопротивление некротическому урону; Тёмное зрение 60 фт.; пассивная Внимательность 13. Понимает Общий, но не говорит.", "Large Neutral Evil Monstrosity. Speed 10 ft., Fly 60 ft. Perception +3; Necrotic Resistance; Darkvision 60 ft.; passive Perception 13. Understands Common but cannot speak."), [pack,
      p("Терзание: рукопашная атака +4, досягаемость 5 фт.; 9 (2d6 + 2) колющего урона, и цель Отравлена до конца своего следующего хода.", "Gouge: melee attack +4, reach 5 ft.; 9 (2d6 + 2) Piercing damage and the target is Poisoned until the end of its next turn."),
    ]),
  animal("blood-hawk", "Кровавый ястреб", "Blood Hawk", 345, 12, 7, "2d6", [6,14,10,3,14,5], "1/8",
    p("Маленький Зверь, без мировоззрения. Скорость 10 фт., Полёт 60 фт. Внимательность +6; пассивная Внимательность 16; языков нет.", "Small unaligned Beast. Speed 10 ft., Fly 60 ft. Perception +6; passive Perception 16; no languages."), [pack,
      p("Клюв: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) колющего урона, либо 6 (1d8 + 2), если у цели осталось не больше половины максимума хитов.", "Beak: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Piercing damage, or 6 (1d8 + 2) if the target is Bloodied (at half its Hit Point maximum or lower)."),
    ]),
  animal("camel", "Верблюд", "Camel", 346, 10, 17, "2d10 + 6", [15,8,17,2,11,5], "1/8",
    p("Большой Зверь, без мировоззрения. Скорость 50 фт. Спасбросок Телосложения +5. Тёмное зрение 60 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 50 ft. Constitution save +5. Darkvision 60 ft.; passive Perception 10; no languages."), [
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) дробящего урона.", "Bite: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Bludgeoning damage."),
    ]),
  animal("constrictor-snake", "Удав", "Constrictor Snake", 346, 13, 13, "2d10 + 2", [15,14,12,1,10,3], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2, Скрытность +4. Слепое зрение 10 фт.; пассивная Внимательность 12; языков нет.", "Large unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2, Stealth +4. Blindsight 10 ft.; passive Perception 12; no languages."), [
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 6 (1d8 + 2) колющего урона.", "Bite: melee attack +4, reach 5 ft.; 6 (1d8 + 2) Piercing damage."),
      p("Сдавливание: одно видимое существо Среднего или меньшего размера в 5 фт. делает спасбросок Силы Сл 12. Провал: 7 (3d4) дробящего урона и Схвачено, Сл высвобождения 12.", "Constrict: one visible Medium or smaller creature within 5 ft. makes a DC 12 Strength save. Failure: 7 (3d4) Bludgeoning damage and Grappled, escape DC 12."),
    ]),
  animal("crocodile", "Крокодил", "Crocodile", 347, 12, 13, "2d10 + 2", [15,10,13,2,10,5], "1/2",
    p("Большой Зверь, без мировоззрения. Скорость 20 фт., Плавание 30 фт. Спасбросок Телосложения +3, Скрытность +2; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 20 ft., Swim 30 ft. Constitution save +3, Stealth +2; passive Perception 10; no languages."), [
      p("Задержка дыхания: 1 час.", "Hold Breath: 1 hour."),
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 6 (1d8 + 2) колющего урона. Существо Среднего или меньшего размера Схвачено (Сл высвобождения 12) и Опутано, пока захват сохраняется.", "Bite: melee attack +4, reach 5 ft.; 6 (1d8 + 2) Piercing damage. A Medium or smaller creature is Grappled (escape DC 12) and Restrained while the grapple lasts."),
    ]),
  animal("draft-horse", "Тягловая лошадь", "Draft Horse", 347, 10, 15, "2d10 + 4", [18,10,15,2,11,7], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 40 ft.; passive Perception 10; no languages."), [
      p("Копыта: рукопашная атака +6, досягаемость 5 фт.; 6 (1d4 + 4) дробящего урона.", "Hooves: melee attack +6, reach 5 ft.; 6 (1d4 + 4) Bludgeoning damage."),
    ]),
  animal("elk", "Лось", "Elk", 348, 10, 11, "2d10", [16,10,11,2,10,6], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 50 фт. Внимательность +2; Тёмное зрение 60 фт.; пассивная Внимательность 12; языков нет.", "Large unaligned Beast. Speed 50 ft. Perception +2; Darkvision 60 ft.; passive Perception 12; no languages."), [
      p("Таран: рукопашная атака +5, досягаемость 5 фт.; 6 (1d6 + 3) дробящего урона. Если непосредственно перед попаданием лось прошёл к цели не менее 20 фт. по прямой и цель — существо Большого или меньшего размера, она получает ещё 3 (1d6) дробящего урона и Сбита с ног.", "Ram: melee attack +5, reach 5 ft.; 6 (1d6 + 3) Bludgeoning damage. If the elk moved at least 20 ft. straight toward the target immediately before the hit and the target is a Large or smaller creature, it takes another 3 (1d6) Bludgeoning damage and is Prone."),
    ]),
  animal("flying-snake", "Летающая змея", "Flying Snake", 348, 14, 5, "2d4", [4,15,11,2,12,5], "1/8",
    p("Крошечная Монструозность, без мировоззрения. Скорость 30 фт., Полёт 60 фт., Плавание 30 фт. Слепое зрение 10 фт.; пассивная Внимательность 11; языков нет.", "Tiny unaligned Monstrosity. Speed 30 ft., Fly 60 ft., Swim 30 ft. Blindsight 10 ft.; passive Perception 11; no languages."), [
      p("Облёт: вылет из досягаемости врага не провоцирует атаку.", "Flyby: flying out of an enemy's reach does not provoke an Opportunity Attack."),
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 1 колющий урон и 5 (2d4) урона ядом.", "Bite: melee attack +4, reach 5 ft.; 1 Piercing damage plus 5 (2d4) Poison damage."),
    ]),
  animal("giant-ape", "Гигантская обезьяна", "Giant Ape", 349, 12, 168, "16d12 + 64", [23,14,18,5,12,7], "7",
    p("Огромный Зверь, без мировоззрения. Скорость 40 фт., Лазание 40 фт. Атлетика +9, Внимательность +4, Выживание +4; пассивная Внимательность 14; языков нет.", "Huge unaligned Beast. Speed 40 ft., Climb 40 ft. Athletics +9, Perception +4, Survival +4; passive Perception 14; no languages."), [
      p("Мультиатака: две атаки Кулаком.", "Multiattack: two Fist attacks."),
      p("Кулак: рукопашная атака +9, досягаемость 10 фт.; 22 (3d10 + 6) дробящего урона.", "Fist: melee attack +9, reach 10 ft.; 22 (3d10 + 6) Bludgeoning damage."),
      p("Бросок валуна (перезарядка 6): в видимую точку в пределах 90 фт. Каждое существо в сфере радиусом 5 фт. вокруг точки делает спасбросок Ловкости Сл 17. Провал: 24 (7d6) дробящего урона, а существо Большого или меньшего размера Сбито с ног. Успех: только половина урона.", "Boulder Toss (Recharge 6): target a visible point within 90 ft. Each creature in a 5-foot-radius Sphere there makes a DC 17 Dexterity save. Failure: 24 (7d6) Bludgeoning damage and a Large or smaller creature is Prone. Success: half damage only."),
      p("Прыжок (бонусное действие): потратив 10 фт. перемещения, прыгните на расстояние до 30 фт.", "Leap (Bonus Action): spend 10 ft. of movement to jump up to 30 ft."),
    ], 5),
  animal("giant-bat", "Гигантская летучая мышь", "Giant Bat", 349, 13, 22, "4d10", [15,16,11,2,12,6], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 10 фт., Полёт 60 фт. Слепое зрение 120 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Speed 10 ft., Fly 60 ft. Blindsight 120 ft.; passive Perception 11; no languages."), [
      p("Укус: рукопашная атака +5, досягаемость 5 фт.; 6 (1d6 + 3) колющего урона.", "Bite: melee attack +5, reach 5 ft.; 6 (1d6 + 3) Piercing damage."),
    ]),
  animal("giant-centipede", "Гигантская многоножка", "Giant Centipede", 349, 14, 9, "2d6 + 2", [5,14,12,1,7,3], "1/4",
    p("Маленький Зверь, без мировоззрения. Скорость 30 фт., Лазание 30 фт. Слепое зрение 30 фт.; пассивная Внимательность 8; языков нет.", "Small unaligned Beast. Speed 30 ft., Climb 30 ft. Blindsight 30 ft.; passive Perception 8; no languages."), [
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) колющего урона, и цель Отравлена до начала следующего хода многоножки.", "Bite: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Piercing damage and the target is Poisoned until the start of the centipede's next turn."),
    ]),
  animal("giant-constrictor-snake", "Гигантский удав", "Giant Constrictor Snake", 350, 12, 60, "8d12 + 8", [19,14,12,1,10,3], "2",
    p("Огромный Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2; Слепое зрение 10 фт.; пассивная Внимательность 12; языков нет.", "Huge unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2; Blindsight 10 ft.; passive Perception 12; no languages."), [
      p("Мультиатака: одна атака Укусом и Сдавливание.", "Multiattack: one Bite attack and Constrict."),
      p("Укус: рукопашная атака +6, досягаемость 10 фт.; 11 (2d6 + 4) колющего урона.", "Bite: melee attack +6, reach 10 ft.; 11 (2d6 + 4) Piercing damage."),
      p("Сдавливание: одно видимое существо Большого или меньшего размера в 10 фт. делает спасбросок Силы Сл 14. Провал: 13 (2d8 + 4) дробящего урона и Схвачено, Сл высвобождения 14.", "Constrict: one visible Large or smaller creature within 10 ft. makes a DC 14 Strength save. Failure: 13 (2d8 + 4) Bludgeoning damage and Grappled, escape DC 14."),
    ]),
  animal("giant-crab", "Гигантский краб", "Giant Crab", 350, 15, 13, "3d8", [13,13,11,1,9,3], "1/8",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Скрытность +3; Слепое зрение 30 фт.; пассивная Внимательность 9; языков нет.", "Medium unaligned Beast. Speed 30 ft., Swim 30 ft. Stealth +3; Blindsight 30 ft.; passive Perception 9; no languages."), [amphibious,
      p("Клешня: рукопашная атака +3, досягаемость 5 фт.; 4 (1d6 + 1) дробящего урона. Существо Среднего или меньшего размера Схвачено одной из двух клешней, Сл высвобождения 11.", "Claw: melee attack +3, reach 5 ft.; 4 (1d6 + 1) Bludgeoning damage. A Medium or smaller creature is Grappled by one of two claws, escape DC 11."),
    ]),
];
