import type { Bilingual, RuleCreature } from "./rule-creatures";

// Independent mechanical descriptions, checked against SRD 5.1 (CC BY 4.0).
const p = (ru: string, en: string): Bilingual => ({ ru, en });
const beast = (ru: string, en: string, page: number, armorClass: number, hp: number, hitDice: string, abilities: RuleCreature["abilities"], challenge: string, profile: Bilingual, rules: Bilingual[]): RuleCreature => ({
  id: en.toLowerCase().replaceAll(" ", "-") + "-2014", edition: "2014", name: p(ru, en),
  sourceUrl: `https://www.dndbeyond.com/attachments/39j2li89/SRD5.1-CCBY4.0License.pdf#page=${page}`,
  armorClass, hp, hitDice, abilities, challenge, proficiency: Number(challenge) >= 5 ? 3 : 2,
  initiative: Math.floor((abilities[1] - 10) / 2), profile, rules,
});
const melee = (ru: string, en: string, bonus: number, reach: number, damage: string, typeRu: string, typeEn: string, targetRu = "одна цель", targetEn = "one target") => p(
  `${ru}: рукопашная атака оружием +${bonus}, досягаемость ${reach} фт., ${targetRu}; ${damage} ${typeRu} урона.`,
  `${en}: melee weapon attack +${bonus}, reach ${reach} ft., ${targetEn}; ${damage} ${typeEn} damage.`,
);
const smell = p("Острый нюх: преимущество на проверки Мудрости (Внимательность), основанные на обонянии.", "Keen Smell: advantage on Wisdom (Perception) checks relying on smell.");
const sight = p("Острое зрение: преимущество на проверки Мудрости (Внимательность), основанные на зрении.", "Keen Sight: advantage on Wisdom (Perception) checks relying on sight.");
const pack = p("Тактика стаи: преимущество на атаки по существу, если в пределах 5 фт. от него есть союзник, который не Недееспособен.", "Pack Tactics: advantage on attacks against a creature with an ally within 5 ft. of it, provided that ally is not Incapacitated.");
const breath = (duration: string, english: string) => p(`Задержка дыхания: ${duration}.`, `Hold Breath: ${english}.`);
const hearingSmell = p("Острые слух и нюх: преимущество на проверки Мудрости (Внимательность), основанные на слухе или обонянии.", "Keen Hearing and Smell: advantage on Wisdom (Perception) checks relying on hearing or smell.");
const flyby = p("Облёт: вылет из досягаемости врага не провоцирует атаки.", "Flyby: flying out of an enemy's reach does not provoke opportunity attacks.");
const grapple = (dc: number, ru: string, en: string) => p(`При попадании цель Схвачена (Сл высвобождения ${dc}) и Опутана до окончания захвата. Пока захват сохраняется, ${ru} нельзя применять к другой цели.`, `On a hit the target is Grappled (escape DC ${dc}) and Restrained until the grapple ends. While the grapple lasts, ${en} cannot be used against another target.`);
const knock = (dc: number) => p(`Если цель — существо, после попадания она делает спасбросок Силы Сл ${dc} или Сбита с ног.`, `A creature hit makes a DC ${dc} Strength save or falls Prone.`);
const amphibious = p("Амфибия: дышит воздухом и водой.", "Amphibious: breathes air and water.");
const water = p("Дышит только под водой.", "Breathes only underwater.");
const leap = p("Прыжок с места: в длину до 20 фт., в высоту до 10 фт., с разбегом или без него.", "Standing Leap: long jump up to 20 ft. and high jump up to 10 ft., with or without a running start.");
const sureFooted = p("Устойчивость: преимущество на спасброски Силы и Ловкости против эффектов, сбивающих с ног.", "Sure-Footed: advantage on Strength and Dexterity saves against effects that would knock it Prone.");
const bloodFrenzy = p("Кровавое безумие: преимущество на рукопашные атаки по существу с неполными хитами.", "Blood Frenzy: advantage on melee attacks against a creature missing any Hit Points.");
const pounce = (dc: number) => p(`Наскок: пройдя к существу не менее 20 фт. по прямой и попав Когтем в тот же ход, заставляет цель сделать спасбросок Силы Сл ${dc} или оказаться Сбитой с ног. Если цель Сбита с ног, можно бонусным действием совершить по ней один Укус.`, `Pounce: after moving at least 20 ft. straight toward a creature and hitting it with Claw on the same turn, the target makes a DC ${dc} Strength save or falls Prone. If the target is Prone, make one Bite against it as a Bonus Action.`);
export const ANIMALS_2014: RuleCreature[] = [
  beast("Лев", "Lion", 383, 12, 26, "4d10 + 4", [17,15,13,3,12,8], "1",
    p("Большой Зверь, без мировоззрения. Скорость 50 фт. Внимательность +3, Скрытность +6; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Speed 50 ft. Perception +3, Stealth +6; passive Perception 13; no languages."), [smell, pack, pounce(13),
      p("Прыжок с разбега: после разбега 10 фт. прыжок в длину до 25 фт.", "Running Leap: after a 10 ft. running start, long jump up to 25 ft."), melee("Укус", "Bite", 5, 5, "7 (1d8 + 3)", "колющего", "Piercing"), melee("Коготь", "Claw", 5, 5, "6 (1d6 + 3)", "рубящего", "Slashing")]),
  beast("Мамонт", "Mammoth", 384, 13, 126, "11d12 + 55", [24,9,21,3,11,6], "6",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 10; no languages."), [
      p("Растаптывающий натиск: пройдя к существу не менее 20 фт. по прямой и попав Бивнями в тот же ход, мамонт заставляет его сделать спасбросок Силы Сл 18 или оказаться Сбитым с ног. Если цель Сбита с ног, мамонт может бонусным действием совершить по ней одну атаку Растаптыванием.", "Trampling Charge: after moving at least 20 ft. straight toward a creature and hitting it with Gore on the same turn, the target makes a DC 18 Strength save or falls Prone. If the target is Prone, the mammoth can make one Stomp attack against it as a Bonus Action."),
      melee("Бивни", "Gore", 10, 10, "25 (4d8 + 7)", "колющего", "Piercing"), melee("Растаптывание", "Stomp", 10, 5, "29 (4d10 + 7)", "дробящего", "Bludgeoning", "одно Сбитое с ног существо", "one Prone creature")]),
  beast("Мул", "Mule", 384, 10, 11, "2d8 + 2", [14,10,13,2,10,5], "1/8",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Medium unaligned Beast. Speed 40 ft.; passive Perception 10; no languages."), [sureFooted,
      p("Вьючное животное: для расчёта грузоподъёмности считается Большим животным.", "Beast of Burden: treated as a Large animal when determining carrying capacity."), melee("Копыта", "Hooves", 2, 5, "4 (1d4 + 2)", "дробящего", "Bludgeoning")]),
  beast("Пантера", "Panther", 385, 12, 13, "3d8", [14,15,10,3,14,7], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 50 фт., Лазание 40 фт. Внимательность +4, Скрытность +6; пассивная Внимательность 14; языков нет.", "Medium unaligned Beast. Speed 50 ft., Climb 40 ft. Perception +4, Stealth +6; passive Perception 14; no languages."), [smell, pounce(12), melee("Укус", "Bite", 4, 5, "5 (1d6 + 2)", "колющего", "Piercing"), melee("Коготь", "Claw", 4, 5, "4 (1d4 + 2)", "рубящего", "Slashing")]),
  beast("Белый медведь", "Polar Bear", 386, 12, 42, "5d10 + 15", [20,10,16,2,13,7], "2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 40 фт., Плавание 30 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Natural armor. Speed 40 ft., Swim 30 ft. Perception +3; passive Perception 13; no languages."), [smell,
      p("Мультиатака: один Укус и одна атака Когтями.", "Multiattack: one Bite and one Claws attack."), melee("Укус", "Bite", 7, 5, "9 (1d8 + 5)", "колющего", "Piercing"), melee("Когти", "Claws", 7, 5, "12 (2d6 + 5)", "рубящего", "Slashing")]),
  beast("Рифовая акула", "Reef Shark", 387, 12, 22, "4d8 + 4", [14,13,13,1,10,4], "1/2",
    p("Средний Зверь, без мировоззрения. Природный доспех. Скорость 0 фт., Плавание 40 фт. Внимательность +2; Слепое зрение 30 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Natural armor. Speed 0 ft., Swim 40 ft. Perception +2; Blindsight 30 ft.; passive Perception 12; no languages."), [pack, water, melee("Укус", "Bite", 4, 5, "6 (1d8 + 2)", "колющего", "Piercing")]),
  beast("Носорог", "Rhinoceros", 388, 11, 45, "6d10 + 12", [21,8,15,2,12,6], "2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 11; no languages."), [
      p("Натиск: пройдя к цели не менее 20 фт. по прямой и попав Рогом в тот же ход, наносит ещё 9 (2d8) дробящего урона. Если цель — существо, она делает спасбросок Силы Сл 15 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Gore on the same turn, deal another 9 (2d8) Bludgeoning damage. A creature target makes a DC 15 Strength save or falls Prone."), melee("Рог", "Gore", 7, 5, "14 (2d8 + 5)", "дробящего", "Bludgeoning")]),
  beast("Саблезубый тигр", "Saber-Toothed Tiger", 388, 12, 52, "7d10 + 14", [18,14,15,3,12,8], "2",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт. Внимательность +3, Скрытность +6; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Speed 40 ft. Perception +3, Stealth +6; passive Perception 13; no languages."), [smell, pounce(14), melee("Укус", "Bite", 6, 5, "10 (1d10 + 5)", "колющего", "Piercing"), melee("Коготь", "Claw", 6, 5, "12 (2d6 + 5)", "рубящего", "Slashing")]),
  beast("Скорпион", "Scorpion", 388, 11, 1, "1d4 - 1", [2,11,8,1,8,2], "0",
    p("Крошечный Зверь, без мировоззрения. Природный доспех. Скорость 10 фт.; Слепое зрение 10 фт.; пассивная Внимательность 9; языков нет.", "Tiny unaligned Beast. Natural armor. Speed 10 ft.; Blindsight 10 ft.; passive Perception 9; no languages."), [melee("Жало", "Sting", 2, 5, "1", "колющего", "Piercing", "одно существо", "one creature"),
      p("После попадания цель делает спасбросок Телосложения Сл 9: 4 (1d8) урона ядом при провале, половина при успехе.", "After a hit the target makes a DC 9 Constitution save: 4 (1d8) Poison damage on failure, half on success.")]),
  beast("Тигр", "Tiger", 391, 12, 37, "5d10 + 10", [17,15,14,3,12,8], "1",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт. Внимательность +3, Скрытность +6; Тёмное зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Speed 40 ft. Perception +3, Stealth +6; Darkvision 60 ft.; passive Perception 13; no languages."), [smell, pounce(13), melee("Укус", "Bite", 5, 5, "8 (1d10 + 3)", "колющего", "Piercing"), melee("Коготь", "Claw", 5, 5, "7 (1d8 + 3)", "рубящего", "Slashing")]),
  beast("Стервятник", "Vulture", 392, 10, 5, "1d8 + 1", [7,10,13,2,12,4], "0",
    p("Средний Зверь, без мировоззрения. Скорость 10 фт., Полёт 50 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 10 ft., Fly 50 ft. Perception +3; passive Perception 13; no languages."), [pack,
      p("Острые зрение и нюх: преимущество на проверки Мудрости (Внимательность), основанные на зрении или обонянии.", "Keen Sight and Smell: advantage on Wisdom (Perception) checks relying on sight or smell."), melee("Клюв", "Beak", 2, 5, "2 (1d4)", "колющего", "Piercing")]),
  beast("Волк", "Wolf", 393, 13, 11, "2d8 + 2", [12,15,12,3,12,6], "1/4",
    p("Средний Зверь, без мировоззрения. Природный доспех. Скорость 40 фт. Внимательность +3, Скрытность +4; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Natural armor. Speed 40 ft. Perception +3, Stealth +4; passive Perception 13; no languages."), [hearingSmell, pack, melee("Укус", "Bite", 4, 5, "7 (2d4 + 2)", "колющего", "Piercing"), knock(11)]),
  beast("Гигантская ядовитая змея", "Giant Poisonous Snake", 378, 14, 11, "2d8 + 2", [10,18,13,2,10,3], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2; Слепое зрение 10 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2; Blindsight 10 ft.; passive Perception 12; no languages."), [melee("Укус", "Bite", 6, 10, "6 (1d4 + 4)", "колющего", "Piercing"),
      p("После попадания цель делает спасбросок Телосложения Сл 11: 10 (3d6) урона ядом при провале, половина при успехе.", "After a hit the target makes a DC 11 Constitution save: 10 (3d6) Poison damage on failure, half on success."),
    ]),
  beast("Гигантский морской конёк", "Giant Sea Horse", 378, 13, 16, "3d10", [12,15,11,2,12,5], "1/2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 0 фт., Плавание 40 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Natural armor. Speed 0 ft., Swim 40 ft.; passive Perception 11; no languages."), [water,
      p("Натиск: если конёк прошёл к цели не менее 20 фт. по прямой и попал Тараном в тот же ход, цель получает ещё 7 (2d6) дробящего урона. Если цель — существо, она делает спасбросок Силы Сл 11 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Ram on the same turn, deal another 7 (2d6) Bludgeoning damage. A creature target makes a DC 11 Strength save or falls Prone."), melee("Таран", "Ram", 3, 5, "4 (1d6 + 1)", "дробящего", "Bludgeoning"),
    ]),
  beast("Гигантская акула", "Giant Shark", 379, 13, 126, "11d12 + 55", [23,11,21,1,10,5], "5",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 0 фт., Плавание 50 фт. Внимательность +3; Слепое зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Huge unaligned Beast. Natural armor. Speed 0 ft., Swim 50 ft. Perception +3; Blindsight 60 ft.; passive Perception 13; no languages."), [bloodFrenzy, water, melee("Укус", "Bite", 9, 5, "22 (3d10 + 6)", "колющего", "Piercing")]),
  beast("Гигантская жаба", "Giant Toad", 380, 11, 39, "6d10 + 6", [15,13,13,2,10,3], "1",
    p("Большой Зверь, без мировоззрения. Скорость 20 фт., Плавание 40 фт.; Тёмное зрение 30 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 20 ft., Swim 40 ft.; Darkvision 30 ft.; passive Perception 10; no languages."), [amphibious, leap,
      p("Укус: рукопашная атака оружием +4, досягаемость 5 фт., одна цель; 7 (1d10 + 2) колющего урона и 5 (1d10) урона ядом.", "Bite: melee weapon attack +4, reach 5 ft., one target; 7 (1d10 + 2) Piercing plus 5 (1d10) Poison damage."), grapple(13, "Укус", "Bite"),
      p("Проглатывание: совершите один Укус по схваченной цели Среднего или меньшего размера. При попадании цель проглочена, захват прекращается; она Ослеплена и Опутана, имеет полное укрытие от атак и эффектов снаружи и получает 10 (3d6) урона кислотой в начале каждого хода жабы. Одновременно проглочена только одна цель. После смерти жабы цель больше не Опутана ею и может выйти из трупа, потратив 5 фт. перемещения, Сбитой с ног.", "Swallow: make one Bite attack against a Medium or smaller grappled target. On a hit it is swallowed and the grapple ends. It is Blinded and Restrained, has total cover against attacks and effects outside, and takes 10 (3d6) Acid damage at the start of each of the toad's turns. Only one target can be swallowed at a time. If the toad dies, the target is no longer Restrained by it and can leave the corpse by spending 5 ft. of movement, exiting Prone."),
    ]),
  beast("Гигантский стервятник", "Giant Vulture", 380, 10, 22, "3d10 + 6", [15,10,15,6,12,7], "1",
    p("Большой Зверь, нейтрально-злой. Скорость 10 фт., Полёт 60 фт. Внимательность +3; пассивная Внимательность 13. Понимает Общий, но не говорит.", "Large Neutral Evil Beast. Speed 10 ft., Fly 60 ft. Perception +3; passive Perception 13. Understands Common but cannot speak."), [pack,
      p("Острые зрение и нюх: преимущество на проверки Мудрости (Внимательность), основанные на зрении или обонянии.", "Keen Sight and Smell: advantage on Wisdom (Perception) checks relying on sight or smell."),
      p("Мультиатака: одна атака Клювом и одна Когтями.", "Multiattack: one Beak and one Talons attack."), melee("Клюв", "Beak", 4, 5, "7 (2d4 + 2)", "колющего", "Piercing"), melee("Когти", "Talons", 4, 5, "9 (2d6 + 2)", "рубящего", "Slashing"),
    ]),
  beast("Гигантская ласка", "Giant Weasel", 381, 13, 9, "2d8", [11,16,10,4,12,5], "1/8",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт. Внимательность +3, Скрытность +5; Тёмное зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 40 ft. Perception +3, Stealth +5; Darkvision 60 ft.; passive Perception 13; no languages."), [hearingSmell, melee("Укус", "Bite", 5, 5, "5 (1d4 + 3)", "колющего", "Piercing")]),
  beast("Гигантский паук-волк", "Giant Wolf Spider", 381, 13, 11, "2d8 + 2", [12,16,13,3,12,4], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт., Лазание 40 фт. Внимательность +3, Скрытность +7; Слепое зрение 10 фт., Тёмное зрение 60 фт.; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 40 ft., Climb 40 ft. Perception +3, Stealth +7; Blindsight 10 ft., Darkvision 60 ft.; passive Perception 13; no languages."), [
      p("Паучье лазание: преодолевает сложные поверхности, включая потолки, без проверки характеристики. Чувство паутины: касаясь паутины, знает точное положение других существ на той же паутине. Хождение по паутине: игнорирует ограничения перемещения от паутины.", "Spider Climb: climbs difficult surfaces, including ceilings, without an ability check. Web Sense: while touching a web, knows the exact location of other creatures touching the same web. Web Walker: ignores movement restrictions caused by webbing."),
      melee("Укус", "Bite", 3, 5, "4 (1d6 + 1)", "колющего", "Piercing", "одно существо", "one creature"),
      p("После попадания цель делает спасбросок Телосложения Сл 11: 7 (2d6) урона ядом при провале, половина при успехе. Если урон ядом снижает её до 0 хитов, она стабильна, но Отравлена 1 час, даже после восстановления хитов, и Парализована, пока Отравлена таким образом.", "After a hit the target makes a DC 11 Constitution save: 7 (2d6) Poison damage on failure, half on success. If the Poison damage reduces it to 0 Hit Points, it is stable but Poisoned for 1 hour, even after regaining Hit Points, and Paralyzed while Poisoned this way."),
    ]),
  beast("Коза", "Goat", 381, 10, 4, "1d8", [12,10,11,2,10,5], "0",
    p("Средний Зверь, без мировоззрения. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Medium unaligned Beast. Speed 40 ft.; passive Perception 10; no languages."), [sureFooted,
      p("Натиск: если коза прошла к цели не менее 20 фт. по прямой и попала Тараном в тот же ход, цель получает ещё 2 (1d4) дробящего урона. Если цель — существо, она делает спасбросок Силы Сл 10 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Ram on the same turn, deal another 2 (1d4) Bludgeoning damage. A creature target makes a DC 10 Strength save or falls Prone."), melee("Таран", "Ram", 3, 5, "3 (1d4 + 1)", "дробящего", "Bludgeoning"),
    ]),
  beast("Акула-охотник", "Hunter Shark", 382, 12, 45, "6d10 + 12", [18,13,15,1,10,4], "2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 0 фт., Плавание 40 фт. Внимательность +2; Слепое зрение 30 фт.; пассивная Внимательность 12; языков нет.", "Large unaligned Beast. Natural armor. Speed 0 ft., Swim 40 ft. Perception +2; Blindsight 30 ft.; passive Perception 12; no languages."), [bloodFrenzy, water, melee("Укус", "Bite", 6, 5, "13 (2d8 + 4)", "колющего", "Piercing")]),
  beast("Гиена", "Hyena", 382, 11, 5, "1d8 + 1", [11,13,12,2,12,5], "0",
    p("Средний Зверь, без мировоззрения. Скорость 50 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 50 ft. Perception +3; passive Perception 13; no languages."), [pack, melee("Укус", "Bite", 2, 5, "3 (1d6)", "колющего", "Piercing")]),
  beast("Шакал", "Jackal", 382, 12, 3, "1d6", [8,15,11,3,12,6], "0",
    p("Маленький Зверь, без мировоззрения. Скорость 40 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Small unaligned Beast. Speed 40 ft. Perception +3; passive Perception 13; no languages."), [hearingSmell, pack, melee("Укус", "Bite", 1, 5, "1 (1d4 - 1)", "колющего", "Piercing")]),
  beast("Косатка", "Killer Whale", 383, 12, 90, "12d12 + 12", [19,10,13,3,12,7], "3",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 0 фт., Плавание 60 фт. Внимательность +3; Слепое зрение 120 фт.; пассивная Внимательность 13; языков нет.", "Huge unaligned Beast. Natural armor. Speed 0 ft., Swim 60 ft. Perception +3; Blindsight 120 ft.; passive Perception 13; no languages."), [breath("30 минут", "30 minutes"),
      p("Эхолокация: Слепое зрение недоступно в состоянии Оглохший. Острый слух: преимущество на проверки Мудрости (Внимательность), основанные на слухе.", "Echolocation: Blindsight is unavailable while Deafened. Keen Hearing: advantage on Wisdom (Perception) checks relying on hearing."), melee("Укус", "Bite", 6, 5, "21 (5d6 + 4)", "колющего", "Piercing"),
    ]),
  beast("Гигантский удав", "Giant Constrictor Snake", 374, 12, 60, "8d12 + 8", [19,14,12,1,10,3], "2",
    p("Огромный Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2; Слепое зрение 10 фт.; пассивная Внимательность 12; языков нет.", "Huge unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2; Blindsight 10 ft.; passive Perception 12; no languages."), [
      melee("Укус", "Bite", 6, 10, "11 (2d6 + 4)", "колющего", "Piercing", "одно существо", "one creature"),
      melee("Сдавливание", "Constrict", 6, 5, "13 (2d8 + 4)", "дробящего", "Bludgeoning", "одно существо", "one creature"), grapple(16, "Сдавливание", "Constrict"),
    ]),
  beast("Гигантский краб", "Giant Crab", 374, 15, 13, "3d8", [13,15,11,1,9,3], "1/8",
    p("Средний Зверь, без мировоззрения. Природный доспех. Скорость 30 фт., Плавание 30 фт. Скрытность +4; Слепое зрение 30 фт.; пассивная Внимательность 9; языков нет.", "Medium unaligned Beast. Natural armor. Speed 30 ft., Swim 30 ft. Stealth +4; Blindsight 30 ft.; passive Perception 9; no languages."), [amphibious,
      melee("Клешня", "Claw", 3, 5, "4 (1d6 + 1)", "дробящего", "Bludgeoning"),
      p("Попав Клешнёй, краб хватает цель (Сл высвобождения 11). Каждая из двух клешней может удерживать только одну цель.", "A Claw hit grapples the target (escape DC 11). Each of the two claws can grapple only one target."),
    ]),
  beast("Гигантский крокодил", "Giant Crocodile", 374, 14, 85, "9d12 + 27", [21,9,17,2,10,7], "5",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 30 фт., Плавание 50 фт. Скрытность +5; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Natural armor. Speed 30 ft., Swim 50 ft. Stealth +5; passive Perception 10; no languages."), [breath("30 минут", "30 minutes"),
      p("Мультиатака: один Укус и одна атака Хвостом.", "Multiattack: one Bite and one Tail attack."), melee("Укус", "Bite", 8, 5, "21 (3d10 + 5)", "колющего", "Piercing"), grapple(16, "Укус", "Bite"),
      melee("Хвост", "Tail", 8, 10, "14 (2d8 + 5)", "дробящего", "Bludgeoning", "одна цель, не схваченная крокодилом", "one target not grappled by the crocodile"), knock(16),
    ]),
  beast("Гигантский орёл", "Giant Eagle", 375, 13, 26, "4d10 + 4", [16,17,13,8,14,10], "1",
    p("Большой Зверь, нейтрально-добрый. Скорость 10 фт., Полёт 80 фт. Внимательность +4; пассивная Внимательность 14. Язык гигантских орлов; понимает Общий и Воздушный, но не говорит на них.", "Large Neutral Good Beast. Speed 10 ft., Fly 80 ft. Perception +4; passive Perception 14. Giant Eagle; understands Common and Auran but cannot speak them."), [sight,
      p("Мультиатака: одна атака Клювом и одна Когтями.", "Multiattack: one Beak and one Talons attack."), melee("Клюв", "Beak", 5, 5, "6 (1d6 + 3)", "колющего", "Piercing"), melee("Когти", "Talons", 5, 5, "10 (2d6 + 3)", "рубящего", "Slashing"),
    ]),
  beast("Гигантский лось", "Giant Elk", 375, 14, 42, "5d12 + 10", [19,16,14,7,14,10], "2",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 60 фт. Внимательность +4; пассивная Внимательность 14. Язык гигантских лосей; понимает Общий, Эльфийский и Сильван, но не говорит на них.", "Huge unaligned Beast. Natural armor. Speed 60 ft. Perception +4; passive Perception 14. Giant Elk; understands Common, Elvish and Sylvan but cannot speak them."), [
      p("Натиск: если лось прошёл к цели не менее 20 фт. по прямой и попал Тараном в тот же ход, цель получает ещё 7 (2d6) урона. Если цель — существо, она делает спасбросок Силы Сл 14 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Ram on the same turn, deal another 7 (2d6) damage. A creature target makes a DC 14 Strength save or falls Prone."),
      melee("Таран", "Ram", 6, 10, "11 (2d6 + 4)", "дробящего", "Bludgeoning"), melee("Копыта", "Hooves", 6, 5, "22 (4d8 + 4)", "дробящего", "Bludgeoning", "одно Сбитое с ног существо", "one Prone creature"),
    ]),
  beast("Гигантский огненный жук", "Giant Fire Beetle", 375, 13, 4, "1d6 + 1", [8,10,12,1,7,3], "0",
    p("Маленький Зверь, без мировоззрения. Природный доспех. Скорость 30 фт.; Слепое зрение 30 фт.; пассивная Внимательность 8; языков нет.", "Small unaligned Beast. Natural armor. Speed 30 ft.; Blindsight 30 ft.; passive Perception 8; no languages."), [
      p("Свечение: яркий свет в радиусе 10 фт. и тусклый ещё на 10 фт. Светящиеся железы продолжают светиться 1d6 дней после смерти жука.", "Illumination: bright light in a 10-foot radius and dim light for another 10 ft. The glowing glands continue shining for 1d6 days after death."), melee("Укус", "Bite", 1, 5, "2 (1d6 - 1)", "рубящего", "Slashing"),
    ]),
  beast("Гигантская лягушка", "Giant Frog", 376, 11, 18, "4d8", [12,13,11,2,10,3], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт. Внимательность +2, Скрытность +3; Тёмное зрение 30 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 30 ft., Swim 30 ft. Perception +2, Stealth +3; Darkvision 30 ft.; passive Perception 12; no languages."), [amphibious, leap,
      melee("Укус", "Bite", 3, 5, "4 (1d6 + 1)", "колющего", "Piercing"), grapple(11, "Укус", "Bite"),
      p("Проглатывание: совершите одну атаку Укусом по схваченной цели Маленького или меньшего размера. При попадании цель проглочена, захват прекращается; она Ослеплена и Опутана, имеет полное укрытие от атак и эффектов снаружи и получает 5 (2d4) урона кислотой в начале каждого хода лягушки. Одновременно проглочена только одна цель. После смерти лягушки цель больше не Опутана ею и может выйти из трупа, потратив 5 фт. перемещения, Сбитой с ног.", "Swallow: make one Bite attack against a Small or smaller grappled target. On a hit it is swallowed and the grapple ends. It is Blinded and Restrained, has total cover against attacks and effects outside, and takes 5 (2d4) Acid damage at the start of each of the frog's turns. Only one target can be swallowed at a time. If the frog dies, the target is no longer Restrained by it and can leave the corpse by spending 5 ft. of movement, exiting Prone."),
    ]),
  beast("Гигантская коза", "Giant Goat", 376, 11, 19, "3d10 + 3", [17,11,12,3,12,6], "1/2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 11; no languages."), [sureFooted,
      p("Натиск: если коза прошла к цели не менее 20 фт. по прямой и попала Тараном в тот же ход, цель получает ещё 5 (2d4) дробящего урона. Если цель — существо, она делает спасбросок Силы Сл 13 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Ram on the same turn, deal another 5 (2d4) Bludgeoning damage. A creature target makes a DC 13 Strength save or falls Prone."), melee("Таран", "Ram", 5, 5, "8 (2d4 + 3)", "дробящего", "Bludgeoning"),
    ]),
  beast("Гигантская гиена", "Giant Hyena", 376, 12, 45, "6d10 + 12", [16,14,14,2,12,7], "1",
    p("Большой Зверь, без мировоззрения. Скорость 50 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Speed 50 ft. Perception +3; passive Perception 13; no languages."), [
      p("Буйство: снизив существо до 0 хитов рукопашной атакой в свой ход, гиена может бонусным действием пройти до половины своей скорости и совершить один Укус.", "Rampage: after reducing a creature to 0 Hit Points with a melee attack on its turn, the hyena can use a bonus action to move up to half its speed and make one Bite attack."), melee("Укус", "Bite", 5, 5, "10 (2d6 + 3)", "колющего", "Piercing"),
    ]),
  beast("Гигантская ящерица", "Giant Lizard", 377, 12, 19, "3d10 + 3", [15,12,13,2,10,5], "1/4",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 30 фт., Лазание 30 фт.; Тёмное зрение 30 фт.; пассивная Внимательность 10; языков нет. Может служить ездовым или тягловым животным.", "Large unaligned Beast. Natural armor. Speed 30 ft., Climb 30 ft.; Darkvision 30 ft.; passive Perception 10; no languages. Can be used as a mount or draft animal."), [melee("Укус", "Bite", 4, 5, "6 (1d8 + 2)", "колющего", "Piercing")]),
  beast("Гигантский осьминог", "Giant Octopus", 377, 11, 52, "8d10 + 8", [17,13,13,4,10,4], "1",
    p("Большой Зверь, без мировоззрения. Скорость 10 фт., Плавание 60 фт. Внимательность +4, Скрытность +5; Тёмное зрение 60 фт.; пассивная Внимательность 14; языков нет.", "Large unaligned Beast. Speed 10 ft., Swim 60 ft. Perception +4, Stealth +5; Darkvision 60 ft.; passive Perception 14; no languages."), [water, breath("1 час вне воды", "1 hour outside water"),
      p("Подводный камуфляж: преимущество на проверки Ловкости (Скрытность) под водой.", "Underwater Camouflage: advantage on Dexterity (Stealth) checks underwater."),
      melee("Щупальца", "Tentacles", 5, 15, "10 (2d6 + 3)", "дробящего", "Bludgeoning"),
      p("При попадании по существу оно Схвачено (Сл высвобождения 16) и Опутано до окончания захвата. Пока захват сохраняется, щупальца нельзя применять к другой цели.", "A creature hit is Grappled (escape DC 16) and Restrained until the grapple ends. While the grapple lasts, Tentacles cannot be used against another target."),
      p("Чернильное облако (действие, восстановление после короткого или долгого отдыха): под водой выпустите вокруг себя облако чернил радиусом 20 фт. Область сильно заслонена на 1 минуту; сильное течение может рассеять чернила. После выпуска чернил можно бонусным действием совершить Рывок.", "Ink Cloud (action, recharges after a short or long rest): underwater, release ink in a 20-foot radius around yourself. The area is heavily obscured for 1 minute; a significant current can disperse it. After releasing the ink, you can Dash as a bonus action."),
    ]),
  beast("Гигантская сова", "Giant Owl", 377, 12, 19, "3d10 + 3", [13,15,12,8,13,10], "1/4",
    p("Большой Зверь, нейтральный. Скорость 5 фт., Полёт 60 фт. Внимательность +5, Скрытность +4; Тёмное зрение 120 фт.; пассивная Внимательность 15. Язык гигантских сов; понимает Общий, Эльфийский и Сильван, но не говорит на них.", "Large Neutral Beast. Speed 5 ft., Fly 60 ft. Perception +5, Stealth +4; Darkvision 120 ft.; passive Perception 15. Giant Owl; understands Common, Elvish and Sylvan but cannot speak them."), [flyby,
      p("Острые слух и зрение: преимущество на проверки Мудрости (Внимательность), основанные на слухе или зрении.", "Keen Hearing and Sight: advantage on Wisdom (Perception) checks relying on hearing or sight."), melee("Когти", "Talons", 3, 5, "8 (2d6 + 1)", "рубящего", "Slashing"),
    ]),
  beast("Удав", "Constrictor Snake", 369, 12, 13, "2d10 + 2", [15,14,12,1,10,3], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 30 фт., Плавание 30 фт.; Слепое зрение 10 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 30 ft., Swim 30 ft.; Blindsight 10 ft.; passive Perception 10; no languages."), [
      melee("Укус", "Bite", 4, 5, "5 (1d6 + 2)", "колющего", "Piercing", "одно существо", "one creature"),
      melee("Сдавливание", "Constrict", 4, 5, "6 (1d8 + 2)", "дробящего", "Bludgeoning", "одно существо", "one creature"), grapple(14, "Сдавливание", "Constrict"),
    ]),
  beast("Крокодил", "Crocodile", 370, 12, 19, "3d10 + 3", [15,10,13,2,10,5], "1/2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 20 фт., Плавание 30 фт. Скрытность +2; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Natural armor. Speed 20 ft., Swim 30 ft. Stealth +2; passive Perception 10; no languages."), [breath("15 минут", "15 minutes"),
      melee("Укус", "Bite", 4, 5, "7 (1d10 + 2)", "колющего", "Piercing", "одно существо", "one creature"), grapple(12, "Укус", "Bite"),
    ]),
  beast("Олень", "Deer", 370, 13, 4, "1d8", [11,16,11,2,14,5], "0",
    p("Средний Зверь, без мировоззрения. Скорость 50 фт.; пассивная Внимательность 12; языков нет.", "Medium unaligned Beast. Speed 50 ft.; passive Perception 12; no languages."), [melee("Укус", "Bite", 2, 5, "2 (1d4)", "колющего", "Piercing")]),
  beast("Лютый волк", "Dire Wolf", 371, 14, 37, "5d10 + 10", [17,15,15,3,12,7], "1",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 50 фт. Внимательность +3, Скрытность +4; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Natural armor. Speed 50 ft. Perception +3, Stealth +4; passive Perception 13; no languages."), [hearingSmell, pack, melee("Укус", "Bite", 5, 5, "10 (2d6 + 3)", "колющего", "Piercing"), knock(13)]),
  beast("Тягловая лошадь", "Draft Horse", 371, 10, 19, "3d10 + 3", [18,10,12,2,11,7], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 40 ft.; passive Perception 10; no languages."), [melee("Копыта", "Hooves", 6, 5, "9 (2d4 + 4)", "дробящего", "Bludgeoning")]),
  beast("Орёл", "Eagle", 371, 12, 3, "1d6", [6,15,10,2,14,7], "0",
    p("Маленький Зверь, без мировоззрения. Скорость 10 фт., Полёт 60 фт. Внимательность +4; пассивная Внимательность 14; языков нет.", "Small unaligned Beast. Speed 10 ft., Fly 60 ft. Perception +4; passive Perception 14; no languages."), [sight, melee("Когти", "Talons", 4, 5, "4 (1d4 + 2)", "рубящего", "Slashing")]),
  beast("Слон", "Elephant", 371, 12, 76, "8d12 + 24", [22,9,17,3,11,6], "4",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 10; no languages."), [
      p("Растаптывающий натиск: если слон прошёл к существу не менее 20 фт. по прямой и попал Бивнями в тот же ход, цель делает спасбросок Силы Сл 12 или Сбита с ног. Если цель Сбита с ног, слон может бонусным действием совершить по ней одну атаку Топотом.", "Trampling Charge: after moving at least 20 ft. straight toward a creature and hitting it with Gore on the same turn, the target makes a DC 12 Strength save or falls Prone. If the target is Prone, the elephant can make one Stomp attack against it as a bonus action."),
      melee("Бивни", "Gore", 8, 5, "19 (3d8 + 6)", "колющего", "Piercing"), melee("Топот", "Stomp", 8, 5, "22 (3d10 + 6)", "дробящего", "Bludgeoning", "одно Сбитое с ног существо", "one Prone creature"),
    ]),
  beast("Летающая змея", "Flying Snake", 372, 14, 5, "2d4", [4,18,11,2,12,5], "1/8",
    p("Крошечный Зверь, без мировоззрения. Скорость 30 фт., Полёт 60 фт., Плавание 30 фт.; Слепое зрение 10 фт.; пассивная Внимательность 11; языков нет.", "Tiny unaligned Beast. Speed 30 ft., Fly 60 ft., Swim 30 ft.; Blindsight 10 ft.; passive Perception 11; no languages."), [flyby,
      p("Укус: рукопашная атака оружием +6, досягаемость 5 фт., одна цель; 1 колющий урон и 7 (3d4) урона ядом.", "Bite: melee weapon attack +6, reach 5 ft., one target; 1 Piercing plus 7 (3d4) Poison damage."),
    ]),
  beast("Гигантская обезьяна", "Giant Ape", 373, 12, 157, "15d12 + 60", [23,14,18,7,12,7], "7",
    p("Огромный Зверь, без мировоззрения. Скорость 40 фт., Лазание 40 фт. Атлетика +9, Внимательность +4; пассивная Внимательность 14; языков нет.", "Huge unaligned Beast. Speed 40 ft., Climb 40 ft. Athletics +9, Perception +4; passive Perception 14; no languages."), [
      p("Мультиатака: две атаки Кулаком.", "Multiattack: two Fist attacks."), melee("Кулак", "Fist", 9, 10, "22 (3d10 + 6)", "дробящего", "Bludgeoning"),
      p("Камень: дальнобойная атака оружием +9, дистанция 50/100 фт., одна цель; 30 (7d6 + 6) дробящего урона.", "Rock: ranged weapon attack +9, range 50/100 ft., one target; 30 (7d6 + 6) Bludgeoning damage."),
    ]),
  beast("Гигантский барсук", "Giant Badger", 373, 10, 13, "2d8 + 4", [13,10,15,2,12,5], "1/4",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Копание 10 фт.; Тёмное зрение 30 фт.; пассивная Внимательность 11; языков нет.", "Medium unaligned Beast. Speed 30 ft., Burrow 10 ft.; Darkvision 30 ft.; passive Perception 11; no languages."), [smell,
      p("Мультиатака: один Укус и одна атака Когтями.", "Multiattack: one Bite and one Claws attack."), melee("Укус", "Bite", 3, 5, "4 (1d6 + 1)", "колющего", "Piercing"), melee("Когти", "Claws", 3, 5, "6 (2d4 + 1)", "рубящего", "Slashing"),
    ]),
  beast("Гигантская летучая мышь", "Giant Bat", 373, 13, 22, "4d10", [15,16,11,2,12,6], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 10 фт., Полёт 60 фт.; Слепое зрение 60 фт.; пассивная Внимательность 11; языков нет.", "Large unaligned Beast. Speed 10 ft., Fly 60 ft.; Blindsight 60 ft.; passive Perception 11; no languages."), [
      p("Эхолокация: Слепое зрение недоступно в состоянии Оглохший. Острый слух: преимущество на проверки Мудрости (Внимательность), основанные на слухе.", "Echolocation: Blindsight is unavailable while Deafened. Keen Hearing: advantage on Wisdom (Perception) checks relying on hearing."),
      melee("Укус", "Bite", 4, 5, "5 (1d6 + 2)", "колющего", "Piercing", "одно существо", "one creature"),
    ]),
  beast("Гигантский кабан", "Giant Boar", 373, 12, 42, "5d10 + 15", [17,10,16,2,7,5], "2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 8; языков нет.", "Large unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 8; no languages."), [
      p("Натиск: если кабан прошёл к цели не менее 20 фт. по прямой и попал Клыком в тот же ход, цель получает ещё 7 (2d6) рубящего урона. Если цель — существо, она делает спасбросок Силы Сл 13 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Tusk on the same turn, deal another 7 (2d6) Slashing damage. A creature target makes a DC 13 Strength save or falls Prone."),
      p("Неукротимость (восстановление после короткого или долгого отдыха): если 10 урона или меньше должны снизить кабана до 0 хитов, вместо этого остаётся 1 хит.", "Relentless (recharges after a short or long rest): if damage of 10 or less would reduce the boar to 0 Hit Points, it drops to 1 instead."), melee("Клык", "Tusk", 5, 5, "10 (2d6 + 3)", "рубящего", "Slashing"),
    ]),
  beast("Плезиозавр", "Plesiosaurus", 279, 13, 68, "8d10 + 24", [18,15,16,2,12,5], "2",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 20 фт., Плавание 40 фт. Внимательность +3, Скрытность +4; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Natural armor. Speed 20 ft., Swim 40 ft. Perception +3, Stealth +4; passive Perception 13; no languages."), [breath("1 час", "1 hour"), melee("Укус", "Bite", 6, 10, "14 (3d6 + 4)", "колющего", "Piercing")]),
  beast("Трицератопс", "Triceratops", 279, 13, 95, "10d12 + 30", [22,9,17,2,11,5], "5",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 50 фт.; пассивная Внимательность 10; языков нет.", "Huge unaligned Beast. Natural armor. Speed 50 ft.; passive Perception 10; no languages."), [
      p("Растаптывающий натиск: если трицератопс прошёл к существу не менее 20 фт. по прямой и попал Рогами в тот же ход, цель делает спасбросок Силы Сл 13 или Сбита с ног. Если цель Сбита с ног, трицератопс может бонусным действием совершить по ней одну атаку Топотом.", "Trampling Charge: after moving at least 20 ft. straight toward a creature and hitting it with Gore on the same turn, the target makes a DC 13 Strength save or falls Prone. If the target is Prone, the triceratops can make one Stomp attack against it as a bonus action."),
      melee("Рога", "Gore", 9, 5, "24 (4d8 + 6)", "колющего", "Piercing"),
      melee("Топот", "Stomp", 9, 5, "22 (3d10 + 6)", "дробящего", "Bludgeoning", "одно Сбитое с ног существо", "one Prone creature"),
    ]),
  beast("Тираннозавр", "Tyrannosaurus Rex", 279, 13, 136, "13d12 + 52", [25,10,19,2,12,9], "8",
    p("Огромный Зверь, без мировоззрения. Природный доспех. Скорость 50 фт. Внимательность +4; пассивная Внимательность 14; языков нет.", "Huge unaligned Beast. Natural armor. Speed 50 ft. Perception +4; passive Perception 14; no languages."), [
      p("Мультиатака: один Укус и одна атака Хвостом по разным целям.", "Multiattack: one Bite and one Tail attack against different targets."),
      melee("Укус", "Bite", 10, 10, "33 (4d12 + 7)", "колющего", "Piercing"),
      p("Попав Укусом по существу Среднего или меньшего размера, тираннозавр хватает его (Сл высвобождения 17). До окончания захвата цель Опутана, а тираннозавр не может кусать другую цель.", "A Bite hit grapples a Medium or smaller creature (escape DC 17). Until the grapple ends, the target is Restrained and the tyrannosaurus cannot bite another target."),
      melee("Хвост", "Tail", 10, 10, "20 (3d8 + 7)", "дробящего", "Bludgeoning"),
    ]),
  beast("Кровопийца", "Stirge", 349, 14, 2, "1d4", [4,16,11,2,8,6], "1/8",
    p("Крошечный Зверь, без мировоззрения. Природный доспех. Скорость 10 фт., Полёт 40 фт. Тёмное зрение 60 фт.; пассивная Внимательность 9; языков нет.", "Tiny unaligned Beast. Natural armor. Speed 10 ft., Fly 40 ft. Darkvision 60 ft.; passive Perception 9; no languages."), [
      melee("Высасывание крови", "Blood Drain", 5, 5, "5 (1d4 + 3)", "колющего", "Piercing", "одно существо", "one creature"),
      p("При попадании кровопийца прикрепляется к цели. Пока прикреплён, он не атакует; вместо этого в начале каждого своего хода цель теряет 5 (1d4 + 3) хитов из-за кровопотери. Можно отцепиться, потратив 5 фт. перемещения; кровопийца делает это, высосав 10 хитов или после смерти цели. Любое существо, включая цель, может действием отцепить кровопийцу.", "On a hit the stirge attaches to the target. While attached it does not attack; instead, at the start of each of its turns the target loses 5 (1d4 + 3) Hit Points to blood loss. It can detach by spending 5 ft. of movement, and does so after draining 10 Hit Points or when the target dies. Any creature, including the target, can use an action to detach it."),
    ]),
  beast("Человекообразная обезьяна", "Ape", 366, 12, 19, "3d8 + 6", [16,14,14,6,12,7], "1/2",
    p("Средний Зверь, без мировоззрения. Скорость 30 фт., Лазание 30 фт. Атлетика +5, Внимательность +3; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Speed 30 ft., Climb 30 ft. Athletics +5, Perception +3; passive Perception 13; no languages."), [
      p("Мультиатака: две атаки Кулаком.", "Multiattack: two Fist attacks."), melee("Кулак", "Fist", 5, 5, "6 (1d6 + 3)", "дробящего", "Bludgeoning"),
      p("Камень: дальнобойная атака оружием +5, дистанция 25/50 фт., одна цель; 6 (1d6 + 3) дробящего урона.", "Rock: ranged weapon attack +5, range 25/50 ft., one target; 6 (1d6 + 3) Bludgeoning damage."),
    ]),
  beast("Топороклюв", "Axe Beak", 366, 11, 19, "3d10 + 3", [14,12,12,2,10,5], "1/4",
    p("Большой Зверь, без мировоззрения. Скорость 50 фт.; пассивная Внимательность 10; языков нет.", "Large unaligned Beast. Speed 50 ft.; passive Perception 10; no languages."), [melee("Клюв", "Beak", 4, 5, "6 (1d8 + 2)", "рубящего", "Slashing")]),
  beast("Бабуин", "Baboon", 367, 12, 3, "1d6", [8,14,11,4,12,6], "0",
    p("Маленький Зверь, без мировоззрения. Скорость 30 фт., Лазание 30 фт.; пассивная Внимательность 11; языков нет.", "Small unaligned Beast. Speed 30 ft., Climb 30 ft.; passive Perception 11; no languages."), [pack, melee("Укус", "Bite", 1, 5, "1 (1d4 - 1)", "колющего", "Piercing")]),
  beast("Барсук", "Badger", 367, 10, 3, "1d4 + 1", [4,11,12,2,12,5], "0",
    p("Крошечный Зверь, без мировоззрения. Скорость 20 фт., Копание 5 фт.; Тёмное зрение 30 фт.; пассивная Внимательность 11; языков нет.", "Tiny unaligned Beast. Speed 20 ft., Burrow 5 ft.; Darkvision 30 ft.; passive Perception 11; no languages."), [smell, melee("Укус", "Bite", 2, 5, "1", "колющего", "Piercing")]),
  beast("Чёрный медведь", "Black Bear", 367, 11, 19, "3d8 + 6", [15,10,14,2,12,7], "1/2",
    p("Средний Зверь, без мировоззрения. Природный доспех. Скорость 40 фт., Лазание 30 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Medium unaligned Beast. Natural armor. Speed 40 ft., Climb 30 ft. Perception +3; passive Perception 13; no languages."), [smell,
      p("Мультиатака: один Укус и одна атака Когтями.", "Multiattack: one Bite and one Claws attack."), melee("Укус", "Bite", 3, 5, "5 (1d6 + 2)", "колющего", "Piercing"), melee("Когти", "Claws", 3, 5, "7 (2d4 + 2)", "рубящего", "Slashing"),
    ]),
  beast("Кровавый ястреб", "Blood Hawk", 368, 12, 7, "2d6", [6,14,10,3,14,5], "1/8",
    p("Маленький Зверь, без мировоззрения. Скорость 10 фт., Полёт 60 фт. Внимательность +4; пассивная Внимательность 14; языков нет.", "Small unaligned Beast. Speed 10 ft., Fly 60 ft. Perception +4; passive Perception 14; no languages."), [sight, pack, melee("Клюв", "Beak", 4, 5, "4 (1d4 + 2)", "колющего", "Piercing")]),
  beast("Кабан", "Boar", 368, 11, 11, "2d8 + 2", [13,11,12,2,9,5], "1/4",
    p("Средний Зверь, без мировоззрения. Природный доспех. Скорость 40 фт.; пассивная Внимательность 9; языков нет.", "Medium unaligned Beast. Natural armor. Speed 40 ft.; passive Perception 9; no languages."), [
      p("Натиск: если кабан прошёл к цели не менее 20 фт. по прямой и попал Клыком в тот же ход, цель получает ещё 3 (1d6) рубящего урона. Если цель — существо, она делает спасбросок Силы Сл 11 или Сбита с ног.", "Charge: after moving at least 20 ft. straight toward a target and hitting it with Tusk on the same turn, deal another 3 (1d6) Slashing damage. A creature target makes a DC 11 Strength save or falls Prone."),
      p("Неукротимость (восстановление после короткого или долгого отдыха): если 7 урона или меньше должны снизить кабана до 0 хитов, вместо этого остаётся 1 хит.", "Relentless (recharges after a short or long rest): if damage of 7 or less would reduce the boar to 0 Hit Points, it drops to 1 instead."),
      melee("Клык", "Tusk", 3, 5, "4 (1d6 + 1)", "рубящего", "Slashing"),
    ]),
  beast("Бурый медведь", "Brown Bear", 369, 11, 34, "4d10 + 12", [19,10,16,2,13,7], "1",
    p("Большой Зверь, без мировоззрения. Природный доспех. Скорость 40 фт., Лазание 30 фт. Внимательность +3; пассивная Внимательность 13; языков нет.", "Large unaligned Beast. Natural armor. Speed 40 ft., Climb 30 ft. Perception +3; passive Perception 13; no languages."), [smell,
      p("Мультиатака: один Укус и одна атака Когтями.", "Multiattack: one Bite and one Claws attack."), melee("Укус", "Bite", 5, 5, "8 (1d8 + 4)", "колющего", "Piercing"), melee("Когти", "Claws", 5, 5, "11 (2d6 + 4)", "рубящего", "Slashing"),
    ]),
];
