import type { Edition } from "./rules-data";
import type { SubclassFeature, SubclassExtension } from "./subclasses";
import { ARTIFICER_INFUSION_OPTIONS } from "./artificer-infusions";
import { ARTIFICER_REPLICAS } from "./artificer-replicas";
import { ARTIFICER_REPLICAS_HIGH } from "./artificer-replicas-high";
import { ARTIFICER_REPLICAS_2024_HIGH } from "./artificer-replicas-2024-high";
import { ARTIFICER_REPLICAS_2024 } from "./artificer-replicas-2024";
import { ARTIFICER_REPLICAS_2024_COMMON } from "./artificer-replicas-2024-common";
import { ARTIFICER_REPLICAS_2024_GENERAL } from "./artificer-replicas-2024-general";

/** Original mechanical notes, independently separated by edition. Sources:
 * https://dnd.su/class/137-artificer/
 * https://next.dnd.su/class/artificer
 */
export const ARTIFICER_PREPARED_2024 = [2,3,4,5,6,6,7,7,9,9,10,10,11,11,12,12,14,14,15,15];
export const ARTIFICER_INFUSIONS_2014: [number,number][] = [[2,4],[6,6],[10,8],[14,10],[18,12]];
export const ARTIFICER_PLANS_2024: [number,number][] = [[2,4],[6,5],[10,6],[14,7],[18,8]];
export const ARTIFICER_ITEMS: [number,number][] = [[2,2],[6,3],[10,4],[14,5],[18,6]];
type ArtificerFeature = SubclassFeature & { originalDescription: string };
const f = (level: number, name: string, description: string, originalDescription: string): ArtificerFeature => ({ level,name,description,originalDescription });
export const ARTIFICER_FEATURES: Record<Edition, ArtificerFeature[]> = {
  "2014": [
    f(1,"Магический мастеровой","Держа воровские или ремесленные инструменты, действием коснитесь Крошечного немагического предмета. Дайте ему одно свойство: яркий свет 5 фт. и тусклый ещё 5; запись вашего сообщения до 6 секунд, звучащая при касании существом и слышная в 10 фт.; постоянный запах или негромкий невербальный звук, ощущаемый в 10 фт.; неподвижное изображение, линии или текст до 25 слов на поверхности. Эффект постоянен, но действием с касанием можно убрать. Одно свойство на предмет, одновременно Интеллект предметов (минимум 1); превышение завершает самый старый эффект.","While holding thieves’ tools or artisan’s tools, use an action to touch a Tiny nonmagical object and give it one property: bright light for 5 feet and dim light for another 5; your recorded message of at most 6 seconds, audible within 10 feet whenever a creature touches it; a continuous odor or nonverbal sound perceptible within 10 feet; or a static surface image, shapes, lines, or up to 25 words. The effect lasts until removed by another action and touch. Each object holds one property. Maintain at most your Intelligence modifier (minimum one) objects; exceeding that limit ends the oldest effect."),
    f(1,"Использование заклинаний изобретателя","Интеллект — заклинательная характеристика. Все заклинания изобретателя требуют материального компонента: держите в руках воровские или ремесленные инструменты, которыми владеете; с уровня 2 подходит и ваш инфузированный предмет. Начальные 2 заговора увеличиваются до 3 на уровне 10 и 4 на уровне 14; при каждом повышении можно заменить один. Подготовьте Интеллект + половину уровня вниз заклинаний (минимум 1), имеющих доступные вам круги. После долгого отдыха можно сменить весь список; подготовка занимает 1 минуту на круг каждого заклинания. Подготовленные ритуалы можно применять ритуально. Ячейки восстанавливаются после долгого отдыха.","Use Intelligence for Artificer spell attacks and saves. Every Artificer spell requires a material component: hold thieves’ tools or artisan’s tools with which you are proficient, or from level 2 an item bearing one of your infusions. Know two cantrips, increasing to three at level 10 and four at level 14; replace one whenever you gain an Artificer level. Prepare Intelligence modifier plus half your class level rounded down spells, minimum one, of levels you have slots for. After a long rest you may replace the entire prepared list, spending at least one minute per spell level for each spell. A prepared Artificer ritual can be cast as a ritual. Recover all slots after a long rest."),
    f(2,"Инфузирование предмета","Изучите 4 инфузии; на уровнях 6/10/14/18 известно 6/8/10/12. При повышении можно заменить одну. В конце долгого отдыха касанием насытьте подходящие немагические предметы; предел одновременно 2, затем 3/4/5/6 на уровнях 6/10/14/18. Каждая известная инфузия поддерживает один предмет; предмет содержит только одну инфузию. Можно сразу настроиться. Превышение предела завершает старейшую инфузию. Эффект исчезает при замене известной инфузии или через Интеллект дней после вашей смерти (минимум 1); иначе постоянен. При исчезновении контейнера его содержимое без вреда появляется рядом.","Learn four infusions, increasing to six/eight/ten/twelve at levels 6/10/14/18. Replace one known infusion when gaining a class level. At the end of a long rest, touch eligible nonmagical items to infuse them. Maintain two items, increasing to three/four/five/six at levels 6/10/14/18. Each known infusion affects one item at a time, and an item accepts only one infusion. You may immediately attune. Exceeding the active limit ends the oldest infusion. An infusion otherwise lasts indefinitely, but ends when you replace its known formula or a number of days after your death equal to your Intelligence modifier, minimum one. Contents of a container whose infusion ends appear safely around it."),
    f(3,"Подходящий инструмент","Имея воровские или ремесленные инструменты, за час непрерывной работы создайте один немагический набор ремесленных инструментов в свободном месте в 5 фт. Работа совместима с коротким или долгим отдыхом. Набор исчезает при новом применении.","Using thieves’ tools or artisan’s tools, work uninterrupted for one hour to create one nonmagical set of artisan’s tools in an unoccupied space within 5 feet. This work can take place during a short or long rest. The set vanishes when you use the feature again."),
    f(6,"Компетентность в инструментах","Удваивайте бонус мастерства на проверках характеристик с инструментами, которыми владеете.","Double your proficiency bonus for ability checks using tools with which you are proficient."),
    f(7,"Проблеск гениальности","Когда вы или видимое существо в 30 фт. делаете проверку характеристики или спасбросок, реакцией добавьте ваш модификатор Интеллекта. Число применений — Интеллект, минимум 1; восстановление после долгого отдыха.","When you or a creature you can see within 30 feet makes an ability check or saving throw, use your reaction to add your Intelligence modifier. Uses equal your Intelligence modifier, minimum one; recover all after a long rest."),
    f(10,"Эксперт магических предметов","Одновременно настройтесь на 4 предмета. Создание обычных и необычных магических предметов требует четверти обычного времени и половины обычной стоимости в золоте.","Attune to up to four magic items. Craft common and uncommon magic items in one quarter of the normal time and for half the normal gold cost."),
    f(11,"Хранящий заклинания предмет","В конце долгого отдыха касанием сохраните в простом/воинском оружии или вашем фокусирующем предмете заклинание из списка изобретателя 1–2 круга со временем применения одно действие; подготовка не нужна. Держатель действием создаёт эффект с вашим модификатором Интеллекта и сам поддерживает нужную концентрацию. Всего 2 × Интеллект применений (минимум 2). Сохранение заканчивается при исчерпании или новом применении этой способности.","At the end of a long rest, touch a simple or martial weapon or an item you can use as a spellcasting focus. Store a first- or second-level Artificer-list spell with a casting time of one action; it need not be prepared. A creature holding it uses an action to produce its effect with your Intelligence modifier and maintains any required concentration itself. The spell lasts for twice your Intelligence modifier uses, minimum two, or until you store another spell."),
    f(14,"Учёный магических предметов","Одновременно настройтесь на 5 предметов. Для настройки и использования магических предметов игнорируйте требования класса, расы, заклинаний и уровня.","Attune to up to five items. Ignore class, race, spell, and level requirements for attuning to or using magic items."),
    f(18,"Мастер магических предметов","Одновременно настройтесь на 6 магических предметов.","Attune to up to six magic items."),
    f(20,"Душа изобретения","Ко всем спасброскам +1 за каждый предмет, на который вы настроены. Когда хиты падают до 0 без мгновенной смерти, реакцией завершите одну свою инфузию: вместо 0 останется 1 хит.","Gain +1 to every saving throw per item to which you are attuned. When reduced to 0 hit points without being killed outright, use your reaction to end one of your infusions and instead remain at 1 hit point."),
  ],
  "2024": [
    f(1,"Сотворение заклинаний артефактора","Интеллект — заклинательная характеристика. Каждое заклинание требует материального компонента: держите в руках воровские, ремонтные или другие ремесленные инструменты, которыми владеете. Начальные 2 заговора увеличиваются до 3 на уровне 10 и 4 на уровне 14; один можно заменить после долгого отдыха. Число подготовленных заклинаний определяется таблицей класса, а не Интеллектом. После долгого отдыха можно сменить весь подготовленный список и восстановить все ячейки.","Intelligence is your spellcasting ability. Every Artificer spell needs a material component: hold thieves’ tools, tinker's tools, or other artisan's tools with which you are proficient. Start with two cantrips, gaining a third at level 10 and fourth at level 14; replace one after a long rest. Prepared spell counts follow the class table rather than your Intelligence. After a long rest you may replace the whole prepared list and recover all spell slots."),
    f(1,"Магия вещей","Дополнительно знаете Починку. С инструментами ремонтника действием Магия создайте в свободном месте в 5 фт. один предмет: блок и лебёдка, ведро, колокольчик, корзина, бумага, верёвка, кошель, крюк-кошка, калтропы, кандалы, металлические шарики, кувшин, лампа, леска, ломик, стеклянная бутылка, лопата, масло, мешок, одеяло, охотничий капкан, пергамент, свеча, сеть, спальник, железные шипы, трутница, факел, флакон, фляга или шест. Предмет исчезает после вашего долгого отдыха. Интеллект применений (минимум 1) за долгий отдых.","Know Mending in addition to your chosen cantrips. Holding tinker's tools, take a Magic action to create one of these items in an unoccupied space within 5 feet: ball bearings, basket, bedroll, bell, blanket, block and tackle, bottle, bucket, caltrops, candle, crowbar, flask, grappling hook, hunting trap, iron spikes, jug, lamp, net, oil, paper, parchment, pole, pouch, rope, sack, shovel, string, tinderbox, torch, vial, waterskin, or manacles. It disappears after your next long rest. Uses equal your Intelligence modifier, minimum one, and recover on a long rest."),
    f(2,"Реплики магических предметов","Изучите 4 схемы; на уровнях 6/10/14/18 известно 5/6/7/8. При повышении замените не более одной на доступную по уровню. С инструментами ремонтника после долгого отдыха создавайте разные предметы по известным схемам: одновременно максимум 2, затем 3/4/5/6 на уровнях 6/10/14/18. Можно немедленно настроиться. Превышение завершает старейшую реплику. Замена схемы немедленно убирает все её предметы; после смерти реплики исчезают через 1к4 дня. Содержимое исчезнувшего контейнера без вреда появляется рядом. Созданное этим умением оружие или волшебную палочку можно использовать как фокусировку.","Learn four plans, increasing to five/six/seven/eight at levels 6/10/14/18. Replace at most one plan when gaining a class level, observing its level prerequisites. Holding tinker's tools after a long rest, create different items from known plans, maintaining at most two, then three/four/five/six at levels 6/10/14/18. You can immediately attune. Exceeding the limit removes the oldest replica. Replacing a plan immediately removes every item made from it; after your death replicas disappear in 1d4 days. A vanished container's contents appear safely nearby. Weapons or wands you create this way can be your spellcasting focus."),
    f(6,"Магический мастеровой","Коснитесь своей реплики в 5 фт.: бонусным действием потратьте ячейку и восстановите столько зарядов предмета, каков круг ячейки; либо бонусным действием уничтожьте реплику и получите ячейку 1 круга за обычный предмет или 2 за необычный/редкий, до долгого отдыха (раз за долгий отдых); либо действием Магия превратите реплику в предмет другой известной схемы (раз за долгий отдых).", "Touch one of your replicas within 5 feet. As a Bonus Action, expend a spell slot to restore charges equal to its level. Alternatively, as a Bonus Action dissolve a replica to gain a first-level slot for a common item or second-level slot for an uncommon or rare item; use this once per long rest and the slot vanishes at that rest. As a separate once-per-long-rest Magic action, transform a replica into another item whose plan you know."),
    f(7,"Проблеск гениальности","После провала проверки характеристики или спасброска вами или видимым существом в 30 фт. реакцией добавьте ваш модификатор Интеллекта, возможно превратив провал в успех. Интеллект применений (минимум 1) за долгий отдых.","After you or a creature you can see within 30 feet fails an ability check or saving throw, use your Reaction to add your Intelligence modifier, possibly turning failure into success. Uses equal Intelligence modifier, minimum one, recovered after a long rest."),
    f(10,"Искусник магических предметов","Одновременно настройтесь на 4 магических предмета.","Attune to up to four magic items."),
    f(11,"Хранящий заклинания предмет","После долгого отдыха касанием сохраните в простом/воинском оружии или вашем фокусирующем предмете заклинание артефактора 1–3 круга со временем одно действие и без расходуемого материального компонента; подготовка не нужна. Держатель действием Магия создаёт эффект с вашим модификатором Интеллекта и сам поддерживает концентрацию. Затем предмет недоступен до начала следующего хода этого существа. Предел 2 × Интеллект применений (минимум 2), либо до нового сохранения.","After a long rest, touch a simple or martial weapon or an item you can use as a focus. Store a first-, second-, or third-level Artificer spell with an action casting time and no consumed material component, whether prepared or not. A holder takes a Magic action to produce the effect using your Intelligence modifier, maintaining any concentration itself. The item then cannot be used again until the start of that creature's next turn. It lasts for twice your Intelligence modifier uses, minimum two, or until you store another spell."),
    f(14,"Изобретательность","Одновременно настройтесь на 5 предметов. После короткого отдыха восстановите одно применение Проблеска гениальности.","Attune to up to five items. After a short rest recover one use of Flash of Genius."),
    f(18,"Мастер магических предметов","Одновременно настройтесь на 6 магических предметов.","Attune to up to six magic items."),
    f(20,"Душа творения","Если хиты падают до 0 без мгновенной смерти, можете уничтожить любое число своих необычных или редких реплик: вместо 0 получите 20 хитов за каждый предмет. Если настроены хотя бы на один магический предмет, короткий отдых восстанавливает все применения Проблеска гениальности.","When reduced to 0 hit points without being killed outright, you may dissolve any number of your uncommon or rare replicas and instead have 20 hit points per dissolved item. If attuned to at least one magic item, a short rest restores all uses of Flash of Genius."),
  ],
};

const artisanToolEnglish: Record<string,string> = {
  alchemist:"Alchemist’s Supplies", brewer:"Brewer’s Supplies", calligrapher:"Calligrapher’s Supplies",
  carpenter:"Carpenter’s Tools", cartographer:"Cartographer’s Tools", cobbler:"Cobbler’s Tools",
  cook:"Cook’s Utensils", glassblower:"Glassblower’s Tools", jeweler:"Jeweler’s Tools",
  leatherworker:"Leatherworker’s Tools", mason:"Mason’s Tools", painter:"Painter’s Supplies",
  potter:"Potter’s Tools", smith:"Smith’s Tools", weaver:"Weaver’s Tools", woodcarver:"Woodcarver’s Tools",
};
export const ARTISAN_TOOL_OPTIONS = [
  ["alchemist", "Инструменты алхимика"], ["brewer", "Инструменты пивовара"],
  ["calligrapher", "Инструменты каллиграфа"], ["carpenter", "Инструменты плотника"],
  ["cartographer", "Инструменты картографа"], ["cobbler", "Инструменты сапожника"],
  ["cook", "Поварские принадлежности"], ["glassblower", "Инструменты стеклодува"],
  ["jeweler", "Инструменты ювелира"], ["leatherworker", "Инструменты кожевника"],
  ["mason", "Инструменты каменщика"], ["painter", "Инструменты художника"],
  ["potter", "Инструменты гончара"], ["smith", "Инструменты кузнеца"],
  ["weaver", "Инструменты ткача"], ["woodcarver", "Инструменты резчика по дереву"],
].map(([id, name]) => ({ id, name: `Владение: ${name.toLowerCase()}`, description: `Добавляйте бонус мастерства к проверкам, использующим ${name.toLowerCase()}.`, originalDescription:`Proficiency with ${artisanToolEnglish[id]}. Add your Proficiency Bonus to checks using these tools.` }));

export const ARTIFICER_BASE_RULES = Object.fromEntries(
  (["2014", "2024"] as const).map((edition): [Edition, SubclassExtension] => [edition, {
    id: "artificer-base", classId: "artificer", name: "Изобретатель",
    description: "Базовые умения изобретателя.", editions: [edition], level2014: 3,
    source: edition === "2014" ? "Tasha’s Cauldron of Everything" : "Eberron: Forge of the Artificer",
    sourceUrl: edition === "2014" ? "https://dnd.su/class/137-artificer/" : "https://next.dnd.su/class/artificer",
    features: [f(1,"Владения изобретателя", "Владение простым оружием, лёгкими и средними доспехами, щитами, воровскими инструментами и инструментами ремонтника. Выберите ещё один ремесленный инструмент.", "Proficiency with Simple weapons, Light and Medium armor, Shields, Thieves’ Tools, and Tinker’s Tools. Choose one other type of Artisan’s Tools."), ...ARTIFICER_FEATURES[edition]],
    grants: edition === "2024" ? [[1, ["mending"]]] : [],
    choices: [{id:"artificer-tool", level:1, name:"Ремесленные инструменты", count:1, options:ARTISAN_TOOL_OPTIONS}],
    choicePools: [{
      id: edition === "2014" ? "artificer-infusions" : "artificer-plans",
      name: edition === "2014" ? "Известные инфузии" : "Известные схемы",
      counts: edition === "2014" ? ARTIFICER_INFUSIONS_2014 : ARTIFICER_PLANS_2024,
      replaceAt: "level",
      options: [
        ...(edition === "2014" ? ARTIFICER_INFUSION_OPTIONS : []),
        ...(edition === "2014" ? [...ARTIFICER_REPLICAS, ...ARTIFICER_REPLICAS_HIGH] : [...ARTIFICER_REPLICAS_2024, ...ARTIFICER_REPLICAS_2024_HIGH, ...ARTIFICER_REPLICAS_2024_COMMON, ...ARTIFICER_REPLICAS_2024_GENERAL]).map(item => ({
          id:item.id, name:item.name.ru, description:item.rules.ru, originalDescription:item.rules.en,
          level:item.replicationLevel ?? 2, itemReferenceIds:[item.id],
        })),
      ],
    }],
  }]),
) as Record<Edition, SubclassExtension>;
