import type { SubclassExtension } from "./subclasses";
/** Tasha's official infusions only; Replicate Magic Item is expanded separately. */
export const ARTIFICER_INFUSION_OPTIONS: NonNullable<SubclassExtension["choicePools"]>[number]["options"] = [
 {id:"returning-weapon",name:"Возвращающееся оружие",description:"Простое или воинское метательное оружие. Магическое, +1 к атакам и урону; сразу после дальнобойной атаки возвращается в руку. Настройка не нужна."},
 {id:"arcane-propulsion-armor",level:14,name:"Движимый магией доспех",description:"Доспех, настройка. Ходьба +5 фт.; заменяет отсутствующие конечности и не снимается против воли. Пустые рукавицы — простое магическое рукопашное оружие, которым носитель владеет, 1к8 силового урона, метательное 20/60 фт. Брошенная рукавица сразу возвращается и прикрепляется."},
 {id:"armor-magical-strength",name:"Доспех магической силы",description:"Доспех, настройка, 6 зарядов, восстановление 1к6 на рассвете. Один заряд добавляет модификатор Интеллекта НОСИТЕЛЯ к его проверке или спасброску Силы. Либо реакцией и одним зарядом носитель предотвращает своё падение ничком."},
 {id:"resistant-armor",level:6,name:"Доспех сопротивления",description:"Доспех, настройка. При инфузировании выберите один тип: кислота, холод, огонь, электричество, яд, звук, излучение, некротическая энергия, психическая энергия или силовое поле. Носящий доспех получает сопротивление этому типу."},
 {id:"radiant-weapon",level:6,name:"Излучающее свет оружие",description:"Простое или воинское оружие, настройка. Магическое, +1 к атакам и урону. Держатель бонусным действием включает или выключает яркий свет 30 фт. и тусклый ещё 30. Четыре заряда, восстановление 1к4 на рассвете. Когда по держателю попадают атакой, реакцией и зарядом потребуйте спасбросок Телосложения атакующего против Сл заклинаний изобретателя: провал ослепляет до конца следующего хода атакующего."},
 {id:"spell-refueling-ring",level:6,name:"Кольцо восстановления заклинаний",description:"Кольцо, настройка. Носящий его действием восстанавливает одну потраченную ячейку не выше 3-го круга. После использования кольца носитель не может повторить это до следующего рассвета."},
 {id:"repulsion-shield",level:6,name:"Отталкивающий щит",description:"Щит, настройка. Держатель получает +1 к КД. Четыре заряда, восстановление 1к4 на рассвете. Сразу после попадания по держателю рукопашной атакой он может реакцией и зарядом оттолкнуть атакующего до 15 фт."},
 {id:"repeating-shot",name:"Повторный выстрел",description:"Простое или воинское оружие со свойством Боеприпас, настройка. Магическое, +1 к атакам и урону дальнобойных атак; игнорирует Заряжание. Если боеприпас не вложен, при дальнобойной атаке создаёт магический боеприпас, исчезающий сразу после попадания или промаха."},
 {id:"boots-winding-path",level:6,name:"Сапоги извилистого пути",description:"Сапоги, настройка. Бонусным действием носитель телепортируется до 15 фт. в видимое свободное место, где уже находился на текущем ходу."},
 {id:"homunculus-servant",name:"Слуга-гомункул",description:"Камень или кристалл стоимостью минимум 100 зм становится сердцем дружественного гомункула. Инициатива совпадает с вашей, ход сразу после вас. Сам перемещается и использует реакцию, но действием Уклоняется, пока вы бонусным действием не прикажете иное. При вашей недееспособности действует самостоятельно. Починка лечит 2к6 хитов. При вашей или его смерти тело исчезает, сердце остаётся на месте смерти.",spellReferenceIds:["mending-2014"],creatureReferenceIds:["homunculus-servant-2014"]},
 {id:"enhanced-defense",name:"Улучшенная защита",description:"Доспех или щит, настройка не нужна. Носящий доспех либо держащий щит получает +1 к КД; +2 с уровня изобретателя 10."},
 {id:"enhanced-focus",name:"Улучшенная магическая фокусировка",description:"Жезл, посох или палочка, настройка. Держатель получает +1 к атакам заклинанием и игнорирует укрытие наполовину при этих атаках; +2 с уровня изобретателя 10."},
 {id:"enhanced-weapon",name:"Улучшенное оружие",description:"Простое или воинское оружие, настройка не нужна. Магическое, +1 к атакам и урону; +2 с уровня изобретателя 10."},
 {id:"mind-sharpener",name:"Усилитель разума",description:"Доспех или ряса, настройка не нужна. Четыре заряда, восстановление 1к4 на рассвете. При провале спасброска Телосложения для поддержания концентрации носитель реакцией и зарядом превращает его в успех."},
 {id:"helm-awareness",level:10,name:"Шлем осведомлённости",description:"Шлем, настройка. Носитель получает преимущество на инициативу; его нельзя застать врасплох, пока он не Недееспособен."},
];

const english: Record<string,string> = {
  "returning-weapon": "Infuse a simple or martial weapon with the Thrown property. No attunement. It is magical, grants +1 to attack and damage rolls, and returns to the wielder’s hand immediately after a ranged attack.",
  "arcane-propulsion-armor": "Infuse armor; attunement required. Walking speed increases by 5 feet. The armor replaces missing limbs and cannot be removed against the wearer’s will. An empty gauntlet is a simple magical melee weapon with which the wearer is proficient: 1d8 Force damage, Thrown 20/60 feet. A thrown gauntlet immediately returns and reattaches.",
  "armor-magical-strength": "Infuse armor; attunement required. Six charges, regaining 1d6 at dawn. The wearer can spend one charge to add THEIR OWN Intelligence modifier to a Strength check or save. Alternatively, the wearer can use a reaction and one charge to avoid being knocked prone.",
  "resistant-armor": "Infuse armor; attunement required. When infusing, select Acid, Cold, Fire, Force, Lightning, Necrotic, Poison, Psychic, Radiant, or Thunder. The wearer resists that damage type.",
  "radiant-weapon": "Infuse a simple or martial weapon; attunement required. It is magical and grants +1 to attack and damage rolls. Its holder can use a bonus action to turn on or off bright light for 30 feet and dim light for 30 more. Four charges, regaining 1d4 at dawn. When an attack hits the holder, a reaction and one charge force the attacker to make a Constitution save against the Artificer’s spell save DC; failure blinds it until the end of its next turn.",
  "spell-refueling-ring": "Infuse a ring; attunement required. Its wearer can use an action to regain one expended spell slot of level 3 or lower. After using the ring, that wearer cannot use it again until the next dawn.",
  "repulsion-shield": "Infuse a shield; attunement required. Its holder gains +1 AC. Four charges, regaining 1d4 at dawn. Immediately after a melee attack hits the holder, the holder can use a reaction and one charge to push the attacker up to 15 feet away.",
  "repeating-shot": "Infuse a simple or martial weapon with the Ammunition property; attunement required. It is magical, grants +1 to attack and damage rolls for ranged attacks, and ignores Loading. If no ammunition is loaded, it creates magical ammunition for each ranged attack; that ammunition vanishes immediately after hitting or missing.",
  "boots-winding-path": "Infuse boots; attunement required. As a bonus action, the wearer teleports up to 15 feet to a visible unoccupied space the wearer occupied earlier during the current turn.",
  "homunculus-servant": "Infuse a gem or crystal worth at least 100 GP as the heart of a friendly homunculus. It shares your initiative and takes its turn immediately after yours. It moves and uses reactions independently, but Dodges unless you use a bonus action to order a different action. While you are incapacitated, it acts independently. Mending restores 2d6 HP. If either you or the homunculus dies, its body vanishes and leaves the heart at its location.",
  "enhanced-defense": "Infuse armor or a shield; no attunement. While wearing the armor or holding the shield, gain +1 AC, increasing to +2 at Artificer level 10.",
  "enhanced-focus": "Infuse a rod, staff, or wand; attunement required. Its holder gains +1 to spell attack rolls and ignores half cover with spell attacks. The bonus becomes +2 at Artificer level 10.",
  "enhanced-weapon": "Infuse a simple or martial weapon; no attunement. It is magical and grants +1 to attack and damage rolls, increasing to +2 at Artificer level 10.",
  "mind-sharpener": "Infuse armor or robes; no attunement. Four charges, regaining 1d4 at dawn. When the wearer fails a Constitution save to maintain concentration, a reaction and one charge turn it into a success.",
  "helm-awareness": "Infuse a helmet; attunement required. The wearer has advantage on initiative rolls and cannot be surprised unless incapacitated."
};
for (const option of ARTIFICER_INFUSION_OPTIONS) {
 option.originalDescription = english[option.id];
 option.itemReferenceIds = [`infusion-${option.id}-2014`];
}
