import type { SpellOption } from "./rules-data";
const spell = (
  id: string,
  name: string,
  level: number,
  school: string,
  classes: string[],
  castingTime: string,
  range: string,
  duration: string,
  concentration: boolean,
  components: string,
  descriptionRu: string,
  description: string,
  path: string,
): SpellOption => ({
  id: `${id}-2014`,
  name,
  level,
  school,
  classes,
  castingTime,
  range,
  duration,
  concentration,
  components,
  descriptionRu,
  description,
  summary: descriptionRu,
  editions: ["2014"],
  ritual: false,
  source: "Player’s Handbook (2014)",
  sourceUrl: `https://dnd.su/spells/${path}/`,
});
export const CLERIC_SPELLS: SpellOption[] = [
  {
    ...spell(
      "synaptic-static",
      "Синаптический разряд · Synaptic Static",
      5,
      "Очарование",
      ["bard", "wizard", "warlock", "sorcerer"],
      "Action",
      "120 feet",
      "Instantaneous",
      false,
      "V, S",
      "Каждое существо в сфере 20 фт. вокруг выбранной точки в дистанции делает спасбросок Интеллекта. Провал: 8d6 психического урона и на 1 минуту штраф d6 к атакам, проверкам характеристик и спасброскам Телосложения для концентрации. Успех: только половина урона. Затронутая цель повторяет спасбросок Интеллекта в конце каждого хода, прекращая штраф при успехе.",
      "Each creature in a 20-foot-radius Sphere centered on a point within range makes an Intelligence save. Failure deals 8d6 Psychic damage and muddles its thoughts for 1 minute: subtract 1d6 from its attack rolls, ability checks, and Constitution saves to maintain Concentration. Success deals half damage only. An affected creature repeats the Intelligence save at the end of each turn, ending the penalty on success.",
      "10668-synaptic-static",
    ),
    id: "synaptic-static-2024",
    editions: ["2024"],
    source: "Player’s Handbook (2024)",
    sourceUrl: "https://next.dnd.su/spells/10668-synaptic-static",
  },
  spell(
    "destructive-wave",
    "Разрушительная волна · Destructive Wave",
    5,
    "Воплощение",
    ["paladin"],
    "Action",
    "Self (30 feet)",
    "Instantaneous",
    false,
    "V",
    "Выбранные вами существа в 30 фт. делают спасбросок Телосложения. Провал: 5d6 звукового урона плюс 5d6 излучением или некротического на ваш выбор и опрокидывание. Успех: половина обоих типов урона, без опрокидывания.",
    "Choose creatures within 30 feet. Each makes a Constitution save: failure deals 5d6 Thunder plus 5d6 Radiant or Necrotic damage (your choice) and knocks it Prone; success halves the damage and prevents being knocked Prone.",
    "296-destructive_wave",
  ),
  spell(
    "crusaders-mantle",
    "Мантия крестоносца · Crusader’s Mantle",
    3,
    "Воплощение",
    ["paladin"],
    "Action",
    "Self",
    "1 minute",
    true,
    "V",
    "Аура радиусом 30 фт. перемещается с вами. Вы и невраждебные существа внутри наносите дополнительно 1d4 урона излучением при попадании атакой оружием.",
    "A 30-foot-radius aura moves with you. You and nonhostile creatures within it deal an additional 1d4 Radiant damage whenever they hit with a weapon attack.",
    "156-crusader_s_mantle",
  ),
  spell(
    "searing-smite",
    "Палящая кара · Searing Smite",
    1,
    "Воплощение",
    ["paladin"],
    "Bonus Action",
    "Self",
    "1 minute",
    true,
    "V",
    "Следующее попадание рукопашной атакой оружием по существу во время заклинания наносит ещё 1d6 огненного урона и поджигает цель. В начале каждого своего хода до окончания заклинания она делает спасбросок Телосложения: провал наносит 1d6 огненного урона, успех заканчивает заклинание. Цель либо существо в 5 фт. может действием погасить пламя; вода и другие гасящие эффекты также заканчивают заклинание. За круг ячейки выше первого добавьте 1d6 только к начальному урону попадания.",
    "Your next melee weapon hit against a creature during the duration deals an extra 1d6 Fire damage and ignites it. At the start of each subsequent turn it makes a Constitution save: failure deals 1d6 Fire damage; success ends the spell. The target or a creature within 5 feet can spend an action extinguishing the flames. Other extinguishing effects, such as immersion in water, also end the spell. Each slot level above 1 adds 1d6 only to the initial hit’s extra damage.",
    "224-searing_smite",
  ),
  spell(
    "elemental-weapon",
    "Стихийное оружие · Elemental Weapon",
    3,
    "Преобразование",
    ["paladin"],
    "Action",
    "Touch",
    "1 hour",
    true,
    "V, S",
    "Коснитесь немагического оружия: оно становится магическим, получает +1 к атакам и +1d4 урона выбранного типа — кислота, холод, огонь, электричество или звук. Ячейка 5–6 круга даёт +2 к атакам и +2d4 урона; ячейка 7+ — +3 и +3d4 соответственно.",
    "Touch a nonmagical weapon. It becomes magical with +1 to attack rolls and an extra 1d4 damage of your chosen type: Acid, Cold, Fire, Lightning, or Thunder. A level 5–6 slot changes these to +2 and 2d4; a level 7+ slot changes them to +3 and 3d4.",
    "339-elemental_weapon",
  ),
  spell(
    "grasping-vine",
    "Цепкая лоза · Grasping Vine",
    4,
    "Вызов",
    ["druid", "ranger"],
    "Bonus Action",
    "30 feet",
    "1 minute",
    true,
    "V, S",
    "Создайте лозу на земле в видимом свободном месте в дистанции. При сотворении прикажите ей схватить видимую вами цель в 30 фт. от лозы: провал спасброска Ловкости подтягивает цель к лозе на 20 фт. Пока заклинание действует, бонусным действием в каждый свой ход можно повторить попытку с той же или другой целью.",
    "Create a vine on the ground in a visible unoccupied space within range. When casting, you may direct it to seize a creature you can see within 30 feet of the vine. A failed Dexterity save pulls that creature 20 feet toward the vine. On each of your turns during the duration, a Bonus Action can order another attempt against the same or a different creature.",
    "85-grasping_vine",
  ),
  spell(
    "ray-of-sickness",
    "Луч болезни · Ray of Sickness",
    1,
    "Некромантия",
    ["wizard", "sorcerer"],
    "Action",
    "60 feet",
    "Instantaneous",
    false,
    "V, S",
    "Дальнобойная атака заклинанием по существу в дистанции. Попадание: 2d8 урона ядом и спасбросок Телосложения; провал также отравляет цель до конца следующего вашего хода. За круг ячейки выше первого добавьте 1d8 урона.",
    "Make a ranged spell attack against a creature within range. A hit deals 2d8 Poison damage and forces a Constitution save. Failure also gives the target the Poisoned condition until the end of your next turn. Add 1d8 damage for each slot level above 1.",
    "147-ray_of_sickness",
  ),
  spell(
    "aura-of-life",
    "Аура жизни · Aura of Life",
    4,
    "Ограждение",
    ["paladin"],
    "Action",
    "Self (30 feet)",
    "10 minutes",
    true,
    "V",
    "Аура радиусом 30 фт. следует за вами. Вы и невраждебные существа внутри сопротивляетесь некротическому урону; максимум ваших хитов не может уменьшаться. Невраждебное живое существо с 0 хитов, начинающее ход внутри, восстанавливает 1 хит.",
    "A 30-foot-radius aura moves with you. You and nonhostile creatures within it have Resistance to Necrotic damage and cannot have their HP maximum reduced. A nonhostile living creature with 0 HP regains 1 HP when it starts its turn in the aura.",
    "4-aura_of_life",
  ),
];
