import type { Bilingual, RuleCreature } from "./rule-creatures";
import type { Edition } from "./rules-data";
const p = (ru:string,en:string): Bilingual => ({ru,en});
const resistance = p("Сопротивление магии: преимущество на спасброски против заклинаний и других магических эффектов.", "Magic Resistance: advantage on saves against spells and other magical effects.");
const invisibleSpell = p("Невидимость (действие): применяет Невидимость на себя без компонентов, используя Харизму. Действуют длительность, концентрация и условия окончания заклинания.", "Invisibility (action): casts Invisibility on itself without components, using Charisma. The spell's duration, concentration and ending conditions apply.");
const oldInvisibility = (ru:string,en:string) => p(`Невидимость (действие): становится Невидимым до ${ru} или прекращения концентрации (как на заклинании). Носимое и переносимое снаряжение также невидимо.`, `Invisibility (action): becomes Invisible until ${en} or concentration ends (as for a spell). Worn and carried equipment is invisible too.`);
const shape = (modern:boolean,ru:string,en:string) => p(`Смена облика (действие): принимает вид ${ru} или возвращается в истинный облик. Характеристики, кроме указанных скоростей, сохраняются; снаряжение не превращается.${modern ? "" : " После смерти возвращается в истинный облик."}`, `Shape-Shift (action): resembles ${en}, or returns to its true form. Statistics other than the listed speeds remain unchanged; equipment does not transform.${modern ? "" : " Returns to its true form on death."}`);
const make = (edition:Edition,id:string,name:Bilingual,page:number,armorClass:number,hp:number,hitDice:string,abilities:RuleCreature["abilities"],challenge:string,profile:Bilingual,rules:Bilingual[],spellIds?:string[]):RuleCreature => ({
  id:`${id}-${edition}`,edition,name,sourceUrl:edition === "2014" ? `https://www.dndbeyond.com/attachments/39j2li89/SRD5.1-CCBY4.0License.pdf#page=${page}` : `https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf#page=${page}`,
  armorClass,hp,hitDice,abilities,challenge,proficiency:2,initiative:Math.floor((abilities[1]-10)/2),profile,rules,...(spellIds ? {spellIds}:{}),
});
export const PACT_FAMILIARS: RuleCreature[] = [];
for (const edition of ["2014","2024"] as const) {
  const modern = edition === "2024";
  PACT_FAMILIARS.push(make(edition,"imp",p("Бес","Imp"),modern?300:277,13,modern?21:10,modern?"6d4 + 6":"3d4 + 3",[6,17,13,11,12,14],"1",
    p(`Крошечное Исчадие (дьявол${modern ? "" : ", перевёртыш"}), законно-злое. Скорость 20 фт., Полёт 40 фт. Обман +4, Проницательность +3, Скрытность +5${modern ? "" : ", Убеждение +4"}. Сопротивление холоду${modern ? "" : ", дробящему/колющему/рубящему урону немагических непосеребрённых атак"}; иммунитет к огню, яду и Отравленному. Тёмное зрение 120 фт. работает и в магической тьме; пассивная Внимательность 11. Общий, Инфернальный.`, `Tiny Lawful Evil Fiend (Devil${modern ? "" : ", shapechanger"}). Speed 20 ft., Fly 40 ft. Deception +4, Insight +3, Stealth +5${modern ? "" : ", Persuasion +4"}. Resistance to Cold${modern ? "" : " and Bludgeoning/Piercing/Slashing from nonmagical, nonsilvered attacks"}; immunity to Fire, Poison and Poisoned. Darkvision 120 ft. is unimpeded by magical darkness; passive Perception 11. Common, Infernal.`), [resistance,
      shape(modern,"крысы (Скорость 20 фт.), ворона (20 фт., Полёт 60 фт.) или паука (20 фт., Лазание 20 фт.)","a rat (Speed 20 ft.), raven (20 ft., Fly 60 ft.) or spider (20 ft., Climb 20 ft.)"),
      modern ? p("Жало: рукопашная атака +5, досягаемость 5 фт.; 6 (1d6 + 3) колющего урона и 7 (2d6) урона ядом.","Sting: melee attack +5, reach 5 ft.; 6 (1d6 + 3) Piercing plus 7 (2d6) Poison damage.") : p("Жало (Укус в зверином облике): рукопашная атака оружием +5, досягаемость 5 фт., одна цель; 5 (1d4 + 3) колющего урона. Спасбросок Телосложения Сл 11: ещё 10 (3d6) урона ядом при провале, половина при успехе.","Sting (Bite in Beast form): melee weapon attack +5, reach 5 ft., one target; 5 (1d4 + 3) Piercing damage. DC 11 Constitution save: another 10 (3d6) Poison damage on failure, half on success."),
      modern ? invisibleSpell : oldInvisibility("совершения атаки","it attacks"),
    ], modern?["invisibility-2024"]:undefined));
  PACT_FAMILIARS.push(make(edition,"quasit",p("Квазит","Quasit"),modern?317:273,13,modern?25:7,modern?"10d4":"3d4",[5,17,10,7,10,10],"1",
    p(`Крошечное Исчадие (демон${modern ? "" : ", перевёртыш"}), хаотично-злое. Скорость 40 фт. Скрытность +5. Сопротивление холоду, огню, электричеству${modern ? "" : ", дробящему/колющему/рубящему урону немагических атак"}; иммунитет к яду и Отравленному. Тёмное зрение 120 фт.; пассивная Внимательность 10. Бездны, Общий.`, `Tiny Chaotic Evil Fiend (Demon${modern ? "" : ", shapechanger"}). Speed 40 ft. Stealth +5. Resistance to Cold, Fire, Lightning${modern ? "" : " and Bludgeoning/Piercing/Slashing from nonmagical attacks"}; immunity to Poison and Poisoned. Darkvision 120 ft.; passive Perception 10. Abyssal, Common.`), [resistance,
      shape(modern,"летучей мыши (Скорость 10 фт., Полёт 40 фт.), сороконожки (40 фт., Лазание 40 фт.) или жабы (40 фт., Плавание 40 фт.)","a bat (Speed 10 ft., Fly 40 ft.), centipede (40 ft., Climb 40 ft.) or toad (40 ft., Swim 40 ft.)"),
      modern ? p("Разрывание: рукопашная атака +5, досягаемость 5 фт.; 5 (1d4 + 3) рубящего урона, цель Отравлена до начала следующего хода квазита.","Rend: melee attack +5, reach 5 ft.; 5 (1d4 + 3) Slashing damage; the target is Poisoned until the start of the quasit's next turn.") : p("Когти (Укус в зверином облике): рукопашная атака оружием +4, досягаемость 5 фт., одна цель; 5 (1d4 + 3) колющего урона. Провал спасброска Телосложения Сл 10 дополнительно наносит 5 (2d4) урона ядом и Отравляет цель на 1 минуту. В конце каждого своего хода цель повторяет спасбросок, успех прекращает эффект.","Claws (Bite in Beast form): melee weapon attack +4, reach 5 ft., one target; 5 (1d4 + 3) Piercing damage. A failed DC 10 Constitution save adds 5 (2d4) Poison damage and Poisons the target for 1 minute. It repeats the save at the end of each turn, ending the effect on success."),
      p(`Испуг (действие, 1/день): одно существо в пределах 20 фт. делает спасбросок Мудрости Сл 10; при провале Испугано на 1 минуту. Повторяет спасбросок в конце каждого своего хода, успех прекращает эффект.${modern ? " Через минуту спасбросок автоматически успешен." : " Повторный спасбросок с помехой, если квазит находится в поле зрения."}`, `Scare (action, 1/day): one creature within 20 ft. makes a DC 10 Wisdom save or is Frightened for 1 minute. It repeats the save at the end of each turn, ending the effect on success.${modern ? " After 1 minute it automatically succeeds." : " The repeat save has disadvantage if the quasit is within line of sight."}`),
      modern ? invisibleSpell : oldInvisibility("атаки или использования Испуга","it attacks or uses Scare"),
    ],modern?["invisibility-2024"]:undefined));
  PACT_FAMILIARS.push(make(edition,"pseudodragon",p("Псевдодракон","Pseudodragon"),modern?316:340,modern?14:13,modern?10:7,modern?"3d4 + 3":"2d4 + 2",[6,15,13,10,12,10],"1/4",
    p(`Крошечный Дракон, нейтрально-добрый.${modern ? "" : " Природный доспех."} Скорость 15 фт., Полёт 60 фт. Внимательность +${modern?5:3}, Скрытность +4. Слепое зрение 10 фт., Тёмное зрение 60 фт.; пассивная Внимательность ${modern?15:13}. Понимает Общий и Драконий, но не говорит.`, `Tiny Neutral Good Dragon.${modern ? "" : " Natural armor."} Speed 15 ft., Fly 60 ft. Perception +${modern?5:3}, Stealth +4. Blindsight 10 ft., Darkvision 60 ft.; passive Perception ${modern?15:13}. Understands Common and Draconic but cannot speak.`), [resistance,
      ...(modern ? [p("Мультиатака: два Укуса.","Multiattack: two Bite attacks.")] : [p("Острые чувства: преимущество на проверки Мудрости (Внимательность), основанные на зрении, слухе или обонянии. Ограниченная телепатия: магически передаёт простые мысли, эмоции и образы существам в пределах 100 фт., понимающим хотя бы один язык.","Keen Senses: advantage on Wisdom (Perception) checks relying on sight, hearing or smell. Limited Telepathy: magically shares simple ideas, emotions and images with creatures within 100 ft. that understand a language.")]),
      p("Укус: рукопашная атака +4, досягаемость 5 фт.; 4 (1d4 + 2) колющего урона.","Bite: melee attack +4, reach 5 ft.; 4 (1d4 + 2) Piercing damage."),
      modern ? p("Жало (действие): одно видимое существо в пределах 5 фт. делает спасбросок Телосложения Сл 12. Провал: 5 (2d4) урона ядом и Отравлен на 1 час. Провал на 5 или больше: пока Отравлена, цель также Без сознания; это состояние прекращается при получении урона или если существо в пределах 5 фт. действием разбудит её.","Sting (action): one visible creature within 5 ft. makes a DC 12 Constitution save. Failure: 5 (2d4) Poison damage and Poisoned for 1 hour. Failure by 5 or more: also Unconscious while Poisoned; Unconscious ends on taking damage or when a creature within 5 ft. uses an action to wake it.") : p("Жало: рукопашная атака оружием +4, досягаемость 5 фт., одно существо; 4 (1d4 + 2) колющего урона. Провал спасброска Телосложения Сл 11 Отравляет цель на 1 час. При провале на 5 или больше цель также Без сознания на этот срок, до получения урона или пока другое существо действием не разбудит её.","Sting: melee weapon attack +4, reach 5 ft., one creature; 4 (1d4 + 2) Piercing damage. A failed DC 11 Constitution save Poisons it for 1 hour. Failure by 5 or more also makes it Unconscious for that duration, until damaged or another creature uses an action to wake it."),
    ]));
  PACT_FAMILIARS.push(make(edition,"sprite",p("Спрайт","Sprite"),modern?329:348,15,modern?10:2,modern?"4d4":"1d4",[3,18,10,14,13,11],"1/4",
    p(`Крошечная Фея, нейтрально-добрая.${modern ? "" : " Кожаный доспех."} Скорость 10 фт., Полёт 40 фт. Внимательность +3, Скрытность +8; пассивная Внимательность 13. Общий, Эльфийский, Сильван.`, `Tiny Neutral Good Fey.${modern ? "" : " Leather armor."} Speed 10 ft., Fly 40 ft. Perception +3, Stealth +8; passive Perception 13. Common, Elvish, Sylvan.`), [
      modern ? p("Игольчатый меч: рукопашная атака +6, досягаемость 5 фт.; 6 (1d4 + 4) колющего урона. Чарующий лук: дальнобойная атака +6, дистанция 40/160 фт.; 1 колющего урона, цель Очарована до начала следующего хода спрайта.","Needle Sword: melee attack +6, reach 5 ft.; 6 (1d4 + 4) Piercing damage. Enchanting Bow: ranged attack +6, range 40/160 ft.; 1 Piercing damage and the target is Charmed until the start of the sprite's next turn.") : p("Длинный меч: рукопашная атака оружием +2, досягаемость 5 фт., одна цель; 1 рубящего урона. Короткий лук: дальнобойная атака оружием +6, дистанция 40/160 фт., одна цель; 1 колющего урона. Провал спасброска Телосложения Сл 10 Отравляет цель на 1 минуту. Если итог спасброска 5 или меньше, Отравленная цель также Без сознания на этот срок, до получения урона или пока другое существо действием не разбудит её.","Longsword: melee weapon attack +2, reach 5 ft., one target; 1 Slashing damage. Shortbow: ranged weapon attack +6, range 40/160 ft., one target; 1 Piercing damage. A failed DC 10 Constitution save Poisons it for 1 minute. If the total save is 5 or less, the Poisoned target also falls Unconscious for that duration, until damaged or another creature uses an action to wake it."),
      modern ? p("Взгляд в сердце (действие): одно видимое существо в пределах 5 фт. делает спасбросок Харизмы Сл 10; при провале спрайт узнаёт его эмоции и мировоззрение. Небожители, Исчадия и Нежить автоматически проваливают спасбросок.","Heart Sight (action): one visible creature within 5 ft. makes a DC 10 Charisma save. On failure the sprite learns its emotions and alignment. Celestials, Fiends and Undead automatically fail.") : p("Взгляд в сердце (действие): коснувшись существа, спрайт магически узнаёт его текущее эмоциональное состояние. Если цель проваливает спасбросок Харизмы Сл 10, узнаёт также мировоззрение; Небожители, Исчадия и Нежить автоматически проваливают спасбросок.","Heart Sight (action): on touching a creature, magically learns its current emotions. A failed DC 10 Charisma save also reveals alignment; Celestials, Fiends and Undead automatically fail."),
      modern ? invisibleSpell : oldInvisibility("атаки или сотворения заклинания","it attacks or casts a spell"),
    ],modern?["invisibility-2024"]:undefined));
}
PACT_FAMILIARS.push(make("2024","sphinx-of-wonder",p("Сфинкс любознательности","Sphinx of Wonder"),327,13,24,"7d4 + 7",[6,17,13,15,12,11],"1",
  p("Крошечный Небожитель, законно-добрый. Скорость 20 фт., Полёт 40 фт. Магия +4, Религия +4, Скрытность +5. Сопротивление некротическому, психическому урону и излучению. Тёмное зрение 60 фт.; пассивная Внимательность 11. Небесный, Общий.","Tiny Lawful Good Celestial. Speed 20 ft., Fly 40 ft. Arcana +4, Religion +4, Stealth +5. Resistance to Necrotic, Psychic and Radiant damage. Darkvision 60 ft.; passive Perception 11. Celestial, Common."), [resistance,
    p("Разрывание: рукопашная атака +5, досягаемость 5 фт.; 5 (1d4 + 3) рубящего урона и 7 (2d6) излучением.","Rend: melee attack +5, reach 5 ft.; 5 (1d4 + 3) Slashing plus 7 (2d6) Radiant damage."),
    p("Вспышка изобретательности (реакция, 2/день): когда сфинкс или другое существо в пределах 30 фт. совершает проверку характеристики или спасбросок, сфинкс добавляет к броску 2.","Burst of Ingenuity (reaction, 2/day): when the sphinx or another creature within 30 ft. makes an ability check or saving throw, add 2 to the roll."),
  ]));
PACT_FAMILIARS.push({...make("2024","slaad-tadpole",p("Слаад-головастик","Slaad Tadpole"),0,12,7,"3d4",[7,15,10,3,5,3],"1/8",
  p("Крошечная Аберрация, хаотично-нейтральная. Скорость 30 фт., Копание 10 фт. Скрытность +4. Сопротивление кислоте, холоду, огню, электричеству и грому. Тёмное зрение 60 фт.; пассивная Внимательность 7. Понимает Слаадский, но не говорит.","Tiny Chaotic Neutral Aberration. Speed 30 ft., Burrow 10 ft. Stealth +4. Resistance to Acid, Cold, Fire, Lightning and Thunder. Darkvision 60 ft.; passive Perception 7. Understands Slaad but cannot speak."), [resistance,
    p("Укус: рукопашная атака +4, досягаемость 5 фт.; 5 (1d6 + 2) колющего урона.","Bite: melee attack +4, reach 5 ft.; 5 (1d6 + 2) Piercing damage."),
  ]),sourceUrl:"https://next.dnd.su/bestiary/21553-slaad-tadpole/"});
