import type { SpellOption } from "./rules-data";
const old = (
  id: string,
  name: string,
  level: number,
  school: string,
  classes: string[],
  range: string,
  duration: string,
  concentration: boolean,
  components: string,
  descriptionRu: string,
  description: string,
  path: string,
): SpellOption => ({
  id: `${id}-2014`,
  name,
  editions: ["2014"],
  level,
  school,
  classes,
  range,
  duration,
  concentration,
  components,
  castingTime: "Action",
  ritual: false,
  summary: descriptionRu,
  descriptionRu,
  description,
  source: "Player’s Handbook (2014)",
  sourceUrl: `https://dnd.su/spells/${path}/`,
});
const summon = (
  id: string,
  name: string,
  classes: string[],
  components: string,
  variantsRu: string,
  variantsEn: string,
  path: string,
): SpellOption => ({
  ...old(
    `summon-${id}`,
    name,
    4,
    "Вызов",
    classes,
    "90 feet",
    "1 hour",
    true,
    components,
    `В видимом свободном месте появляется дружественный вам и союзникам дух. ${variantsRu} Его полный статблок приведён здесь. Инициатива как ваша, ход сразу после вас. Выполняет устные команды без вашего действия; без команд Уклоняется и движется, избегая опасности. Исчезает при 0 хитов или окончании заклинания. Формулы статблока используют круг потраченной ячейки.`,
    `A spirit friendly to you and your allies appears in a visible unoccupied space. ${variantsEn} Its full stat block is included. It shares your Initiative and acts immediately after you. It follows verbal commands without costing you an action; otherwise it Dodges and moves to avoid danger. It disappears at 0 HP or when the spell ends. Stat-block formulas use the expended slot level.`,
    path,
  ),
  source: "Tasha’s Cauldron of Everything",
  creatureReferenceIds: [
    `${id === "aberration" ? "aberrant" : id}-spirit-2014`,
  ],
});
export const SORCERER_SPELLS: SpellOption[] = [
  old(
    "dissonant-whispers",
    "Диссонирующий шёпот · Dissonant Whispers",
    1,
    "Очарование",
    ["bard"],
    "60 feet",
    "Instantaneous",
    false,
    "V",
    "Цель в дистанции делает спасбросок Мудрости. Провал: 3d6 психического урона и, если реакция доступна, немедленно тратит её на движение от вас до своей скорости, избегая очевидных опасностей. Успех: только половина урона. Глухая цель автоматически преуспевает. За круг ячейки выше первого добавьте 1d6 урона.",
    "A creature within range makes a Wisdom save. Failure deals 3d6 Psychic damage and forces it to use its Reaction, if available, to move as far from you as its Speed allows, avoiding obvious hazards. Success halves the damage and prevents the movement. A Deafened creature succeeds automatically. Add 1d6 damage per slot level above 1.",
    "56-dissonant_whisper",
  ),
  {
    ...old(
      "mind-sliver",
      "Расщепление разума · Mind Sliver",
      0,
      "Очарование",
      ["wizard", "warlock", "sorcerer"],
      "60 feet",
      "1 round",
      false,
      "V",
      "Видимая цель при провале спасброска Интеллекта получает 1d6 психического урона и вычитает d4 из следующего спасброска до конца вашего следующего хода. Урон 2d6 на уровне персонажа 5, 3d6 на 11, 4d6 на 17.",
      "A visible creature makes an Intelligence save. Failure deals 1d6 Psychic damage and subtracts 1d4 from its next saving throw before your next turn ends. Damage increases to 2d6 at character level 5, 3d6 at 11, and 4d6 at 17.",
      "3050-mind_sliver",
    ),
    source: "Tasha’s Cauldron of Everything",
  },
  old(
    "arms-of-hadar",
    "Руки Хадара · Arms of Hadar",
    1,
    "Вызов",
    ["warlock"],
    "Self (10 feet)",
    "Instantaneous",
    false,
    "V, S",
    "Каждое существо в 10 фт. делает спасбросок Силы. Провал: 2d6 некротического урона и невозможность реакций до его следующего хода. Успех: половина урона без запрета реакций. За круг ячейки выше первого добавьте 1d6 урона.",
    "Each creature within 10 feet makes a Strength save. Failure deals 2d6 Necrotic damage and prevents Reactions until its next turn. Success halves the damage without affecting Reactions. Add 1d6 damage per slot level above 1.",
    "305-arms_of_hadar",
  ),
  old(
    "hunger-of-hadar",
    "Голод Хадара · Hunger of Hadar",
    3,
    "Вызов",
    ["warlock"],
    "150 feet",
    "1 minute",
    true,
    "V, S, M (pickled octopus tentacle)",
    "Сфера радиусом 20 фт. с центром в выбранной точке заполнена чернотой и холодом; шёпот и шум слышны в 30 фт. от неё. Ни обычный, ни магический свет не освещает её; существа, полностью оказавшиеся внутри, ослеплены. Область — трудная местность. Начавший ход внутри получает 2d6 холодного урона. Завершающий ход внутри делает спасбросок Ловкости: провал наносит 2d6 кислотного урона.",
    "A 20-foot-radius sphere of blackness and cold appears at a point within range, with noises audible 30 feet away. No mundane or magical light illuminates it, and creatures fully within are Blinded. The area is Difficult Terrain. Starting a turn inside deals 2d6 Cold damage. Ending a turn inside requires a Dexterity save, dealing 2d6 Acid damage on failure.",
    "47-hunger_of_hadar",
  ),
  summon(
    "aberration",
    "Призыв духа аберрации · Summon Aberration",
    ["wizard", "warlock"],
    "V, S, M (pickled tentacle and eyeball in a platinum-inlaid vial worth 400+ GP)",
    "Выберите бехолдера, слаада или звёздное порождение.",
    "Choose Beholderkin, Slaad, or Star Spawn.",
    "3062-summon_aberration",
  ),
  summon(
    "construct",
    "Призыв духа конструкта · Summon Construct",
    ["wizard", "artificer"],
    "V, S, M (ornate stone and metal lockbox worth 400+ GP)",
    "Выберите глину, металл или камень; облик голема или модрона.",
    "Choose Clay, Metal, or Stone and a golem or modron appearance.",
    "3065-summon_construct",
  ),
  {
    id: "aura-of-vitality-2024",
    name: "Аура живучести · Aura of Vitality",
    editions: ["2024"],
    level: 3,
    school: "Ограждение",
    classes: ["druid", "cleric", "paladin"],
    castingTime: "Action",
    range: "Self",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: "V",
    source: "Player’s Handbook (2024)",
    sourceUrl: "https://next.dnd.su/spells/10437-aura-of-vitality",
    summary:
      "Эманация 30 фт.: лечение 2d6 при появлении и в начале ваших ходов.",
    descriptionRu:
      "Создайте движущуюся с вами эманацию 30 фт. При сотворении и в начале каждого своего хода до окончания заклинания можете восстановить 2d6 хитов одному существу внутри.",
    description:
      "Create a 30-foot Emanation that moves with you. When it appears and at the start of each of your turns during the duration, you may restore 2d6 HP to one creature within it.",
  },
  {
    id: "summon-beast-2024",
    name: "Вызов зверя · Summon Beast",
    editions: ["2024"],
    level: 2,
    school: "Вызов",
    classes: ["druid", "ranger"],
    castingTime: "Action",
    range: "90 feet",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components:
      "V, S, M (feather, fur and fish tail in a gilded acorn worth 200+ GP)",
    source: "Player’s Handbook (2024)",
    sourceUrl: "https://next.dnd.su/spells/10304-summon-beast",
    creatureReferenceIds: ["bestial-spirit-2024"],
    summary:
      "Призыв духа зверя Воздуха, Земли или Воды; полный статблок встроен.",
    descriptionRu:
      "В видимом свободном месте в дистанции появляется Дух зверя. Выберите Воздух, Землю или Воду и внешний вид соответствующего животного; используйте встроенный статблок. Он дружественен вам и союзникам, ходит сразу после вас с вашей инициативой и выполняет устные команды без вашего действия. Без команд Уклоняется и движется, избегая опасности. Исчезает при 0 хитов либо окончании заклинания. Все формулы статблока используют круг потраченной ячейки.",
    description:
      "A Bestial Spirit appears in a visible unoccupied space within range. Choose Air, Land, or Water and the appearance of an appropriate animal; use the included stat block. It is allied with you and your allies, shares your Initiative, and acts immediately after you. It follows verbal commands without costing you an action. Without commands it Dodges and moves to avoid danger. It disappears at 0 HP or when the spell ends. All spell-level formulas in its stat block use the expended slot level.",
  },
];
