import type { SpellOption } from "./rules-data";
import type { RuleLanguage } from "./random-effect-tables";

const materials: Record<string, string> = {
  "for each creature you affect with this spell, you must provide one jacinth worth at least 1,000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes": "для каждого затронутого существа гиацинт стоимостью не менее 1000 зм и украшенный резьбой серебряный слиток стоимостью не менее 100 зм; всё расходуется заклинанием",
  "a diamond worth at least 5,000 gp": "алмаз стоимостью не менее 5000 зм",
  "a vellum depiction or a carved statuette in the likeness of the target, and a special component that varies according to the version of the spell you choose, worth at least 500 gp per Hit Die of the target": "изображение цели на пергаменте или резная статуэтка, а также особый компонент выбранной версии стоимостью не менее 500 зм за каждую Кость хитов цели",
  "a jade circlet worth at least 1,500 gp, which you must place on your head before you cast the spell": "нефритовый обруч стоимостью не менее 1500 зм, который перед сотворением нужно надеть на голову",
  "a sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes": "немного святой воды и алмазы стоимостью не менее 25000 зм, расходуемые заклинанием",
  "for each of the spell’s targets, one jacinth worth 1,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes": "для каждой цели гиацинт стоимостью не менее 1000 зм и серебряный слиток стоимостью не менее 100 зм; всё расходуется заклинанием",
  "a hummingbird feather": "перо колибри",
  "a diamond worth 5,000+ GP": "алмаз стоимостью не менее 5000 зм",
  "a statuette of the target worth 5,000+ GP": "статуэтка цели стоимостью не менее 5000 зм",
  "a jade circlet worth 1,500+ GP": "нефритовый обруч стоимостью не менее 1500 зм",
  "a drop of mercury, a dollop of gum arabic, and a wisp of smoke": "капля ртути, немного гуммиарабика и струйка дыма",
  "diamonds worth 25,000+ GP, which the spell consumes": "алмазы стоимостью не менее 25000 зм, расходуемые заклинанием",
  "either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect": "кусочек квасцов, пропитанный уксусом, для антипатии или капля мёда для симпатии",
  "a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold the creature being cloned, such as a huge urn, coffin, mud- filled cyst in the ground, or crystal container filled with salt water": "алмаз стоимостью не менее 1000 зм и хотя бы кубический дюйм плоти клонируемого существа, расходуемые заклинанием; сосуд с закрываемой крышкой стоимостью не менее 2000 зм, вмещающий это существо, например огромная урна, гроб, полость в земле с грязью или хрустальный сосуд с солёной водой",
  "burning incense and bits of earth and wood mixed in water": "горящие благовония и кусочки земли и дерева, смешанные с водой",
  "a pinch of dirt, a piece of rock, and a lump of clay": "щепотка земли, кусочек камня и комок глины",
  "a handful of clay, crystal, glass, or mineral spheres": "горсть глиняных, хрустальных, стеклянных или минеральных шариков",
  "a tiny reliquary worth at least 1,000 gp containing a sacred relic, such as a scrap of cloth from a saint’s robe or a piece of parchment from a religious text": "крошечный реликварий стоимостью не менее 1000 зм со священной реликвией, например лоскутом одежды святого или фрагментом пергамента религиозного текста",
  "fire and a piece of sunstone": "огонь и кусочек солнечного камня",
  "a mix of vinegar and honey": "смесь уксуса и мёда",
  "a key ring with no keys": "кольцо для ключей без ключей",
  "a diamond worth 1,000+ GP, which the spell consumes, and a sealable vessel worth 2,000+ GP that is large enough to hold the creature being cloned": "алмаз стоимостью не менее 1000 зм, расходуемый заклинанием, и закрываемый сосуд стоимостью не менее 2000 зм, вмещающий клонируемое существо",
  "a fractured rock": "расколотый камень",
  "a reliquary worth 1,000+ GP": "реликварий стоимостью не менее 1000 зм",
  "a piece of sunstone": "кусочек солнечного камня",
  "a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp": "миниатюрный платиновый меч с рукоятью и навершием из меди и цинка стоимостью 250 зм",
  "ruby dust worth 1,500 gp": "рубиновая пыль стоимостью 1500 зм",
  "a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp": "миниатюрный портал из слоновой кости, кусочек полированного мрамора и крошечная серебряная ложка; каждый предмет стоимостью не менее 5 зм",
  "a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence": "раздвоенный металлический стержень стоимостью не менее 250 зм, настроенный на определённый план существования",
  "a small replica of you made from materials worth at least 5 gp": "ваша миниатюрная копия из материалов стоимостью не менее 5 зм",
  "a prayer wheel and holy water": "молитвенное колесо и святая вода",
  "a diamond worth at least 1,000 gp, which the spell consumes": "алмаз стоимостью не менее 1000 зм, расходуемый заклинанием",
  "a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes": "смесь алмазной, изумрудной, рубиновой и сапфировой пыли стоимостью не менее 5000 зм, расходуемая заклинанием",
  "snow or ice in quantities sufficient to made a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature’s body placed inside the snow or ice; and powdered ruby worth 1,500 gp, sprinkled over the duplicate and consumed by the spell": "снег или лёд для копии существа в натуральную величину; волосы, обрезки ногтей или другая часть тела оригинала, помещённая внутрь; рубиновая пыль стоимостью 1500 зм, которой посыпают копию и которую расходует заклинание",
  "mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes": "ртуть, фосфор, алмазная и опаловая пыль общей стоимостью не менее 1000 зм, расходуемые заклинанием",
  "a miniature sword worth 250+ GP": "миниатюрный меч стоимостью не менее 250 зм",
  "ruby dust worth 1,500+ GP, which the spell consumes": "рубиновая пыль стоимостью не менее 1500 зм, расходуемая заклинанием",
  "a miniature door worth 15+ GP": "миниатюрная дверь стоимостью не менее 15 зм",
  "a forked, metal rod worth 250+ GP and attuned to a plane of existence": "раздвоенный металлический стержень стоимостью не менее 250 зм, настроенный на план существования",
  "a statuette of yourself worth 5+ GP": "изображающая вас статуэтка стоимостью не менее 5 зм",
  "a prayer wheel": "молитвенное колесо",
  "a diamond worth 1,000+ GP, which the spell consumes": "алмаз стоимостью не менее 1000 зм, расходуемый заклинанием",
  "a lodestone and iron filings": "магнитный железняк и железные опилки",
  "gem dust worth 5,000+ GP, which the spell consumes": "пыль драгоценных камней стоимостью не менее 5000 зм, расходуемая заклинанием",
  "powdered ruby worth 1,500+ GP, which the spell consumes": "рубиновая пыль стоимостью не менее 1500 зм, расходуемая заклинанием",
  "powdered diamond worth 1,000+ GP, which the spell consumes": "алмазная пыль стоимостью не менее 1000 зм, расходуемая заклинанием",
  "a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins": "кусочек меха; янтарь, стекло или хрустальный стержень; три серебряные булавки",
  "the powder of a crushed black pearl worth at least 500 gp": "порошок из чёрной жемчужины стоимостью не менее 500 зм",
  "a statuette of yourself carved from ivory and decorated with gems worth at least 1,500 gp": "изображающая вас статуэтка из слоновой кости с драгоценными камнями стоимостью не менее 1500 зм",
  "one clay pot filled with grave dirt, one clay pot filled with brackish water, and one 150 gp black onyx stone for each corpse": "глиняный горшок с могильной землёй, глиняный горшок с солоноватой водой и по одному чёрному ониксу стоимостью 150 зм на каждый труп",
  "a lodestone and a pinch of dust": "магнитный железняк и щепотка пыли",
  "a set of divinatory tools— such as bones, ivory sticks, cards, teeth, or carved runes—worth 100 gp and an object from the location you wish to find": "набор гадальных принадлежностей, например костей, палочек слоновой кости, карт, зубов или резных рун, стоимостью 100 зм и предмет из искомого места",
  "a pinch of lime, water, and earth": "щепотка извести, вода и земля",
  "a sprinkling of holy water, rare incense, and powdered ruby worth at least 1,000 gp": "немного святой воды, редкие благовония и рубиновая пыль стоимостью не менее 1000 зм",
  "a small crystal sphere": "маленькая хрустальная сфера",
  "a glass or crystal bead that shatters when the spell ends": "стеклянная или хрустальная бусина, разбивающаяся при окончании заклинания",
  "burning incense, a small measure of brimstone and oil, a knotted string, a small amount of umber hulk blood, and a small silver rod worth at least 10 gp": "горящие благовония, немного серы и масла, завязанная узлами верёвочка, немного крови бурого увальня и маленький серебряный стержень стоимостью не менее 10 зм",
  "a gem-encrusted bowl worth at least 1,000 gp, which the spell consumes": "украшенная драгоценными камнями чаша стоимостью не менее 1000 зм, расходуемая заклинанием",
  "a sapphire worth 1,000 gp": "сапфир стоимостью 1000 зм",
  "a gem, crystal, reliquary, or some other ornamental container worth at least 500 gp": "драгоценный камень, кристалл, реликварий или иной декоративный сосуд стоимостью не менее 500 зм",
  "an iron blade and a small bag containing a mixture of soils—clay, loam, and sand": "железный клинок и мешочек со смесью глины, суглинка и песка",
  "a bit of fleece and jade dust worth at least 25 gp": "кусочек овечьей шерсти и нефритовая пыль стоимостью не менее 25 зм",
  "an ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell": "глазная мазь стоимостью 25 зм из грибного порошка, шафрана и жира, расходуемая заклинанием",
  "a small piece of quartz": "маленький кусочек кварца",
  "fire and holy water": "огонь и святая вода",
  "three silver pins": "три серебряные булавки",
  "the powder of a crushed black pearl worth 500+ GP": "порошок из чёрной жемчужины стоимостью не менее 500 зм",
  "a gem-encrusted statuette of yourself worth 1,500+ GP": "украшенная драгоценными камнями статуэтка, изображающая вас, стоимостью не менее 1500 зм",
  "one 150+ GP black onyx stone for each corpse": "по одному чёрному ониксу стоимостью не менее 150 зм на каждый труп",
  "a set of divination tools—such as cards or runes—worth 100+ GP": "набор инструментов для гадания, например карты или руны, стоимостью не менее 100 зм",
  "a cockatrice feather": "перо кокатриса",
  "ruby dust worth 1,000+ GP": "рубиновая пыль стоимостью не менее 1000 зм",
  "a miniature crystal sphere": "миниатюрная хрустальная сфера",
  "a glass bead": "стеклянная бусина",
  "a silver rod worth 10+ GP": "серебряный стержень стоимостью не менее 10 зм",
  "a gem-encrusted bowl worth 1,000+ GP, which the spell consumes": "украшенная драгоценными камнями чаша стоимостью не менее 1000 зм, расходуемая заклинанием",
  "a sapphire worth 1,000+ GP": "сапфир стоимостью не менее 1000 зм",
  "a gem, crystal, or reliquary worth 500+ GP": "драгоценный камень, кристалл или реликварий стоимостью не менее 500 зм",
  "a snake’s tongue": "змеиный язык",
  "jade dust worth 25+ GP": "нефритовая пыль стоимостью не менее 25 зм",
  "a magnifying glass": "увеличительное стекло",
  "mushroom powder worth 25+ GP, which the spell consumes": "грибной порошок стоимостью не менее 25 зм, расходуемый заклинанием",
  "a piece of quartz": "кусочек кварца",
  "a handful of thorns": "горсть колючек",
  "an eggshell and a snakeskin glove": "яичная скорлупа и перчатка из змеиной кожи",
  "an agate worth at least 1,000 gp, which the spell consumes": "агат стоимостью не менее 1000 зм, расходуемый заклинанием",
  "incense and a vial of holy or unholy water": "благовония и флакон святой или нечестивой воды",
  "burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water": "горящие благовония для воздуха, мягкая глина для земли, сера и фосфор для огня либо вода и песок для воды",
  "a tiny piece of matter of the same type of the item you plan to create": "крошечный кусочек материала того же типа, что и создаваемый предмет",
  "a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird": "горсть песка, капля чернил и писчее перо, выдернутое у спящей птицы",
  "pinch of sulfur": "щепотка серы",
  "diamond dust worth at least 100 gp, which the spell consumes": "алмазная пыль стоимостью не менее 100 зм, расходуемая заклинанием",
  "herbs, oils, and incense worth at least 1,000 gp, which the spell consumes": "травы, масла и благовония стоимостью не менее 1000 зм, расходуемые заклинанием",
  "a few grains of sugar, some kernels of grain, and a smear of fat": "несколько крупинок сахара, немного зерна и кусочек жира",
  "incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each": "благовония стоимостью не менее 250 зм, расходуемые заклинанием, и четыре полоски слоновой кости стоимостью не менее 50 зм каждая",
  "a jewel worth at least 1,000 gp, which the spell consumes": "драгоценный камень стоимостью не менее 1000 зм, расходуемый заклинанием",
  "a diamond worth at least 500 gp, which the spell consumes": "алмаз стоимостью не менее 500 зм, расходуемый заклинанием",
  "a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water": "фокусировка стоимостью не менее 1000 зм, например хрустальный шар, серебряное зеркало или чаша со святой водой",
  "pieces of eggshell from two different kinds of creatures": "кусочки яичной скорлупы двух разных видов существ",
  "rare chalks and inks infused with precious gems with 50 gp, which the spell consumes": "редкие мелки и чернила с драгоценными камнями стоимостью 50 зм, расходуемые заклинанием",
  "a pinch of powder made by crushing a clear gemstone": "щепотка порошка из прозрачного драгоценного камня",
  "a small block of granite": "маленький брусок гранита",
  "incense worth 250+ GP, which the spell consumes, and four ivory strips worth 50+ GP each": "благовония стоимостью не менее 250 зм, расходуемые заклинанием, и четыре полоски слоновой кости стоимостью не менее 50 зм каждая",
  "a pinch of sesame seeds": "щепотка кунжутных семян",
  "a jewel worth 1,000+ GP, which the spell consumes": "драгоценный камень стоимостью не менее 1000 зм, расходуемый заклинанием",
  "a diamond worth 500+ GP, which the spell consumes": "алмаз стоимостью не менее 500 зм, расходуемый заклинанием",
  "two eggs": "два яйца",
  "rare inks worth 50+ GP, which the spell consumes": "редкие чернила стоимостью не менее 50 зм, расходуемые заклинанием",
  "a cube of granite": "кубик гранита",
  "an eggshell and a glove": "яичная скорлупа и перчатка",
  "an agate worth 1,000+ GP, which the spell consumes": "агат стоимостью не менее 1000 зм, расходуемый заклинанием",
  "incense": "благовония",
  "a small crystal or glass cone": "маленький хрустальный или стеклянный конус",
  "a paintbrush": "кисть для рисования",
  "a pinch of sulfur": "щепотка серы",
  "incense worth 1,000+ GP, which the spell consumes": "благовония стоимостью не менее 1000 зм, расходуемые заклинанием",
  "an item distasteful to the target": "предмет, неприятный цели",
  "a piece of tentacle from a giant octopus or a giant squid": "кусочек щупальца гигантского осьминога или кальмара",
  "one holly berry per creature summoned": "по ягоде падуба на каждое призванное существо",
  "a drop of water and a pinch of dust": "капля воды и щепотка пыли",
  "incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes": "благовония и подходящее вашей религии жертвоприношение общей стоимостью не менее 25 зм, расходуемые заклинанием",
  "a tiny silver whistle, a piece of bone, and a thread": "крошечный серебряный свисток, кусочек кости и нить",
  "a leather strap, bound around the arm or a similar appendage": "кожаный ремешок, обвязанный вокруг руки или подобной конечности",
  "a stone, a twig, and a bit of green plant": "камень, веточка и кусочек зелёного растения",
  "a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite": "тонкий лист свинца, кусочек непрозрачного стекла, комок хлопка или ткани и порошок хризолита",
  "a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic": "полусфера прозрачного хрусталя и подходящая полусфера гуммиарабика",
  "an exquisite chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth at least 5,000 gp, and a Tiny replica made from the same materials worth at least 50 gp": "изысканный сундук размером 3 на 2 на 2 фт. из редких материалов стоимостью не менее 5000 зм и его Крошечная копия из тех же материалов стоимостью не менее 50 зм",
  "soft clay, which must be worked into roughly the desired shape of the stone object": "мягкая глина, которой нужно придать приблизительно желаемую форму каменного предмета",
  "diamond dust worth 100 gp, which the spell consumes": "алмазная пыль стоимостью 100 зм, расходуемая заклинанием",
  "a small piece of phosphorus": "маленький кусочек фосфора",
  "a bit of bat fur": "клочок меха летучей мыши",
  "a pentacle": "пентакль",
  "a tentacle": "щупальце",
  "a mixture of water and dust": "смесь воды и пыли",
  "incense worth 25+ GP, which the spell consumes": "благовония стоимостью не менее 25 зм, расходуемые заклинанием",
  "a silver whistle": "серебряный свисток",
  "a bit of phosphorus or a firefly": "немного фосфора или светлячок",
  "a mushroom": "гриб",
  "a mitten": "рукавица",
  "a chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth 5,000+ GP, and a Tiny replica of the chest made from the same materi- als worth 50+ GP": "сундук размером 3 на 2 на 2 фт. из редких материалов стоимостью не менее 5000 зм и его Крошечная копия из тех же материалов стоимостью не менее 50 зм",
  "a drop of bile": "капля желчи",
  "a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing": "фокусировка стоимостью не менее 100 зм: украшенный камнями рог для слуха или стеклянный глаз для зрения",
  "a white feather or the heart of a hen": "белое перо или куриное сердце",
  "a bit of gauze and a wisp of smoke": "кусочек марли и струйка дыма",
  "a glowing stick of incense or a crystal vial filled with phosphorescent material": "светящаяся палочка благовоний или хрустальный флакон с фосфоресцирующим веществом",
  "a bit of fur and a rod of amber, crystal, or glass": "клочок меха и жезл из янтаря, хрусталя или стекла",
  "holy water or powdered silver and iron worth at least 100 gp, which the spell consumes": "святая вода или порошки серебра и железа стоимостью не менее 100 зм, расходуемые заклинанием",
  "a pinch of diamond dust worth 25 gp sprinkled over the target, which the spell consumes": "щепотка алмазной пыли стоимостью 25 зм, которой посыпают цель; расходуется заклинанием",
  "diamonds worth 300 gp, which the spell consumes": "алмазы стоимостью 300 зм, расходуемые заклинанием",
  "a pinch of dust and a few drops of water": "щепотка пыли и несколько капель воды",
  "a holy symbol": "священный символ",
  "a rotten egg or several skunk cabbage leaves": "тухлое яйцо или несколько листьев симплокарпуса",
  "a small crystal bead": "маленькая хрустальная бусина",
  "a small clay model of a ziggurat": "маленькая глиняная модель зиккурата",
  "a short reed or piece of straw": "короткий стебель тростника или соломинка",
  "a tiny fan and a feather of exotic origin": "крошечный веер и экзотическое перо",
  "a drop of blood, a piece of flesh, and a pinch of bone dust": "капля крови, кусочек плоти и щепотка костной пыли",
  "a white feather": "белое перо",
  "powdered diamond worth 200+ GP, which the spell consumes": "алмазная пыль стоимостью не менее 200 зм, расходуемая заклинанием",
  "a pinch of confetti": "щепотка конфетти",
  "a bit of fur and a crystal rod": "клочок меха и хрустальный жезл",
  "salt and powdered silver worth 100+ GP, which the spell consumes": "соль и серебряный порошок стоимостью не менее 100 зм, расходуемые заклинанием",
  "a diamond worth 300+ GP, which the spell consumes": "алмаз стоимостью не менее 300 зм, расходуемый заклинанием",
  "a miniature umbrella": "миниатюрный зонтик",
  "a drop of molasses": "капля патоки",
  "burning incense": "горящие благовония",
  "a rotten egg": "тухлое яйцо",
  "a miniature ziggurat": "миниатюрный зиккурат",
  "a short reed": "короткий стебель тростника",
  "cup of water": "чашка воды",
  "miniature tiara": "миниатюрная тиара",
  "pickled tentacle": "маринованное щупальце",
  "gilded flower worth at least 300 GP": "позолоченный цветок стоимостью не менее 300 зм",
  "a pinch of graveyard dirt": "щепотка кладбищенской земли",
  "a reliquary worth 500+ GP": "реликварий стоимостью не менее 500 зм",
  "air, a pebble, ash, and water in a gold-inlaid vial worth at least 400 GP": "воздух, камешек, пепел и вода в инкрустированном золотом флаконе стоимостью не менее 400 зм",
  "gilded skull worth 300+ GP": "позолоченный череп стоимостью не менее 300 зм",
  "a melee weapon worth at least 1 SP": "рукопашное оружие стоимостью не менее 1 см",
  "a stem from a thorny plant": "стебель колючего растения",
  "25 feet of rope, consumed": "25 фт. верёвки, расходуемой заклинанием",
  "a bit of rotten food": "кусочек гнилой пищи",
  "a twig struck by lightning": "веточка, в которую ударила молния",
  "a pinch of sand": "щепотка песка",
  "a thrown weapon or one piece of ammunition": "метательное оружие или один боеприпас",
  "a melee or ranged weapon worth at least 1 CP": "рукопашное или дальнобойное оружие стоимостью не менее 1 мм",
  "a silk flag worth at least 100 GP": "шёлковый флаг стоимостью не менее 100 зм",
  "a black lantern": "чёрный фонарь",
  "a distorting lens": "искажающая линза",
  "clay and water": "глина и вода",
  "a gem worth at least 100 GP": "драгоценный камень стоимостью не менее 100 зм",
  "a crystal rod worth at least 5000 GP, consumed": "хрустальный жезл стоимостью не менее 5000 зм, расходуемый заклинанием",
  "melee weapon worth 1+ SP": "рукопашное оружие стоимостью не менее 1 см",
  "powdered rhubarb leaf and an adder’s stomach": "порошок листа ревеня и желудок гадюки",
  "a tiny strip of white cloth": "маленькая полоска белой ткани",
  "specially marked sticks, bones, or similar tokens worth at least 25 gp": "особо размеченные палочки, кости или подобные принадлежности стоимостью не менее 25 зм",
  "a handful of oak bark": "горсть дубовой коры",
  "ruby dust worth 50 gp, which the spell consumes": "рубиновая пыль стоимостью 50 зм, расходуемая заклинанием",
  "bat fur and a drop of pitch or piece of coal": "мех летучей мыши и капля смолы или кусочек угля",
  "either a pinch of dried carrot or an agate": "щепотка сушёной моркови или агат",
  "fur or a feather from a beast": "мех или перо зверя",
  "leaf of sumac": "лист сумаха",
  "a bit of tallow, a pinch of brimstone, and a dusting of powdered iron": "немного сала, щепотка серы и железного порошка",
  "a pinch of salt and one copper piece placed on each of the corpse’s eyes, which must remain there for the duration": "щепотка соли и по одной медной монете на каждом глазу трупа; монеты остаются там всё время действия",
  "a small, straight piece of iron": "маленький прямой кусочек железа",
  "an eyelash encased in gum arabic": "ресница в гуммиарабике",
  "a bit of fur from a bloodhound": "клочок шерсти ищейки",
  "a small bit of honeycomb and jade dust worth at least 10 gp, which the spell consumes": "кусочек медовых сот и нефритовая пыль стоимостью не менее 10 зм, расходуемые заклинанием",
  "several seeds of any moonseed plant and a piece of opalescent feldspar": "несколько семян луносемянника и кусочек опалесцирующего полевого шпата",
  "powdered corn extract and a twisted loop of parchment": "порошок кукурузного экстракта и скрученная петля пергамента",
  "a pinch of talc and a small sprinkling of powdered silver": "щепотка талька и немного серебряного порошка",
  "seven sharp thorns or seven small twigs, each sharpened to a point": "семь острых колючек или семь маленьких заострённых веточек",
  "a pair of platinum rings worth at least 50 gp each, which you and the target must wear for the duration": "пара платиновых колец стоимостью не менее 50 зм каждое, которые вы и цель должны носить всё время действия",
  "a segment of rope": "отрезок верёвки",
  "a chip of mica": "кусочек слюды",
  "a drop of bitumen and a spider": "капля битума и паук",
  "seven thorns": "семь колючек",
  "a pair of platinum rings worth 50+ GP each, which you and the target must wear for the duration": "пара платиновых колец стоимостью не менее 50 зм каждое, которые вы и цель должны носить всё время действия",
  "a sumac leaf": "лист сумаха",
  "a ball of wax": "восковой шарик",
  "2 Copper Pieces, which the spell consumes": "2 медные монеты, расходуемые заклинанием",
  "a piece of iron and a flame": "кусочек железа и пламя",
  "a straight piece of iron": "прямой кусочек железа",
  "an eyelash in gum arabic": "ресница в гуммиарабике",
  "fur from a bloodhound": "шерсть ищейки",
  "a forked twig": "раздвоенная веточка",
  "jade dust worth 10+ GP, which the spell consumes": "нефритовая пыль стоимостью не менее 10 зм, расходуемая заклинанием",

  "powdered rhubarb leaf": "порошок листа ревеня",
  "a strip of white cloth": "полоска белой ткани",
  "a small square of silk": "маленький квадратный кусочек шёлка",
  "specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP": "особо размеченные палочки, кости, карты или другие гадательные принадлежности стоимостью не менее 25 зм",
  "ruby dust worth 50+ GP, which the spell consumes": "рубиновая пыль стоимостью не менее 50 зм, расходуемая заклинанием",
  "bat fur and a piece of coal": "мех летучей мыши и кусочек угля",
  "a dried carrot": "сушёная морковь",
  "fur or a feather": "мех или перо",

  "a sprinkling of holy water": "капли святой воды",
  "a pinch of powder or sand that is colored red, yellow, and blue": "щепотка порошка или песка красного, жёлтого и синего цветов",
  "a drop of water if creating water or a few grains of sand if destroying it": "капля воды при создании или несколько песчинок при уничтожении воды",
  "a small amount of alcohol or distilled spirits": "немного алкоголя или крепкого спиртного",
  "a pearl worth at least 100 gp and an owl feather": "жемчужина стоимостью не менее 100 зм и совиное перо",
  "holy water or powdered silver and iron, which the spell consumes": "святая вода или серебряный и железный порошки, расходуемые заклинанием",
  "a small silver mirror": "маленькое серебряное зеркало",
  "a small parchment with a bit of holy text written on it": "небольшой пергамент с отрывком священного текста",
  "a pinch of fine sand, rose petals, or a cricket": "щепотка мелкого песка, лепестки роз или сверчок",
  "a piece of string and a bit of wood": "кусочек верёвки и дерева",
  "tiny tarts and a feather that is waved in the air": "маленькие пирожные и перо, которым размахивают в воздухе",
  "a lead-­‐‑based ink worth at least 10 gp, which the spell consumes": "чернила на основе свинца стоимостью не менее 10 зм, расходуемые заклинанием",

  "10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier": "древесный уголь, благовония и травы стоимостью 10 зм, сжигаемые в латунной жаровне",
  "a bell and silver wire": "колокольчик и серебряная проволока",
  "a drop of blood": "капля крови",
  "a diamond worth 50+ GP": "алмаз стоимостью не менее 50 зм",
  "a pinch of colorful sand": "щепотка разноцветного песка",
  "a mix of water and sand": "смесь воды и песка",
  "a yew leaf": "лист тиса",
  "a drop of alcohol": "капля алкоголя",
  "a small feather or piece of down": "маленькое перо или кусочек пуха",
  "burning incense worth 10+ GP, which the spell consumes": "горящие благовония стоимостью не менее 10 зм, расходуемые заклинанием",
  "a drop of mercury": "капля ртути",
  "a sprig of mistletoe": "веточка омелы",
  "the petrified eye of a newt": "окаменевший глаз тритона",
  "a tart and a feather": "пирожное и перо",
  "a drop of water or a piece of ice": "капля воды или кусочек льда",
  "ink worth 10+ GP, which the spell consumes": "чернила стоимостью не менее 10 зм, расходуемые заклинанием",
  "a pinch of dirt": "щепотка земли",
  "a shard of glass from a mirror": "осколок зеркала",
  "a pinch of sand or rose petals": "щепотка песка или лепестки роз",
  "a bit of string and of wood": "кусочек верёвки и дерева",

  "a bit of phosphorus or wychwood, or a glowworm": "немного фосфора, древесины вяза или светлячок",
  "a miniature cloak": "миниатюрный плащ",
  "mistletoe, a shamrock leaf, and a club or quarterstaff": "омела, лист клевера и дубинка или боевой посох",
  "a bit of fleece": "клочок шерсти",
  "a bit of phosphorus": "немного фосфора",
  "a weapon with which you have profi- ciency and that is worth 1+ CP": "оружие, которым вы владеете, стоимостью не менее 1 мм",
  "a focus worth 100+ GP, either a jeweled horn for hearing or a glass eye for seeing": "фокусировка стоимостью не менее 100 зм: украшенный камнями рог для слуха или стеклянный глаз для зрения",
  "a bit of gauze": "кусочек марли",
  "a shaving of licorice root": "стружка корня солодки",
  "a locust": "саранча",
  "an object with the image of a dragon engraved on it worth 500+ GP": "предмет с выгравированным изображением дракона стоимостью не менее 500 зм",
  "air, pebble, ash and water in a gold-inlaid vial worth 400+ GP": "воздух, камешек, пепел и вода во флаконе с золотой инкрустацией стоимостью не менее 400 зм",
  "a Holy Symbol worth 5+ GP": "священный символ стоимостью не менее 5 зм",
  "diamond dust worth 100+ GP, which the spell consumes": "алмазная пыль стоимостью не менее 100 зм, расходуемая заклинанием",
  "a candle": "свеча",
  "a piece of cured leather": "кусочек выделанной кожи",
  "a crystal bead": "хрустальная бусина",
  "a thin sheet of lead": "тонкий лист свинца",
  "a glass sphere": "стеклянная сфера",
  "a shard of glass": "осколок стекла",
  "a miniature shovel": "миниатюрная лопата",
  "a focus worth 1,000+ GP, such as a crystal ball, mirror, or water-filled font": "фокусировка стоимостью не менее 1000 зм, например хрустальный шар, зеркало или наполненная водой чаша",
  "soft clay": "мягкая глина",
  "a fan and a feather": "веер и перо",
  "a piece of charcoal": "кусочек древесного угля",
  "a lodestone and dust": "магнетит и пыль",
  "a pinch of diamond dust worth 25+ GP, which the spell consumes": "щепотка алмазной пыли стоимостью не менее 25 зм, расходуемая заклинанием",
  "a handful of sand": "горсть песка",
  "gold dust worth 25+ GP, which the spell consumes": "золотая пыль стоимостью не менее 25 зм, расходуемая заклинанием",
  "mistletoe": "омела",
  "a handful of bark": "горсть коры",
  "a flask of Holy Water worth 25+ GP, which the spell consumes": "фляга святой воды стоимостью не менее 25 зм, расходуемая заклинанием",
  "a piece of cork": "кусочек пробки",
  "a bit of spiderweb": "кусочек паутины",
  "a copper piece": "медная монета",
  "a grasshopper’s hind leg": "задняя лапка кузнечика",
  "a snake’s tongue and either a bit of honeycomb or a drop of sweet oil": "змеиный язык и кусочек пчелиных сот либо капля сладкого масла",
  "a copper wire": "медная проволока",
  "a legume seed": "семя бобового растения",
  "a drop of honey": "капля мёда",
  "a firefly or phosphorescent moss": "светлячок или фосфоресцирующий мох",
  "1 Copper Piece": "1 медная монета",
  "a short piece of fine copper wire": "короткий кусочек тонкой медной проволоки",
  "two lodestones": "два магнетита",
  "a gilded ladle worth at least 500 GP": "позолоченный черпак стоимостью не менее 500 зм",
  "a morsel of food": "кусочек пищи",
  "a pinch of soot and salt": "щепотка сажи и соли",
  "a hot pepper": "острый перец",
  "a pinch of powdered iron": "щепотка железного порошка",
  "a leather strap": "кожаный ремешок",
  "a pearl worth 100+ GP": "жемчужина стоимостью не менее 100 зм",

 "gilded flower worth 300+ GP":"позолоченный цветок стоимостью не менее 300 зм",
 "pearl worth 100+ GP, consumed":"жемчужина стоимостью не менее 100 зм, расходуемая",
 "gold dust worth 25+ GP, consumed":"золотая пыль стоимостью не менее 25 зм, расходуемая",
 "black marble":"шарик из чёрного мрамора",
 "iron filings":"железные опилки",
 "platinum cord worth 250+ GP, consumed":"платиновый шнур стоимостью не менее 250 зм, расходуемый",
 "onyx shard and caster blood, consumed":"осколок оникса и кровь заклинателя, расходуемые",
 "crystal prism":"кристаллическая призма",
 "nine-pointed iron star":"железная девятиконечная звезда",
 "hourglass with diamond dust worth 5000+ GP, consumed":"песочные часы с алмазной пылью стоимостью не менее 5000 зм, расходуемые",

  "preserved tentacle and eyeball in a platinum-inlaid vial worth 400+ GP": "заспиртованные щупальце и глаз в сосуде с платиновой инкрустацией стоимостью не менее 400 зм",
  "lockbox worth 400+ GP": "запирающаяся шкатулка стоимостью не менее 400 зм",
  "feather, fur and fish tail in a gilded acorn worth 200+ GP": "перо, мех и рыбий хвост в позолоченном жёлуде стоимостью не менее 200 зм",
  "pickled tentacle and eyeball in a platinum-inlaid vial worth 400+ GP": "заспиртованные щупальце и глаз в сосуде с платиновой инкрустацией стоимостью не менее 400 зм",
  "ornate stone and metal lockbox worth 400+ GP": "затейливая запирающаяся шкатулка из камня и металла стоимостью не менее 400 зм",
  "pickled octopus tentacle": "маринованное щупальце осьминога",
  "three nut shells": "три ореховые скорлупки",
  "holy water or powdered silver and iron":
    "святая вода либо порошок серебра и железа",
  "powdered silver and iron": "порошок серебра и железа",
  "a tiny ball of bat guano and sulfur":
    "маленький шарик помёта летучей мыши и серы",
  "a ball of bat guano and sulfur": "шарик помёта летучей мыши и серы",
  "a wing feather from any bird": "маховое перо любой птицы",
  "a feather": "перо",
  "a bit of pork rind or butter": "кусочек свиной шкурки или сливочного масла",
  "either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end":
    "маленькая кожаная петля либо золотая проволока, согнутая в чашечку с длинным стержнем на одном конце",
  "a metal spring": "металлическая пружина",
  "ashes from a burned leaf of mistletoe and a sprig of spruce":
    "пепел сожжённого листа омелы и еловая веточка",
  "ashes from burned mistletoe": "пепел сожжённой омелы",
  "a caterpillar cocoon": "кокон гусеницы",
  "rare oils and unguents worth at least 1,000 gp, which the spell consumes":
    "редкие масла и мази стоимостью не менее 1000 зм, расходуемые заклинанием",
  "rare oils worth 1,000+ GP, which the spell consumes":
    "редкие масла стоимостью не менее 1000 зм, расходуемые заклинанием",
  "a pinch of talc": "щепотка талька",
  "a moonseed leaf": "лист луносемянника",
  "a prayer scroll": "свиток молитвы",
  "a short piece of copper wire": "короткий кусок медной проволоки",
  "a tiny bell and a piece of fine silver wire": "крошечный колокольчик и кусок тонкой серебряной проволоки",
  "gold dust worth at least 25 gp, which the spell consumes": "золотая пыль стоимостью не менее 25 зм, расходуемая заклинанием",
  "incense and powdered diamond worth at least 200 gp, which the spell consumes": "благовония и алмазная пыль стоимостью не менее 200 зм, расходуемые заклинанием",
  "a pinch of powdered iron or iron filings": "щепотка железного порошка или опилок",
};

/** Translate known metadata without guessing unknown material components. */
export function spellMetadata(
  spell: SpellOption,
  language: RuleLanguage = "ru",
) {
  const values = {
    castingTime: spell.castingTime,
    range: spell.range,
    duration: spell.duration,
    components: spell.components ?? "",
  };
  if (language === "en") return values;
  const translate = (value: string) =>
    value
      .replace(/[\u00ad\u2010\u2011\u2012\u2013\u2014]/g, "-")
      .replace(/-+/g, "-")
      .replace(/\bone minute\b/gi, "1 мин.")
      .replace(/(\d+)-mile radius/gi, "радиус $1 миль")
      .replace("1 reaction, which you take when you see a creature within 60 feet of you casting a spell", "реакция, когда вы видите, как существо в пределах 60 фт. сотворяет заклинание")
      .replace("1 action or 8 hours", "1 действие или 8 ч.")
      .replace(/(\d+)-foot-radius hemisphere/gi, "полусфера радиусом $1 фт.")
      .replace("Reaction, which you take when you see a creature within 60 feet of yourself casting a spell with Verbal, Somatic, or Material components", "реакция, когда вы видите, как существо в пределах 60 фт. сотворяет заклинание с вербальным, соматическим или материальным компонентом")
      .replace("Action (Overgrowth) or 8 hours (Enrichment)", "действие (разрастание) или 8 ч. (обогащение)")
      .replace("Bonus Action, immediately after a Melee weapon or Unarmed Strike hit", "бонусное действие сразу после попадания рукопашным оружием или Безоружным ударом")
      .replace("Bonus Action, immediately after hitting with a melee weapon or Unarmed Strike", "бонусное действие сразу после попадания рукопашным оружием или Безоружным ударом")
      .replace("Reaction, when you take Acid, Cold, Fire, Lightning, or Thunder damage", "реакция при получении урона кислотой, холодом, огнём, электричеством или громом")
      .replace(/(\d+)-foot line/gi, "линия $1 фт.")
      .replace(/(\d+)-foot radius/gi, "радиус $1 фт.")
      .replace(/(\d+)-foot Emanation/gi, "эманация $1 фт.")
      .replace(/\bSight\b/g, "В пределах видимости")
      .replace("1 reaction, which you take when you or a creature within 60 feet of you falls", "реакция, когда падаете вы или существо в пределах 60 фт.")
      .replace("1 reaction, which you take in response to being damaged by a creature within 60 feet of you that you can see", "реакция на получение урона от видимого вами существа в пределах 60 фт.")
      .replace("1 reaction, which you take when you are hit by an attack or targeted by the magic missile spell", "реакция, когда по вам попали атакой или выбрали целью Волшебной стрелы")
      .replace(/(\d+)-foot cone/gi, "конус $1 фт.")
      .replace(/(\d+)-foot cube/gi, "куб $1 фт.")
      .replace(/Bonus Action, which you take immedi-?\s*ately after hitting a target with a Melee weapon or an Unarmed Strike/, "бонусное действие сразу после попадания по цели рукопашным оружием или Безоружным ударом")
      .replace(/Bonus Action, which you take immedi-?\s*ately after hitting a creature with a weapon/, "бонусное действие сразу после попадания по существу оружием")
      .replace("Reaction, which you take when you or a creature you can see within 60 feet of you falls", "реакция, когда падаете вы или видимое вами существо в пределах 60 фт.")
      .replace("Reaction, which you take in response to taking damage from a creature that you can see within 60 feet of yourself", "реакция на получение урона от видимого вами существа в пределах 60 фт.")
      .replace(/Bonus Action, which you take immedi-?\s*ately after hitting a creature with a Melee weapon or an Unarmed Strike/, "бонусное действие сразу после попадания по существу рукопашным оружием или Безоружным ударом")
      .replace("Reaction, which you take when you are hit by an attack roll or targeted by the Magic Missile spell", "реакция, когда по вам попали броском атаки или выбрали целью Волшебной стрелы")
      .replace(/\bUntil dispelled or triggered\b/gi, "До рассеивания или срабатывания")
      .replace(/\bUntil dispelled\b/gi, "До рассеивания")
      .replace(/\bfoot-radius sphere\b/gi, "фт. радиус сферы")
      .replace(/\bor Ritual\b/gi, "или ритуал")
      .replace(/\bBonus Action\b/gi, "бонусное действие")
      .replace(/\bReaction\b/gi, "реакция")
      .replace(/\bAction\b/gi, "действие")
      .replace(/\bConcentration,? up to\b/gi, "Концентрация, до")
      .replace(/\bUp to\b/gi, "До")
      .replace(/\bInstantaneous\b/gi, "Мгновенно")
      .replace(/\bUnlimited\b/gi, "Не ограничена")
      .replace(/\bSpecial\b/gi, "Особая")
      .replace(/\bTouch\b/gi, "Касание")
      .replace(/\bSelf\b/gi, "На себя")
      .replace(/\bfeet\b/gi, "фт.")
      .replace(/\bmiles?\b/gi, "миль")
      .replace(/\bminutes?\b/gi, "мин.")
      .replace(/\bhours?\b/gi, "ч.")
      .replace(/\bdays?\b/gi, "дн.")
      .replace(/\brounds?\b/gi, "раунд");
  return {
    castingTime: translate(values.castingTime),
    range: translate(values.range),
    duration: translate(values.duration),
    components: values.components
      .replace(
        /\((.*)\)/,
        (_, material: string) => `(${materials[material] ?? materials[material.replace(/[\u00ad\u2010\u2011\u2012\u2013\u2014-]+/g, "-").replace(/\s+/g, " ")] ?? material})`,
      )
      .replace(/^V\b/, "В")
      .replace(/\bS\b/, "С")
      .replace(/\bM\b/, "М"),
  };
}
