import type { SpellOption } from "./rules-data";
export const WIZARD_SPELLS: SpellOption[] = [
  {
    id: "summon-fey-2014",
    name: "Призыв духа феи · Summon Fey",
    editions: ["2014"],
    level: 3,
    school: "Вызов",
    classes: ["wizard", "druid", "warlock", "ranger"],
    castingTime: "Action",
    range: "90 feet",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components: "V, S, M (gilded flower worth at least 300 GP)",
    source: "Tasha’s Cauldron of Everything",
    sourceUrl: "https://dnd.su/spells/3070-summon_fey/",
    creatureReferenceIds: ["fey-spirit-2014"],
    summary:
      "Дух феи с выбранным настроением; полный блок характеристик включён.",
    descriptionRu:
      "В видимом свободном месте в дистанции появляется Дух феи из встроенного блока характеристик. Выберите внешний вид и настроение: сердитое, довольное или игривое. Дух дружественен вам и вашим спутникам, имеет вашу инициативу и ходит сразу после вас. Подчиняется устным приказам, которые не требуют вашего действия. Без приказа Уклоняется и двигается, избегая опасности. Исчезает при 0 хитов или окончании заклинания. Круг потраченной ячейки определяет его параметры; при ячейке 4+ используйте этот повышенный круг во всех формулах.",
    description:
      "A Fey Spirit appears in a visible unoccupied space within range; use the included statistics. Choose its appearance and a Fuming, Mirthful, or Tricksy mood. It is friendly to you and your companions, shares your Initiative, and acts immediately after you. It follows verbal orders without using your action. Without orders, it Dodges and moves away from danger. It disappears at 0 HP or when the spell ends. Use the expended slot level in all its formulas, including when casting with a level 4+ slot.",
  },
  {
    id: "summon-fey-2024",
    name: "Вызов феи · Summon Fey",
    editions: ["2024"],
    level: 3,
    school: "Вызов",
    classes: ["wizard", "druid", "warlock", "ranger"],
    castingTime: "Action",
    range: "90 feet",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components: "V, S, M (gilded flower worth 300+ GP)",
    source: "Player’s Handbook (2024)",
    sourceUrl: "https://next.dnd.su/spells/10307-summon-fey/",
    creatureReferenceIds: ["fey-spirit-2024"],
    summary: "Призыв духа феи с одним из трёх настроений; статблок включён.",
    descriptionRu:
      "В видимом свободном месте в дистанции призовите Духа феи. Выберите внешний вид феи и настроение: сердитое, довольное или игривое. Используйте встроенный статблок. Дух — союзник вам и вашим союзникам; с вашей инициативой ходит сразу после вас. Устные команды не требуют вашего действия. Без команд Уклоняется и перемещается, избегая опасности. Исчезает при 0 хитов или окончании заклинания. Все формулы используют круг потраченной ячейки.",
    description:
      "Summon a Fey Spirit in a visible unoccupied space within range. Choose its Fey appearance and Fuming, Mirthful, or Tricksy mood, using the included statistics. It is allied with you and your allies, shares your Initiative, and acts immediately after you. Verbal commands require no action from you. Without orders, it Dodges and moves to avoid danger. It vanishes at 0 HP or when the spell ends. All spell-level formulas use the expended slot level.",
  },
];

const dun = (
  id: string,
  name: string,
  level: number,
  school: string,
  range: string,
  duration: string,
  components: string,
  ru: string,
  en: string,
  path: string,
  castingTime = "Action",
  concentration = false,
  ritual = false,
): SpellOption => ({
  id: id + "-2014",
  name,
  editions: ["2014"],
  level,
  school,
  classes: ["wizard"],
  subclassOnly: ["chronurgy", "graviturgy"],
  range,
  duration,
  components,
  castingTime,
  concentration,
  ritual,
  source: "Explorer’s Guide to Wildemount",
  sourceUrl: "https://dnd.su/spells/" + path + "/",
  summary: ru,
  descriptionRu: ru,
  description: en,
});
WIZARD_SPELLS.push(
  dun(
    "sapping-sting",
    "Иссушающий укол · Sapping Sting",
    0,
    "Некромантия",
    "30 feet",
    "Instantaneous",
    "V, S",
    "Видимая цель делает спасбросок Телосложения. Провал: 1d4 некротического урона и падение ничком. Урон 2d4 на 5-м, 3d4 на 11-м и 4d4 на 17-м уровне персонажа.",
    "One visible creature makes a Constitution save. Failure: 1d4 Necrotic damage and Prone. Damage becomes 2d4 at character level 5, 3d4 at 11, and 4d4 at 17.",
    "2441-sapping-sting",
  ),
  dun(
    "gift-of-alacrity",
    "Дар готовности · Gift of Alacrity",
    1,
    "Прорицание",
    "Touch",
    "8 hours",
    "V, S",
    "Касанием дайте согласному существу возможность добавлять 1d8 к броскам инициативы на время действия.",
    "Touch a willing creature. For the duration it may add 1d8 to Initiative rolls.",
    "2442-gift-of-alacrity",
    "1 minute",
  ),
  dun(
    "magnify-gravity",
    "Притяжение · Magnify Gravity",
    1,
    "Преобразование",
    "60 feet",
    "1 round",
    "V, S",
    "Сфера радиусом 10 фт. вокруг видимой точки. Существа при появлении: спасбросок Телосложения; провал — 2d8 силового урона и половина скорости до конца следующего хода цели, успех — половина урона без замедления. До конца вашего следующего хода поднять/переместить неносимый предмет внутри можно только проверкой Силы против вашей Сл. Ячейка 2+: +1d8 за круг выше 1.",
    "A 10-foot-radius sphere forms at a visible point. Creatures inside make Constitution saves: failure deals 2d8 Force damage and halves Speed until the end of their next turn; success deals half damage without slowing. Until your next turn ends, moving or lifting an unworn, uncarried object inside requires a Strength check against your spell DC. Slots 2+: +1d8 per level above 1.",
    "2444-magnify-gravity",
  ),
  dun(
    "fortunes-favor",
    "Благословение удачи · Fortune’s Favor",
    2,
    "Прорицание",
    "60 feet",
    "1 hour",
    "V, S, M (pearl worth 100+ GP, consumed)",
    "Вы или видимая согласная цель можете один раз окончить эффект, бросив дополнительный d20 для своей атаки, проверки или спасброска и выбрав результат. Также можно сделать это для атаки по цели и выбрать старый или новый результат атакующего. Дополнительный d20 бросается после разрешения преимущества/помехи исходного броска. Ячейка 3+: ещё одна цель за круг выше 2.",
    "You or a visible willing creature can end the effect to roll an additional d20 for its attack, check, or save and choose which result to use. Alternatively it can do so for an attack against it, choosing the attacker’s original or new result. Roll the extra die after resolving the original roll’s Advantage or Disadvantage. Slots 3+: one additional target per level above 2.",
    "2445-fortunes-favor",
    "1 minute",
  ),
  dun(
    "temporal-shunt",
    "Временной сдвиг · Temporal Shunt",
    5,
    "Преобразование",
    "120 feet",
    "1 round",
    "V, S",
    "Реакция: видимое существо делает атаку или сотворяет заклинание. Оно делает спасбросок Мудрости; провал переносит его из текущего времени, атака промахивается или заклинание не действует. В начале следующего хода цель возвращается в исходное либо ближайшее свободное место, не помня сотворения и воздействия. Ячейка 6+: ещё одна цель за круг выше 5; все цели в пределах 30 фт. друг от друга.",
    "Reaction when a visible creature attacks or casts a spell: it makes a Wisdom save. Failure shifts it out of the present, making its attack miss or its spell have no effect. At the start of its next turn it returns to its original or nearest unoccupied space, remembering neither the casting nor the effect. Slots 6+: one extra target per level above 5; all targets must be within 30 feet of each other.",
    "2450-temporal-shunt",
    "Reaction",
  ),
  dun(
    "immovable-object",
    "Неподвижный предмет · Immovable Object",
    2,
    "Преобразование",
    "Touch",
    "1 hour",
    "V, S, M (gold dust worth 25+ GP, consumed)",
    "Касанием закрепите предмет до 10 фунтов в пространстве. Вы и названные при сотворении существа перемещаете его свободно. Заданный пароль, произнесённый в 5 фт., подавляет эффект на 1 минуту. Максимальная нагрузка 4000 фунтов; превышение оканчивает заклинание. Действием проверка Силы против вашей Сл позволяет сдвинуть предмет до 10 фт. Ячейка 4–5: 8000 фунтов, Сл +5, 24 часа; 6+: 20000 фунтов, Сл +10, до рассеивания.",
    "Touch an object weighing at most 10 pounds to fix it in space. You and creatures designated when casting can move it freely. A chosen password spoken within 5 feet suppresses the effect for 1 minute. It supports 4,000 pounds; excess weight ends the spell. An action and successful Strength check against your spell DC moves it up to 10 feet. Slots 4–5: 8,000 pounds, DC +5, 24 hours. Slots 6+: 20,000 pounds, DC +10, until dispelled.",
    "2446-immovable-object",
  ),
  dun(
    "wristpocket",
    "Карман на запястье · Wristpocket",
    2,
    "Преобразование",
    "Self",
    "1 hour",
    "S",
    "Предмет до 5 фунтов, который держите только вы, исчезает из руки в карманное измерение. Действием верните его в свободную руку; другим действием можно спрятать обратно. При окончании заклинания спрятанный предмет падает у ваших ног.",
    "An object weighing no more than 5 pounds and held only by you vanishes from your hand into a pocket dimension. Use an action to retrieve it into a free hand, or another action to hide it again. If still stored when the spell ends, it falls at your feet.",
    "2447-wristpocket",
    "Action",
    true,
    true,
  ),
  dun(
    "pulse-wave",
    "Силовая волна · Pulse Wave",
    3,
    "Воплощение",
    "Self (30-foot cone)",
    "Instantaneous",
    "V, S",
    "В конусе 30 фт. все существа делают спасбросок Телосложения. Провал: 6d6 силового урона и перемещение на 15 фт. к вам либо от вас — выберите одно направление для всех. Успех: половина урона, без перемещения. Незакреплённые предметы также перемещаются на 15 фт. Ячейка 4+: +1d6 урона и +5 фт. перемещения за круг выше 3.",
    "Creatures in a 30-foot Cone make Constitution saves. Failure: 6d6 Force damage and movement 15 feet toward or away from you, choosing one direction for all. Success: half damage and no movement. Unsecured objects also move 15 feet. Slots 4+: +1d6 damage and +5 feet of movement per level above 3.",
    "2448-pulse-wave",
  ),
  dun(
    "gravity-sinkhole",
    "Центр притяжения · Gravity Sinkhole",
    4,
    "Воплощение",
    "120 feet",
    "Instantaneous",
    "V, S, M (black marble)",
    "В сфере радиусом 20 фт. вокруг видимой точки все существа делают спасбросок Телосложения. Провал: 5d10 силового урона и притяжение по прямой в свободное место максимально близко к центру, даже в воздухе. Успех: половина урона без перемещения. Ячейка 5+: +1d10 за круг выше 4.",
    "Creatures in a 20-foot-radius sphere at a visible point make Constitution saves. Failure: 5d10 Force damage and a straight pull to the nearest unoccupied space to the center, even in midair. Success: half damage without movement. Slots 5+: +1d10 per level above 4.",
    "2449-gravity-sinkhole",
  ),
  dun(
    "gravity-fissure",
    "Гравитационный разлом · Gravity Fissure",
    6,
    "Воплощение",
    "Self (100-foot line)",
    "Instantaneous",
    "V, S, M (iron filings)",
    "Линия от вас длиной 100 фт. и шириной 5 фт. Существа в ней: спасбросок Телосложения, 8d8 силового урона при провале или половина при успехе. Существа вне линии, но не дальше 10 фт. от неё, также делают этот спасбросок: провал — 8d8 урона и притяжение по прямой в линию; успех — без эффекта. Ячейка 7+: +1d8 за круг выше 6.",
    "A line extends 100 feet from you, 5 feet wide. Creatures in it make Constitution saves: 8d8 Force damage on failure, half on success. Creatures outside but within 10 feet of the line also save: failure deals 8d8 Force damage and pulls them straight into the line; success has no effect. Slots 7+: +1d8 per level above 6.",
    "2451-gravity-fissure",
  ),
  dun(
    "tether-essence",
    "Единство сущностей · Tether Essence",
    7,
    "Некромантия",
    "60 feet",
    "1 hour",
    "V, S, M (platinum cord worth 250+ GP, consumed)",
    "Две видимые цели делают спасброски Телосложения с помехой, если в пределах 30 фт. друг от друга; можно добровольно провалить. При любом успехе эффекта нет. Два провала связывают цели независимо от последующего расстояния: полученный одной урон или восстановленные хиты в том же количестве применяются ко второй. При 0 хитов у любой либо прекращении заклинания на любой связь оканчивается для обеих.",
    "Two visible creatures make Constitution saves, with Disadvantage if within 30 feet of each other; either may willingly fail. Any success prevents the effect. Two failures link them regardless of subsequent distance: damage taken or HP restored by one applies equally to the other. The spell ends for both if either reaches 0 HP or if the effect ends on either.",
    "2452-tether-essence",
    "Action",
    true,
  ),
  dun(
    "dark-star",
    "Тёмная звезда · Dark Star",
    8,
    "Воплощение",
    "150 feet",
    "1 minute",
    "V, S, M (onyx shard and caster blood, consumed)",
    "Создайте сферу радиусом до 40 фт. в выбранной точке: труднопроходимая местность, магическая тьма, непроницаемая тёмному зрению и немагическому свету. Звук не возникает внутри и не проходит через сферу. Полностью внутри: иммунитет к звуковому урону, существа оглохшие, вербальные компоненты невозможны. При первом входе за ход или начале хода внутри: спасбросок Телосложения, 8d10 силового урона при провале, половина при успехе. При 0 хитов от этого урона цель и её немагические носимые/несомые предметы распадаются в пыль.",
    "Create a sphere up to 40 feet in radius: Difficult Terrain and magical Darkness blocking Darkvision and nonmagical light. Sound cannot originate inside or pass through. Fully enclosed creatures and objects are immune to Thunder; creatures are Deafened and cannot use Verbal components. On first entering during a turn or starting a turn inside, make a Constitution save: 8d10 Force damage on failure, half on success. Reduction to 0 HP by this damage turns the creature and its worn or carried nonmagical objects to dust.",
    "2453-dark-star",
    "Action",
    true,
  ),
  dun(
    "reality-break",
    "Брешь в реальности · Reality Break",
    8,
    "Вызов",
    "60 feet",
    "1 minute",
    "V, S, M (crystal prism)",
    "Цель делает спасбросок Мудрости; провал запрещает реакции. В начале каждого своего хода бросает d10 по встроенной таблице; в конце хода повторяет спасбросок Мудрости, завершая эффект при успехе. d10: 1–2 — 6d12 психического урона и ошеломление до конца хода; 3–5 — спасбросок Ловкости, 8d12 силового урона при провале, половина при успехе; 6–8 — телепортация со снаряжением до 30 фт. в выбранное вами видимое свободное место, 10d12 силового урона и ничком; 9–10 — 10d12 холода и ослепление до конца хода.",
    "The target makes a Wisdom save; failure prevents Reactions. At each turn’s start roll d10 on the included table; at turn’s end repeat the Wisdom save, ending the spell on success. d10: 1–2, 6d12 Psychic damage and Stunned until turn end; 3–5, Dexterity save for 8d12 Force damage, half on success; 6–8, teleport with equipment up to 30 feet to a visible unoccupied space you choose, take 10d12 Force damage and fall Prone; 9–10, 10d12 Cold damage and Blinded until turn end.",
    "2454-reality-break",
    "Action",
    true,
  ),
  dun(
    "ravenous-void",
    "Ревущая бездна · Ravenous Void",
    9,
    "Воплощение",
    "1000 feet",
    "1 minute",
    "V, S, M (nine-pointed iron star)",
    "Сфера радиусом 20 фт. вокруг видимой точки; внутри и в пределах 100 фт. от неё труднопроходимая местность. Неносимые/несомые немагические предметы целиком внутри уничтожаются. При появлении и в начале ваших ходов незакреплённые предметы в 100 фт. притягиваются максимально близко к центру; существа избегают притяжения спасброском Силы. При первом входе за ход или начале хода внутри: 5d10 силового урона, опутанность до выхода (в воздухе цель парит). Действием проверка Силы против вашей Сл снимает опутанность с себя либо цели в досягаемости. При 0 хитов сфера уничтожает цель и её немагическое снаряжение.",
    "A 20-foot-radius sphere forms at a visible point; it and the area within 100 feet of it are Difficult Terrain. Fully enclosed unworn, uncarried nonmagical objects are destroyed. On creation and at your turns’ starts, unsecured objects within 100 feet are pulled as close to the center as possible; creatures avoid this with Strength saves. First entry on a turn or starting a turn inside deals 5d10 Force damage and Restrains until leaving; airborne targets hover. An action and Strength check against your spell DC frees yourself or a creature within reach from Restrained. Reaching 0 HP in the sphere destroys the creature and its nonmagical equipment.",
    "2455-ravenous-void",
    "Action",
    true,
  ),
  dun(
    "time-ravage",
    "Утрата времени · Time Ravage",
    9,
    "Некромантия",
    "90 feet",
    "Instantaneous",
    "V, S, M (hourglass with diamond dust worth 5000+ GP, consumed)",
    "Видимая цель делает спасбросок Телосложения: 10d12 некротического урона при провале либо половина при успехе. Провал также старит её до смерти от старости через 30 дней; до этого все атаки, проверки и спасброски с помехой, скорость вдвое меньше. Вернуть прежний возраст и снять эти эффекты могут только Исполнение желаний либо Высшее восстановление 9-го круга.",
    "A visible target makes a Constitution save: 10d12 Necrotic damage on failure, half on success. Failure also ages it to die of old age in 30 days; until then attacks, checks, and saves have Disadvantage and Speed is halved. Only Wish or Greater Restoration cast at level 9 reverses these effects and restores its previous age.",
    "2456-time-ravage",
  ),
);

WIZARD_SPELLS.find((s) => s.id === "reality-break-2014")!.randomTableId =
  "reality-break-2014";
